<a href="https://colab.research.google.com/github/Nitisha-27/InsightFlowAI/blob/main/InsightFlowAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q kaggle


import os

BASE = "/content/drive/MyDrive/InsightFlow_AI"

folders = [
    "data/raw",
    "data/processed",
    "data/warehouse",
    "data/synthetic",
    "models",
    "reports",
    "images",
    "exports"
]

for folder in folders:
    os.makedirs(os.path.join(BASE, folder), exist_ok=True)

print("Project folders created successfully!")
import os

os.environ["KAGGLE_API_TOKEN"] = "KGAT_89e3dacbaa7546bf0c558cecdb213d52"
!kaggle datasets download \
-d olistbr/brazilian-ecommerce \
-p "/content/drive/MyDrive/InsightFlow_AI/data/raw"

import zipfile

zip_path = "/content/drive/MyDrive/InsightFlow_AI/data/raw/brazilian-ecommerce.zip"
extract_path = "/content/drive/MyDrive/InsightFlow_AI/data/raw"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

base = "/content/drive/MyDrive/InsightFlow_AI/data/raw/"

customers = pd.read_csv(base + "olist_customers_dataset.csv")
orders = pd.read_csv(base + "olist_orders_dataset.csv")
order_items = pd.read_csv(base + "olist_order_items_dataset.csv")
payments = pd.read_csv(base + "olist_order_payments_dataset.csv")
reviews = pd.read_csv(base + "olist_order_reviews_dataset.csv")
products = pd.read_csv(base + "olist_products_dataset.csv")
sellers = pd.read_csv(base + "olist_sellers_dataset.csv")
geolocation = pd.read_csv(base + "olist_geolocation_dataset.csv")
translation = pd.read_csv(base + "product_category_name_translation.csv")

datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Reviews": reviews,
    "Products": products,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Translation": translation
}

for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print("Shape:", df.shape)
    print(df.head())
    print()

Project folders created successfully!
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce
License(s): CC-BY-NC-SA-4.0
Downloading brazilian-ecommerce.zip to /content/drive/MyDrive/InsightFlow_AI/data/raw
100% 42.6M/42.6M [00:00<00:00, 162MB/s]

Dataset extracted successfully!
======================================================================
Customers
Shape: (99441, 5)
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

======================================================================
Orders
Shape: (99441, 8)
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

======================================================================
Order Items
Shape: (112650, 7)
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

======================================================================
Payments
Shape: (103886, 5)
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

======================================================================
Reviews
Shape: (99224, 7)
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

======================================================================
Products
Shape: (32951, 9)
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

======================================================================
Sellers
Shape: (3095, 4)
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

======================================================================
Geolocation
Shape: (1000163, 5)
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

======================================================================
Translation
Shape: (71, 2)
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Data Profiling

In [ ]:
def profile_dataframe(df, name):
    print("="*80)
    print(f"📂 {name}")
    print("="*80)

    print(f"\nShape: {df.shape}")

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nData Types")
    print(df.dtypes)

    print("\nMemory Usage")
    print(f"{df.memory_usage(deep=True).sum()/1024**2:.2f} MB")

    print("\nUnique Values")
    print(df.nunique())

    print("\nNumerical Summary")
    display(df.describe(include='all').T)

profile_dataframe(customers,"Customers")
profile_dataframe(orders,"Orders")
profile_dataframe(order_items,"Order Items")
profile_dataframe(payments,"Payments")
profile_dataframe(reviews,"Reviews")
profile_dataframe(products,"Products")
profile_dataframe(sellers,"Sellers")
profile_dataframe(geolocation,"Geolocation")

================================================================================
📂 Customers
================================================================================

Shape: (99441, 5)

Missing Values
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows
0

Data Types
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

Memory Usage
26.59 MB

Unique Values
customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,99441,99441,274fa6071e5e17fe303b9748641082c8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_unique_id,99441,96096,8d50f5eadf50201ccdcedfb9e2ac8455,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_zip_code_prefix,99441.0,NaN,NaN,NaN,35137.474583,29797.938996,1003.0,11347.0,24416.0,58900.0,99990.0
customer_city,99441,4119,sao paulo,15540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_state,99441,27,SP,41746,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
📂 Orders
================================================================================

Shape: (99441, 8)

Missing Values
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate Rows
0

Data Types
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

Memory Usage
52.94 MB

Unique Values
order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

Numerical Summary

,count,unique,top,freq
order_id,99441,99441,66dea50a8b16d9b4dee7af250b4be1a5,1
customer_id,99441,99441,edb027a75a1449115f6b43211ae02a24,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-08-02 12:06:07,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-14 20:02:44,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

================================================================================
📂 Order Items
================================================================================

Shape: (112650, 7)

Missing Values
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicate Rows
0

Data Types
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

Memory Usage
35.99 MB

Unique Values
order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,112650,98666,8272b63d03f5f79c56e9e4120aec44ef,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_item_id,112650.0,NaN,NaN,NaN,1.197834,0.705124,1.0,1.0,1.0,1.0,21.0
product_id,112650,32951,aca2eb7d00ea1a7b8ebd4e68314663af,527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_id,112650,3095,6560211a19b47992c3666cc44a7e94c0,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipping_limit_date,112650,93318,2017-07-21 18:25:23,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,112650.0,NaN,NaN,NaN,120.653739,183.633928,0.85,39.9,74.99,134.9,6735.0
freight_value,112650.0,NaN,NaN,NaN,19.99032,15.806405,0.0,13.08,16.26,21.15,409.68

================================================================================
📂 Payments
================================================================================

Shape: (103886, 5)

Missing Values
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate Rows
0

Data Types
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

Memory Usage
16.23 MB

Unique Values
order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,103886,99440,fa65dad1b0e818e3ccc5cb0e39231352,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_sequential,103886.0,NaN,NaN,NaN,1.092679,0.706584,1.0,1.0,1.0,1.0,29.0
payment_type,103886,5,credit_card,76795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_installments,103886.0,NaN,NaN,NaN,2.853349,2.687051,0.0,1.0,1.0,4.0,24.0
payment_value,103886.0,NaN,NaN,NaN,154.10038,217.494064,0.0,56.79,100.0,171.8375,13664.08

================================================================================
📂 Reviews
================================================================================

Shape: (99224, 7)

Missing Values
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Duplicate Rows
0

Data Types
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

Memory Usage
39.12 MB

Unique Values
review_id                  98410
order_id                   98673
review_score                   5
review_comment_title        4527
review_comment_message     36159
review_creation_date         636
review_answer_timestamp    98248
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
review_id,99224,98410,4548534449b1f572e357211b90724f1b,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_id,99224,98673,03c939fd7fd3b38f8485a0f95798f1f6,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_score,99224.0,NaN,NaN,NaN,4.086421,1.347579,1.0,4.0,5.0,5.0,5.0
review_comment_title,11568,4527,Recomendo,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_message,40977,36159,Muito bom,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_creation_date,99224,636,2017-12-19 00:00:00,463,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_answer_timestamp,99224,98248,2017-06-15 23:21:05,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
📂 Products
================================================================================

Shape: (32951, 9)

Missing Values
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate Rows
0

Data Types
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Memory Usage
6.30 MB

Unique Values
product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product_id,32951,32951,106392145fca363410d287a815be6de4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category_name,32341,73,cama_mesa_banho,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name_lenght,32341.0,NaN,NaN,NaN,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,NaN,NaN,NaN,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,NaN,NaN,NaN,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,NaN,NaN,NaN,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,NaN,NaN,NaN,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,NaN,NaN,NaN,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,NaN,NaN,NaN,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

================================================================================
📂 Sellers
================================================================================

Shape: (3095, 4)

Missing Values
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate Rows
0

Data Types
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

Memory Usage
0.59 MB

Unique Values
seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
seller_id,3095,3095,9e25199f6ef7e7c347120ff175652c3b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_zip_code_prefix,3095.0,NaN,NaN,NaN,32291.059451,32713.45383,1001.0,7093.5,14940.0,64552.5,99730.0
seller_city,3095,611,sao paulo,694,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_state,3095,23,SP,1849,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
📂 Geolocation
================================================================================

Shape: (1000163, 5)

Missing Values
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate Rows
261831

Data Types
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

Memory Usage
130.26 MB

Unique Values
geolocation_zip_code_prefix     19015
geolocation_lat                717360
geolocation_lng                717613
geolocation_city                 8011
geolocation_state                  27
dtype: int64

Numerical Summary

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
geolocation_zip_code_prefix,1000163.0,NaN,NaN,NaN,36574.166466,30549.33571,1001.0,11075.0,26530.0,63504.0,99990.0
geolocation_lat,1000163.0,NaN,NaN,NaN,-21.176153,5.715866,-36.605374,-23.603546,-22.919377,-19.97962,45.065933
geolocation_lng,1000163.0,NaN,NaN,NaN,-46.390541,4.269748,-101.466766,-48.573172,-46.637879,-43.767709,121.105394
geolocation_city,1000163,8011,sao paulo,135800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geolocation_state,1000163,27,SP,404268,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Data Cleaning

In [ ]:
# ============================================================
# DATA CLEANING
# ============================================================

customers_clean = customers.copy()
orders_clean = orders.copy()
order_items_clean = order_items.copy()
payments_clean = payments.copy()
reviews_clean = reviews.copy()
products_clean = products.copy()
sellers_clean = sellers.copy()
geolocation_clean = geolocation.copy()
translation_clean = translation.copy()

print("✅ Clean copies created successfully!")

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        errors="coerce"
    )

reviews_clean["review_creation_date"] = pd.to_datetime(
    reviews_clean["review_creation_date"],
    errors="coerce"
)

reviews_clean["review_answer_timestamp"] = pd.to_datetime(
    reviews_clean["review_answer_timestamp"],
    errors="coerce"
)

order_items_clean["shipping_limit_date"] = pd.to_datetime(
    order_items_clean["shipping_limit_date"],
    errors="coerce"
)

print("✅ Date columns converted!")

print("Before:", geolocation_clean.shape)

geolocation_clean = geolocation_clean.drop_duplicates()

print("After :", geolocation_clean.shape)

products_clean = products_clean.merge(
    translation_clean,
    on="product_category_name",
    how="left"
)

products_clean.drop(
    columns=["product_category_name"],
    inplace=True
)

products_clean.rename(
    columns={
        "product_category_name_english": "product_category"
    },
    inplace=True
)

products_clean.head()

clean_datasets = {
    "Customers": customers_clean,
    "Orders": orders_clean,
    "Order Items": order_items_clean,
    "Payments": payments_clean,
    "Reviews": reviews_clean,
    "Products": products_clean,
    "Sellers": sellers_clean,
    "Geolocation": geolocation_clean
}

for name, df in clean_datasets.items():
    print("=" * 60)
    print(name)
    print(df.isnull().sum())

    SAVE_PATH = "/content/drive/MyDrive/InsightFlow_AI/data/processed/"

customers_clean.to_parquet(SAVE_PATH + "customers.parquet", index=False)
orders_clean.to_parquet(SAVE_PATH + "orders.parquet", index=False)
order_items_clean.to_parquet(SAVE_PATH + "order_items.parquet", index=False)
payments_clean.to_parquet(SAVE_PATH + "payments.parquet", index=False)
reviews_clean.to_parquet(SAVE_PATH + "reviews.parquet", index=False)
products_clean.to_parquet(SAVE_PATH + "products.parquet", index=False)
sellers_clean.to_parquet(SAVE_PATH + "sellers.parquet", index=False)
geolocation_clean.to_parquet(SAVE_PATH + "geolocation.parquet", index=False)

print("✅ Cleaned datasets saved successfully!")

quality_report = pd.DataFrame({
    "Dataset": list(clean_datasets.keys()),
    "Rows": [df.shape[0] for df in clean_datasets.values()],
    "Columns": [df.shape[1] for df in clean_datasets.values()],
    "Missing Values": [df.isnull().sum().sum() for df in clean_datasets.values()],
    "Duplicate Rows": [df.duplicated().sum() for df in clean_datasets.values()]
})

quality_report

✅ Clean copies created successfully!
✅ Date columns converted!
Before: (1000163, 5)
After : (738332, 5)
============================================================
Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
============================================================
Orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
============================================================
Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
============================================================
Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
============================================================
Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
============================================================
Products
product_id                      0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
product_category              623
dtype: int64
============================================================
Sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
============================================================
Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
✅ Cleaned datasets saved successfully!

       Dataset    Rows  Columns  Missing Values  Duplicate Rows
0    Customers   99441        5               0               0
1       Orders   99441        8            4908               0
2  Order Items  112650        7               0               0
3     Payments  103886        5               0               0
4      Reviews   99224        7          145903               0
5     Products   32951        9            2461               0
6      Sellers    3095        4               0               0
7  Geolocation  738332        5               0               0

Data warehouse

In [ ]:
# ============================================================
# PHASE 3
# CREATE ANALYTICS WAREHOUSE
# ============================================================

print("="*80)
print("CREATING ANALYTICS WAREHOUSE")
print("="*80)

# ------------------------------------------------------------
# Orders + Customers
# ------------------------------------------------------------

warehouse = orders_clean.merge(
    customers_clean,
    on="customer_id",
    how="left"
)

print("After Customers :", warehouse.shape)

# ------------------------------------------------------------
# Order Items
# ------------------------------------------------------------

warehouse = warehouse.merge(
    order_items_clean,
    on="order_id",
    how="left"
)

print("After Order Items :", warehouse.shape)

# ------------------------------------------------------------
# Products
# ------------------------------------------------------------

warehouse = warehouse.merge(
    products_clean,
    on="product_id",
    how="left"
)

print("After Products :", warehouse.shape)

# ------------------------------------------------------------
# Sellers
# ------------------------------------------------------------

warehouse = warehouse.merge(
    sellers_clean,
    on="seller_id",
    how="left"
)

print("After Sellers :", warehouse.shape)

# ------------------------------------------------------------
# Payments
# ------------------------------------------------------------

payment_summary = (

    payments_clean

    .groupby("order_id")

    .agg(

        total_payment=("payment_value","sum"),

        payment_type=("payment_type", lambda x: ",".join(sorted(x.astype(str).unique()))),

        payment_installments=("payment_installments","max")

    )

    .reset_index()

)

warehouse = warehouse.merge(
    payment_summary,
    on="order_id",
    how="left"
)

print("After Payments :", warehouse.shape)

# ------------------------------------------------------------
# Reviews
# ------------------------------------------------------------

review_summary = (

    reviews_clean

    .groupby("order_id")

    .agg(

        review_id=("review_id","first"),

        review_score=("review_score","mean"),

        review_comment_title=("review_comment_title","first"),

        review_comment_message=("review_comment_message","first"),

        review_creation_date=("review_creation_date","first"),

        review_answer_timestamp=("review_answer_timestamp","first")

    )

    .reset_index()

)

warehouse = warehouse.merge(
    review_summary,
    on="order_id",
    how="left"
)

print("After Reviews :", warehouse.shape)

# ------------------------------------------------------------
# DELIVERY FEATURES
# ------------------------------------------------------------

warehouse["approval_hours"] = (

    warehouse["order_approved_at"]

    -

    warehouse["order_purchase_timestamp"]

).dt.total_seconds() / 3600

warehouse["shipping_days"] = (

    warehouse["order_delivered_carrier_date"]

    -

    warehouse["order_approved_at"]

).dt.days

warehouse["delivery_days"] = (

    warehouse["order_delivered_customer_date"]

    -

    warehouse["order_delivered_carrier_date"]

).dt.days

warehouse["estimated_delivery_days"] = (

    warehouse["order_estimated_delivery_date"]

    -

    warehouse["order_purchase_timestamp"]

).dt.days

# ------------------------------------------------------------
# DATE FEATURES
# ------------------------------------------------------------

warehouse["purchase_year"] = (
    warehouse["order_purchase_timestamp"].dt.year
)

warehouse["purchase_month"] = (
    warehouse["order_purchase_timestamp"].dt.month_name()
)

warehouse["purchase_month_num"] = (
    warehouse["order_purchase_timestamp"].dt.month
)

warehouse["purchase_day"] = (
    warehouse["order_purchase_timestamp"].dt.day_name()
)

warehouse["purchase_hour"] = (
    warehouse["order_purchase_timestamp"].dt.hour
)

warehouse["purchase_quarter"] = (
    warehouse["order_purchase_timestamp"].dt.quarter
)

# ------------------------------------------------------------
# REVIEW CATEGORY
# ------------------------------------------------------------

warehouse["review_category"] = pd.cut(

    warehouse["review_score"],

    bins=[0,2,3,4,5],

    labels=[

        "Poor",

        "Average",

        "Good",

        "Excellent"

    ],

    include_lowest=True

)

# ------------------------------------------------------------
# PRODUCT FEATURES
# ------------------------------------------------------------

warehouse["product_volume_cm3"] = (

    warehouse["product_length_cm"]

    *

    warehouse["product_width_cm"]

    *

    warehouse["product_height_cm"]

)

warehouse["total_product_cost"] = (

    warehouse["price"]

    +

    warehouse["freight_value"]

)

# ------------------------------------------------------------
# LOCAL ORDER
# ------------------------------------------------------------

warehouse["local_order"] = (

    warehouse["customer_state"]

    ==

    warehouse["seller_state"]

)

print("\n")

print("="*80)
print("WAREHOUSE CREATED SUCCESSFULLY")
print("="*80)

print("Rows :", warehouse.shape[0])
print("Columns :", warehouse.shape[1])

display(warehouse.head())

================================================================================
CREATING ANALYTICS WAREHOUSE
================================================================================
After Customers : (99441, 12)
After Order Items : (113425, 18)
After Products : (113425, 26)
After Sellers : (113425, 29)
After Payments : (113425, 32)
After Reviews : (113425, 38)


================================================================================
WAREHOUSE CREATED SUCCESSFULLY
================================================================================
Rows : 113425
Columns : 52

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category,seller_zip_code_prefix,seller_city,seller_state,total_payment,payment_type,payment_installments,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,approval_hours,shipping_days,delivery_days,estimated_delivery_days,purchase_year,purchase_month,purchase_month_num,purchase_day,purchase_hour,purchase_quarter,review_category,product_volume_cm3,total_product_cost,local_order
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,9350.0,maua,SP,38.71,"credit_card,voucher",1.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,None,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,0.178333,2.0,6.0,15,2017,October,10,Monday,10,4,Good,1976.0,38.71,True
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery,31570.0,belo horizonte,SP,141.46,boleto,1.0,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,30.713889,0.0,12.0,19,2018,July,7,Tuesday,20,3,Good,4693.0,141.46,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto,14840.0,guariba,SP,179.12,credit_card,3.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,None,None,2018-08-18,2018-08-22 19:07:58,0.276111,0.0,9.0,26,2018,August,8,Wednesday,8,3,Excellent,9576.0,179.12,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,59.0,468.0,3.0,450.0,30.0,10.0,20.0,pet_shop,31842.0,belo horizonte,MG,72.20,credit_card,1.0,359d03e676b3c069f62cadba8dd3f6e8,5.0,None,O produto foi exatamente o que eu esperava e e...,2017-12-03,2017-12-05 19:21:58,0.298056,3.0,9.0,26,2017,November,11,Saturday,19,4,Excellent,6000.0,72.20,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,38.0,316.0,4.0,250.0,51.0,15.0,15.0,stationery,8752.0,mogi das cruzes,SP,28.62,credit_card,1.0,e50934924e227544ba8246aeb3770dd4,5.0,None,None,2018-02-17,2018-02-18 13:02:51,1.030556,0.0,1.0,12,2018,February,2,Tuesday,21,1,Excellent,11475.0,28.62,True

Analytics Warehouse

In [ ]:
# ============================================================
# DATA QUALITY FIXES
# ============================================================

import numpy as np

# Invalid shipping days
warehouse.loc[
    warehouse["shipping_days"] < 0,
    "shipping_days"
] = np.nan

# Product category
warehouse["product_category"] = warehouse["product_category"].fillna("Unknown")

# Review category
warehouse["review_category"] = (
    warehouse["review_category"]
    .cat.add_categories(["No Review"])
    .fillna("No Review")
)

# Price per gram
warehouse["price_per_gram"] = (
    warehouse["price"] /
    warehouse["product_weight_g"].replace(0, np.nan)
)

# Delivery completed
warehouse["delivery_completed"] = (
    warehouse["order_delivered_customer_date"].notna()
)

# Product density
warehouse["product_density"] = (
    warehouse["product_weight_g"] /
    warehouse["product_volume_cm3"].replace(0, np.nan)
)

# ============================================================
# CUSTOMER FEATURES
# ============================================================

warehouse = warehouse.sort_values(
    ["customer_unique_id",
     "order_purchase_timestamp"]
)

warehouse["customer_order_number"] = (
    warehouse.groupby("customer_unique_id")
    .cumcount()+1
)

warehouse["repeat_customer"] = (
    warehouse["customer_order_number"] > 1
)

customer_orders = (
    warehouse.groupby("customer_unique_id")
    ["order_id"]
    .transform("nunique")
)

warehouse["customer_total_orders"] = customer_orders

warehouse["customer_lifetime_value"] = (
    warehouse.groupby("customer_unique_id")
    ["total_payment"]
    .transform("sum")
)

warehouse["customer_avg_order_value"] = (
    warehouse.groupby("customer_unique_id")
    ["total_payment"]
    .transform("mean")
)

warehouse["customer_first_purchase"] = (
    warehouse.groupby("customer_unique_id")
    ["order_purchase_timestamp"]
    .transform("min")
)

warehouse["customer_last_purchase"] = (
    warehouse.groupby("customer_unique_id")
    ["order_purchase_timestamp"]
    .transform("max")
)

warehouse["customer_tenure_days"] = (

    warehouse["customer_last_purchase"]

    -

    warehouse["customer_first_purchase"]

).dt.days

warehouse["new_customer"] = (
    warehouse["customer_order_number"] == 1
)

# ============================================================
# PRODUCT FEATURES
# ============================================================

warehouse["product_sales_count"] = (
    warehouse.groupby("product_id")
    ["order_id"]
    .transform("count")
)

warehouse["product_total_revenue"] = (
    warehouse.groupby("product_id")
    ["total_payment"]
    .transform("sum")
)

warehouse["product_avg_review"] = (
    warehouse.groupby("product_id")
    ["review_score"]
    .transform("mean")
)

warehouse["product_avg_price"] = (
    warehouse.groupby("product_id")
    ["price"]
    .transform("mean")
)

warehouse["product_popularity_rank"] = (
    warehouse["product_sales_count"]
    .rank(method="dense", ascending=False)
)

# ============================================================
# SELLER FEATURES
# ============================================================

warehouse["seller_total_orders"] = (
    warehouse.groupby("seller_id")
    ["order_id"]
    .transform("count")
)

warehouse["seller_revenue"] = (
    warehouse.groupby("seller_id")
    ["total_payment"]
    .transform("sum")
)

warehouse["seller_avg_review"] = (
    warehouse.groupby("seller_id")
    ["review_score"]
    .transform("mean")
)

warehouse["seller_rank"] = (
    warehouse["seller_revenue"]
    .rank(
        ascending=False,
        method="dense"
    )
)

# ============================================================
# DELIVERY FEATURES
# ============================================================

warehouse["delivery_delay_days"] = (

    warehouse["delivery_days"]

    -

    warehouse["estimated_delivery_days"]

)

warehouse["early_delivery"] = (
    warehouse["delivery_delay_days"] < 0
)

warehouse["on_time_delivery"] = (
    warehouse["delivery_delay_days"] <= 0
)

warehouse["late_delivery_days"] = (
    warehouse["delivery_delay_days"]
    .clip(lower=0)
)

# ============================================================
# REVENUE FEATURES
# ============================================================

warehouse["freight_percentage"] = (

    warehouse["freight_value"]

    /

    warehouse["total_product_cost"]

) * 100

warehouse["profit_proxy"] = (

    warehouse["price"]

    -

    warehouse["freight_value"]

)

warehouse["high_margin"] = (
    warehouse["profit_proxy"] >
    warehouse["profit_proxy"].median()
)

warehouse["premium_order"] = (
    warehouse["total_payment"] >
    warehouse["total_payment"].quantile(0.90)
)

# ============================================================
# FINAL FEATURE ENRICHMENT
# (Run this BEFORE saving the warehouse)
# ============================================================

print("="*80)
print("ADDING FINAL BUSINESS FEATURES")
print("="*80)

# ------------------------------------------------------------
# 1. Product Average Review
# ------------------------------------------------------------

warehouse["product_avg_review"] = (
    warehouse["product_avg_review"]
    .fillna(0)
)

# ------------------------------------------------------------
# 2. Customer Segment
# ------------------------------------------------------------

warehouse["customer_segment"] = pd.cut(

    warehouse["customer_lifetime_value"],

    bins=[0,100,500,2000,np.inf],

    labels=[

        "Bronze",

        "Silver",

        "Gold",

        "Platinum"

    ],

    include_lowest=True

)

# ------------------------------------------------------------
# 3. Product Revenue Rank
# ------------------------------------------------------------

warehouse["product_revenue_rank"] = (

    warehouse["product_total_revenue"]

    .rank(

        ascending=False,

        method="dense"

    )

)

# ------------------------------------------------------------
# 4. Basket Size
# ------------------------------------------------------------

basket_size = (

    warehouse

    .groupby("order_id")

    ["order_item_id"]

    .count()

)

warehouse["basket_size"] = (

    warehouse["order_id"]

    .map(basket_size)

)

# ------------------------------------------------------------
# 5. Basket Value
# ------------------------------------------------------------

basket_value = (

    warehouse

    .groupby("order_id")

    ["total_payment"]

    .first()

)

warehouse["basket_value"] = (

    warehouse["order_id"]

    .map(basket_value)

)

# ------------------------------------------------------------
# 6. Average Delivery Time Per Seller
# ------------------------------------------------------------

warehouse["seller_avg_delivery_days"] = (

    warehouse

    .groupby("seller_id")

    ["delivery_days"]

    .transform("mean")

)

# ------------------------------------------------------------
# 7. Seller Performance
# ------------------------------------------------------------

warehouse["seller_performance"] = pd.cut(

    warehouse["seller_avg_review"],

    bins=[0,3,4,4.5,5],

    labels=[

        "Poor",

        "Average",

        "Good",

        "Excellent"

    ],

    include_lowest=True

)

# ------------------------------------------------------------
# 8. Order Size
# ------------------------------------------------------------

warehouse["order_size"] = pd.cut(

    warehouse["basket_size"],

    bins=[0,1,3,5,100],

    labels=[

        "Single Item",

        "Small Basket",

        "Medium Basket",

        "Large Basket"

    ],

    include_lowest=True

)

# ------------------------------------------------------------
# 9. Revenue Percentile
# ------------------------------------------------------------

warehouse["revenue_percentile"] = (

    warehouse["total_payment"]

    .rank(pct=True)

)

# ------------------------------------------------------------
# 10. Top 10% Customer
# ------------------------------------------------------------

warehouse["top_customer"] = (

    warehouse["customer_lifetime_value"]

    >=

    warehouse["customer_lifetime_value"]

    .quantile(0.90)

)

# ------------------------------------------------------------
# 11. Top 10% Seller
# ------------------------------------------------------------

warehouse["top_seller"] = (

    warehouse["seller_revenue"]

    >=

    warehouse["seller_revenue"]

    .quantile(0.90)

)

# ------------------------------------------------------------
# 12. Top 10% Product
# ------------------------------------------------------------

warehouse["top_product"] = (

    warehouse["product_total_revenue"]

    >=

    warehouse["product_total_revenue"]

    .quantile(0.90)

)

# ------------------------------------------------------------
# 13. Revenue Class
# ------------------------------------------------------------

warehouse["revenue_class"] = pd.cut(

    warehouse["total_payment"],

    bins=[0,100,300,600,1000,np.inf],

    labels=[

        "Very Low",

        "Low",

        "Medium",

        "High",

        "Premium"

    ],

    include_lowest=True

)

# ------------------------------------------------------------
# FINAL SUMMARY
# ------------------------------------------------------------

print("\nFinal Warehouse Shape:", warehouse.shape)

print("\nTotal Features:", warehouse.shape[1])

print("\nNewest Features Added:")

new_features = [

    "customer_segment",

    "product_revenue_rank",

    "basket_size",

    "basket_value",

    "seller_avg_delivery_days",

    "seller_performance",

    "order_size",

    "revenue_percentile",

    "top_customer",

    "top_seller",

    "top_product",

    "revenue_class"

]

print(new_features)

print("\nFinal Feature Engineering Completed Successfully!")

# ============================================================
# TIME FEATURES
# ============================================================

warehouse["purchase_week"] = (
    warehouse["order_purchase_timestamp"]
    .dt.isocalendar()
    .week
)

warehouse["purchase_day_number"] = (
    warehouse["order_purchase_timestamp"]
    .dt.day
)

warehouse["purchase_weekend"] = (
    warehouse["order_purchase_timestamp"]
    .dt.dayofweek >= 5
)

warehouse["purchase_season"] = np.select(

    [

        warehouse["purchase_month"].isin(
            ["December","January","February"]
        ),

        warehouse["purchase_month"].isin(
            ["March","April","May"]
        ),

        warehouse["purchase_month"].isin(
            ["June","July","August"]
        ),

        warehouse["purchase_month"].isin(
            ["September","October","November"]
        )

    ],

    [

        "Summer",

        "Autumn",

        "Winter",

        "Spring"

    ],

    default="Unknown"

)

print("="*80)
print("FINAL WAREHOUSE")
print("="*80)

print("Rows :", warehouse.shape[0])

print("Columns :", warehouse.shape[1])

print("\nRemaining Missing Values")

display(

    warehouse.isnull()

    .sum()

    .sort_values(ascending=False)

    .head(20)

)

display(warehouse.head())

warehouse.to_parquet(
    "/content/drive/MyDrive/InsightFlow_AI/data/warehouse/final_analytics_warehouse.parquet",
    index=False
)

warehouse.to_csv(
    "/content/drive/MyDrive/InsightFlow_AI/data/warehouse/final_analytics_warehouse.csv",
    index=False
)

print("Final Warehouse Saved Successfully!")

================================================================================
ADDING FINAL BUSINESS FEATURES
================================================================================

Final Warehouse Shape: (113425, 93)

Total Features: 93

Newest Features Added:
['customer_segment', 'product_revenue_rank', 'basket_size', 'basket_value', 'seller_avg_delivery_days', 'seller_performance', 'order_size', 'revenue_percentile', 'top_customer', 'top_seller', 'top_product', 'revenue_class']

Final Feature Engineering Completed Successfully!
================================================================================
FINAL WAREHOUSE
================================================================================
Rows : 113425
Columns : 97

Remaining Missing Values

review_comment_title             99918
review_comment_message           65430
shipping_days                     3534
delivery_days                     3230
delivery_delay_days               3230
late_delivery_days                3230
order_delivered_customer_date     3229
product_description_lenght        2378
product_photos_qty                2378
product_name_lenght               2378
order_delivered_carrier_date      1968
seller_avg_delivery_days           981
review_creation_date               961
review_id                          961
review_answer_timestamp            961
review_score                       961
price_per_gram                     801
product_width_cm                   793
product_weight_g                   793
product_length_cm                  793
dtype: int64

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category,seller_zip_code_prefix,seller_city,seller_state,total_payment,payment_type,payment_installments,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,approval_hours,shipping_days,delivery_days,estimated_delivery_days,purchase_year,purchase_month,purchase_month_num,purchase_day,purchase_hour,purchase_quarter,review_category,product_volume_cm3,total_product_cost,local_order,price_per_gram,delivery_completed,product_density,customer_order_number,repeat_customer,customer_total_orders,customer_lifetime_value,customer_avg_order_value,customer_first_purchase,customer_last_purchase,customer_tenure_days,new_customer,product_sales_count,product_total_revenue,product_avg_review,product_avg_price,product_popularity_rank,seller_total_orders,seller_revenue,seller_avg_review,seller_rank,delivery_delay_days,early_delivery,on_time_delivery,late_delivery_days,freight_percentage,profit_proxy,high_margin,premium_order,customer_segment,product_revenue_rank,basket_size,basket_value,seller_avg_delivery_days,seller_performance,order_size,revenue_percentile,top_customer,top_seller,top_product,revenue_class,purchase_week,purchase_day_number,purchase_weekend,purchase_season
60152,e22acc9c116caa3f2b7121bbb380d08e,fadbb3709178fc513abc1b2670aa1ad2,delivered,2018-05-10 10:56:27,2018-05-10 11:11:18,2018-05-12 08:18:00,2018-05-16 20:48:37,2018-05-21,0000366f3b9a7992bf8c76cfdf3221e2,7787,cajamar,SP,1.0,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,2018-05-15 11:11:18,129.90,12.00,60.0,236.0,1.0,1500.0,34.0,7.0,32.0,bed_bath_table,13405.0,piracicaba,SP,141.90,credit_card,8.0,13359f48c3c7e41a2b8afca340937eeb,5.0,Super Recomendo,"Adorei a cortina, ficou linda na minha sala, e...",2018-05-17,2018-05-21 13:44:48,0.247500,1.0,4.0,10,2018,May,5,Thursday,10,2,Excellent,7616.0,141.90,True,0.086600,True,0.196954,1,False,1,141.90,141.90,2018-05-10 10:56:27,2018-05-10 10:56:27,0,True,29.0,6667.20,4.206897,109.382759,110.0,1551.0,272219.32,4.063754,6.0,-6.0,True,True,0.0,8.456660,117.90,True,False,Silver,352.0,1,141.90,7.921835,Good,Single Item,0.605632,False,True,False,Low,19,10,False,Autumn
84207,3594e05a005ac4d06a72673270ef9ec9,4cb282e167ae9234755102258dd52ee8,delivered,2018-05-07 11:11:27,2018-05-07 18:25:44,2018-05-09 12:18:00,2018-05-10 18:02:42,2018-05-15,0000b849f77a49e4a4ce2b2a4ca5be3f,6053,osasco,SP,1.0,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,2018-05-11 17:56:33,18.90,8.29,56.0,635.0,1.0,375.0,26.0,11.0,18.0,health_beauty,2215.0,sao paulo,SP,27.19,credit_card,1.0,e383e10e36a765f04f752a37c1674e43,4.0,None,None,2018-05-11,2018-05-11 22:29:25,7.238056,1.0,1.0,7,2018,May,5,Monday,11,2,Good,5148.0,27.19,True,0.050400,True,0.072844,1,False,1,27.19,27.19,2018-05-07 11:11:27,2018-05-07 11:11:27,0,True,7.0,195.84,4.714286,19.042857,132.0,58.0,2804.17,3.982759,1066.0,-6.0,True,True,0.0,30.489150,10.61,False,False,Bronze,14895.0,1,27.19,4.034483,Average,Single Item,0.020150,False,False,False,Very Low,19,7,False,Autumn
30148,b33ec3b699337181488304f362a6b734,9b3932a6253894a02c1df9d19004239f,delivered,2017-03-10 21:05:03,2017-03-10 21:05:03,2017-03-13 12:58:30,2017-04-05 14:38:47,2017-04-07,0000f46a3911fa3c0805444483337064,88115,sao jose,SC,1.0,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,2017-03-15 21:05:03,69.00,17.22,49.0,177.0,3.0,1500.0,25.0,50.0,35.0,stationery,13232.0,campo limpo paulista,SP,86.22,credit_card,8.0,d89cb4217c23008b141e66c3160de8a4,3.0,None,None,2017-04-06,2017-04-07 01:19:44,0.000000,2.0,23.0,27,2017,March,3,Friday,21,1,Average,43750.0,86.22,False,0.046000,True,0.034286,1,False,1,86.22,86.22,2017-03-10 21:05:03,2017-03-10 21:05:03,0,True,5.0,440.59,4.600000,73.000000,134.0,1147.0,131982.15,4.113656,20.0,-4.0,True,True,0.0,19.972164,51.78,False,False,Bronze,8553.0,1,86.22,9.628647,Good,Single Item,0.368390,False,False,False,Very Low,10,10,False,Autumn
112316,41272756ecddd9a9ed0180413cc22fb6,914991f0c02ef0843c0e7010c819d642,delivered,2017-10-12 20:29:41,2017-10-12 20:49:17,2017-10-13 20:08:19,2017-11-01 21:23:05,2017-11-13,0000f6ccb0745a6a4b88665a16c9f078,66812,belem,PA,1.0,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,2017-10-18 21:49:17,25.99,17.63,43.0,1741.0,5.0,150.0,19.0,5.0,11.0,telephony,3569.0,sao paulo,SP,43.62,credit_card,4.0,6f22e4ad2cd9e0d40c5842e4787b4321,4.0,None,Bom vendedor,2017-11-02,2017-11-03 00:17:51,0.326667,0.0,19.0,31,2017,October,10,Thursday,20,4,Good,1045.0,43.62,False,0.173267,True,0.143541,1,False,1,43.62,43.62,2017-10-12 20:29:41,2017-10-12 20:29:41,0,True,3.0,123.49,4.666667,27.990000,136.0,340.0,16770.94,3.901786,257.0,-12.0,True,True,0.0,40.417240,8.36,False,False,Bronze,18403.0,1,43.62,9.361446,Average,Single Item,0.111764,False,False,False,Very Low,41,12,False,Spring
47364,d957021f1127559cd947b62533f484f7,47227568b10f5f58a524a75507e6992c,delivered,2017-11-14 19:45:42,2017-11-14 20:06:52,2017-11-16 19:52:10,2017-11-27 23:08:56,2017-12-05,0004aac84e0df4da2b147fca70cf8255,18040,sorocaba,SP,1.0,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,2017-11-22 20:06:52,180.00,16.89,58.0,794.0,3.0,6050.0,16.0,3.0,11.0,telephony,12327.0,jacarei,SP,196.89,credit_card,6.0,880a77e7dd4e496969f138f974cc44a1,5.0,None,None,2017-11-28,2017-12-02 22:29:35,0.352778,1.0,11.0,20,2017,November,11,Tuesday,19,4,Excellent,528.0,196.89,True,0.029752,True,11.458333,1,False,1,196.89,196.89,2017-11-14 19:45:42,2017-11-14 19:45:42,0,True,1.0,196.89,5.000000,180.000000,138.0,328.0,40310.83,3.769939,94.0,-9.0,True,True,0.0,8.578394,163.11,True,False,Silver,14861.0,1,196.89,10.136223,Average,Single Item,0.753403,False,False,False,Low,46,14,False,Spring

Final Warehouse Saved Successfully!

Star Schema

Enterprise FACT_SALES

In [ ]:
# ============================================================
# ENTERPRISE ANALYTICS WAREHOUSE
# CONFIGURATION
# ============================================================

import os
import json
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",100)

print("Libraries Loaded Successfully")

# ============================================================
# PROJECT PATHS
# ============================================================

BASE = "/content/drive/MyDrive/InsightFlow_AI"

WAREHOUSE = os.path.join(BASE,"data","warehouse")

DIMENSIONS = os.path.join(WAREHOUSE,"dimensions")

FACTS = os.path.join(WAREHOUSE,"facts")

METADATA = os.path.join(WAREHOUSE,"metadata")

REPORTS = os.path.join(BASE,"reports")

for folder in [

    DIMENSIONS,

    FACTS,

    METADATA,

    REPORTS

]:

    os.makedirs(folder,exist_ok=True)

print("Folders Created Successfully")

# ============================================================
# LOAD FINAL WAREHOUSE
# ============================================================

warehouse = pd.read_parquet(

    BASE+

    "/data/warehouse/final_analytics_warehouse.parquet"

)

print("Warehouse Loaded")

print(warehouse.shape)

print("="*80)

print("WAREHOUSE SUMMARY")

print("="*80)

print("Rows :",warehouse.shape[0])

print("Columns :",warehouse.shape[1])

print()

print("Memory Usage")

print(

warehouse.memory_usage(

deep=True

).sum()/1024**2,

"MB"

)

print()

display(

warehouse.head()

)

schema = pd.DataFrame({

"Column":warehouse.columns,

"Datatype":warehouse.dtypes.astype(str),

"Missing":

warehouse.isnull().sum(),

"Unique":

warehouse.nunique()

})

display(schema)

schema.to_csv(

METADATA+

"/warehouse_schema.csv",

index=False

)

print("Schema Saved")

dictionary = pd.DataFrame({

"Column":warehouse.columns,

"Business_Name":"",

"Description":"",

"Datatype":

warehouse.dtypes.astype(str),

"Source_Table":"",

"Business_Rule":"",

"Nullable":"",

"Primary_Key":"",

"Foreign_Key":""

})

dictionary.to_csv(

METADATA+

"/data_dictionary.csv",

index=False

)

print("Business Dictionary Template Created")

pipeline = {

"Project":"InsightFlow AI",

"Version":"1.0",

"Warehouse Rows":

int(

warehouse.shape[0]

),

"Warehouse Columns":

int(

warehouse.shape[1]

),

"Created_By":"Nitisha Mishra",

"Pipeline":"Enterprise Analytics Warehouse"

}

with open(

METADATA+

"/pipeline.json",

"w"

) as f:

    json.dump(

        pipeline,

        f,

        indent=4

    )

print("Pipeline Metadata Saved")

# ============================================================
# BUILD DIMENSION HELPER
# ============================================================

def build_dimension(
    df,
    business_key,
    surrogate_key_name,
    columns,
    sort_by=None
):
    """
    Generic dimension builder.
    Creates one row per business key and assigns
    a deterministic surrogate key.
    """

    # Keep only columns that actually exist
    available_columns = [
        col for col in columns
        if col in df.columns
    ]

    dimension = df[available_columns].copy()

    # Remove missing business keys
    dimension = dimension[
        dimension[business_key].notna()
    ].copy()

    # Remove duplicate business keys
    dimension = (
        dimension
        .sort_values(
            sort_by if sort_by else business_key
        )
        .drop_duplicates(
            subset=[business_key],
            keep="first"
        )
        .reset_index(drop=True)
    )

    # Remove old surrogate key if present
    if surrogate_key_name in dimension.columns:
        dimension.drop(
            columns=[surrogate_key_name],
            inplace=True
        )

    # Create surrogate key
    dimension.insert(
        0,
        surrogate_key_name,
        range(
            1,
            len(dimension) + 1
        )
    )

    return dimension


print("✓ build_dimension() defined successfully")


 # ============================================================
# DIM_CUSTOMERS (FIXED)
# ============================================================

customer_columns = [

    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state",
    "customer_zip_code_prefix",
    "customer_segment",
    "customer_total_orders",
    "customer_lifetime_value",
    "customer_avg_order_value",
    "customer_tenure_days",
    "repeat_customer"

]

dim_customers = (

    warehouse[customer_columns]

    .sort_values("customer_id")

    .drop_duplicates(
        subset=["customer_id"],
        keep="last"
    )

    .reset_index(drop=True)

)

dim_customers.insert(

    0,

    "customer_key",

    range(1, len(dim_customers)+1)

)

print("="*70)
print("DIM_CUSTOMERS")
print("="*70)
print("Rows :", len(dim_customers))
print("Columns :", len(dim_customers.columns))
print("Duplicate Customer IDs :", dim_customers["customer_id"].duplicated().sum())

display(dim_customers.head())

# ============================================================
# DIM_PRODUCTS
# ============================================================

dim_products = build_dimension(

    warehouse,

    business_key="product_id",

    surrogate_key_name="product_key",

    columns=[

        "product_id",

        "product_category",

        "product_weight_g",

        "product_length_cm",

        "product_width_cm",

        "product_height_cm",

        "product_volume_cm3",

        "product_sales_count",

        "product_total_revenue",

        "product_avg_review",

        "product_avg_price",

        "product_popularity_rank",

        "product_revenue_rank"

    ]

)

display(dim_products.head())

# ============================================================
# DIM_SELLERS
# ============================================================

dim_sellers = build_dimension(

    warehouse,

    business_key="seller_id",

    surrogate_key_name="seller_key",

    columns=[

        "seller_id",

        "seller_city",

        "seller_state",

        "seller_total_orders",

        "seller_revenue",

        "seller_avg_review",

        "seller_avg_delivery_days",

        "seller_rank",

        "seller_performance"

    ]

)

display(dim_sellers.head())

# ============================================================
# DIM_PAYMENTS
# ============================================================

# ============================================================
# DIM_PAYMENTS (FIXED)
# ============================================================

payment_summary = (

    warehouse

    .groupby("order_id")

    .agg(

        payment_type=("payment_type", "first"),

        payment_installments=("payment_installments", "max"),

        total_payment=("total_payment", "sum")

    )

    .reset_index()

)

payment_summary["payment_count"] = (

    warehouse

    .groupby("order_id")

    .size()

    .values

)

payment_summary.rename(

    columns={

        "payment_type":"payment_methods"

    },

    inplace=True

)

payment_summary.insert(

    0,

    "payment_key",

    range(1,len(payment_summary)+1)

)

dim_payments = payment_summary

print("="*70)
print("DIM_PAYMENTS")
print("="*70)

print("Rows :",len(dim_payments))
print("Columns :",len(dim_payments.columns))

display(dim_payments.head())

# ============================================================
# DIM_REVIEWS
# ============================================================

# ============================================================
# DIM_REVIEWS (FIXED)
# ============================================================

dim_reviews = (

    warehouse[[
        "order_id",
        "review_score",
        "review_category"
    ]]

    .drop_duplicates(subset=["order_id"])

    .reset_index(drop=True)

)

# Create review availability
dim_reviews["review_available"] = (
    dim_reviews["review_score"].notna()
)

# Create review label from score
dim_reviews["review_label"] = np.select(

    [

        dim_reviews["review_score"] >= 4,

        dim_reviews["review_score"] == 3,

        dim_reviews["review_score"] <= 2,

        dim_reviews["review_score"].isna()

    ],

    [

        "Positive",

        "Neutral",

        "Negative",

        "No Review"

    ],

    default="Unknown"

)

# Create surrogate key
dim_reviews.insert(

    0,

    "review_key",

    range(1, len(dim_reviews)+1)

)

print("="*70)
print("DIM_REVIEWS")
print("="*70)

print("Rows :", len(dim_reviews))
print("Columns :", len(dim_reviews.columns))
print("Duplicate Orders :", dim_reviews["order_id"].duplicated().sum())

display(dim_reviews.head())

# ============================================================
# DIM_LOCATION
# ============================================================

dim_locations = warehouse[[

    "customer_city",

    "customer_state",

    "seller_city",

    "seller_state",

    "local_order"

]].drop_duplicates()

dim_locations = dim_locations.sort_values([

    "customer_state",

    "customer_city",

    "seller_state",

    "seller_city"

]).reset_index(drop=True)

dim_locations.insert(

    0,

    "location_key",

    range(1, len(dim_locations)+1)

)

display(dim_locations.head())

# ============================================================
# DIM_ORDER_STATUS (FIXED)
# ============================================================

dim_status = (

    warehouse[[

        "order_status"

    ]]

    .drop_duplicates()

    .sort_values("order_status")

    .reset_index(drop=True)

)

dim_status.insert(

    0,

    "status_key",

    range(1, len(dim_status)+1)

)

print("="*70)
print("DIM_STATUS")
print("="*70)
print("Rows :", len(dim_status))
print("Unique Status :", dim_status["order_status"].nunique())

display(dim_status)

# ================================
# FIX PRODUCT DIMENSION
# ================================

# Remove rows with missing Product IDs
dim_products = dim_products.dropna(subset=["product_id"])

# Remove duplicate Product IDs
dim_products = (
    dim_products
    .sort_values("product_id")
    .drop_duplicates(subset=["product_id"], keep="first")
    .reset_index(drop=True)
)

# Remove old surrogate key if it already exists
if "product_key" in dim_products.columns:
    dim_products.drop(columns=["product_key"], inplace=True)

# Create new surrogate key
dim_products.insert(
    0,
    "product_key",
    range(1, len(dim_products)+1)
)

print("="*60)
print("PRODUCT DIMENSION")
print("="*60)
print("Rows :", len(dim_products))
print("Duplicate Product IDs :", dim_products["product_id"].duplicated().sum())
print("Missing Product IDs :", dim_products["product_id"].isna().sum())

# ================================
# FIX SELLER DIMENSION
# ================================

dim_sellers = dim_sellers.dropna(subset=["seller_id"])

dim_sellers = (
    dim_sellers
    .sort_values("seller_id")
    .drop_duplicates(subset=["seller_id"], keep="first")
    .reset_index(drop=True)
)

if "seller_key" in dim_sellers.columns:
    dim_sellers.drop(columns=["seller_key"], inplace=True)

dim_sellers.insert(
    0,
    "seller_key",
    range(1, len(dim_sellers)+1)
)

print("="*60)
print("SELLER DIMENSION")
print("="*60)
print("Rows :", len(dim_sellers))
print("Duplicate Seller IDs :", dim_sellers["seller_id"].duplicated().sum())
print("Missing Seller IDs :", dim_sellers["seller_id"].isna().sum())

# ============================================================
# DIM_DATE (FIXED)
# ============================================================

date_dimension = pd.DataFrame({

    "date": pd.date_range(

        warehouse["order_purchase_timestamp"].min().normalize(),

        warehouse["order_purchase_timestamp"].max().normalize(),

        freq="D"

    )

})

date_dimension["purchase_year"] = date_dimension["date"].dt.year

date_dimension["purchase_quarter"] = date_dimension["date"].dt.quarter

date_dimension["purchase_month"] = date_dimension["date"].dt.month_name()

date_dimension["purchase_week"] = (
    date_dimension["date"]
    .dt.isocalendar()
    .week
    .astype(int)
)

date_dimension["purchase_day"] = date_dimension["date"].dt.day_name()

date_dimension["purchase_day_number"] = date_dimension["date"].dt.day

date_dimension["purchase_weekend"] = (
    date_dimension["date"].dt.dayofweek >= 5
)

date_dimension["purchase_season"] = np.select(

    [

        date_dimension["date"].dt.month.isin([12,1,2]),

        date_dimension["date"].dt.month.isin([3,4,5]),

        date_dimension["date"].dt.month.isin([6,7,8]),

        date_dimension["date"].dt.month.isin([9,10,11])

    ],

    [

        "Summer",

        "Autumn",

        "Winter",

        "Spring"

    ],

    default="Unknown"

)

dim_date = date_dimension.copy()

dim_date.insert(

    0,

    "date_key",

    range(1, len(dim_date)+1)

)

print("="*70)
print("DIM_DATE")
print("="*70)
print("Rows :", len(dim_date))
print("Columns :", len(dim_date.columns))

display(dim_date.head())

# ============================================================
# SAVE DIMENSIONS
# ============================================================

dimension_tables = {

    "dim_customers": dim_customers,

    "dim_products": dim_products,

    "dim_sellers": dim_sellers,

    "dim_payments": dim_payments,

    "dim_reviews": dim_reviews,

    "dim_locations": dim_locations,

    "dim_status": dim_status,

    "dim_date": dim_date

}

for name, table in dimension_tables.items():

    table.to_parquet(
        os.path.join(DIMENSIONS, f"{name}.parquet"),
        index=False
    )

    table.to_csv(
        os.path.join(DIMENSIONS, f"{name}.csv"),
        index=False
    )

print("="*80)
print("ALL DIMENSION TABLES CREATED")
print("="*80)

for name, table in dimension_tables.items():
    print(f"{name:<20} {table.shape}")

Libraries Loaded Successfully
Folders Created Successfully
Warehouse Loaded
(113425, 97)
================================================================================
WAREHOUSE SUMMARY
================================================================================
Rows : 113425
Columns : 97

Memory Usage
177.11752796173096 MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category,seller_zip_code_prefix,seller_city,seller_state,total_payment,payment_type,payment_installments,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,approval_hours,shipping_days,delivery_days,estimated_delivery_days,purchase_year,purchase_month,purchase_month_num,purchase_day,purchase_hour,purchase_quarter,review_category,product_volume_cm3,total_product_cost,local_order,price_per_gram,delivery_completed,product_density,customer_order_number,repeat_customer,customer_total_orders,customer_lifetime_value,customer_avg_order_value,customer_first_purchase,customer_last_purchase,customer_tenure_days,new_customer,product_sales_count,product_total_revenue,product_avg_review,product_avg_price,product_popularity_rank,seller_total_orders,seller_revenue,seller_avg_review,seller_rank,delivery_delay_days,early_delivery,on_time_delivery,late_delivery_days,freight_percentage,profit_proxy,high_margin,premium_order,customer_segment,product_revenue_rank,basket_size,basket_value,seller_avg_delivery_days,seller_performance,order_size,revenue_percentile,top_customer,top_seller,top_product,revenue_class,purchase_week,purchase_day_number,purchase_weekend,purchase_season
0,e22acc9c116caa3f2b7121bbb380d08e,fadbb3709178fc513abc1b2670aa1ad2,delivered,2018-05-10 10:56:27,2018-05-10 11:11:18,2018-05-12 08:18:00,2018-05-16 20:48:37,2018-05-21,0000366f3b9a7992bf8c76cfdf3221e2,7787,cajamar,SP,1.0,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,2018-05-15 11:11:18,129.90,12.00,60.0,236.0,1.0,1500.0,34.0,7.0,32.0,bed_bath_table,13405.0,piracicaba,SP,141.90,credit_card,8.0,13359f48c3c7e41a2b8afca340937eeb,5.0,Super Recomendo,"Adorei a cortina, ficou linda na minha sala, e...",2018-05-17,2018-05-21 13:44:48,0.247500,1.0,4.0,10,2018,May,5,Thursday,10,2,Excellent,7616.0,141.90,True,0.086600,True,0.196954,1,False,1,141.90,141.90,2018-05-10 10:56:27,2018-05-10 10:56:27,0,True,29.0,6667.20,4.206897,109.382759,110.0,1551.0,272219.32,4.063754,6.0,-6.0,True,True,0.0,8.456660,117.90,True,False,Silver,352.0,1,141.90,7.921835,Good,Single Item,0.605632,False,True,False,Low,19,10,False,Autumn
1,3594e05a005ac4d06a72673270ef9ec9,4cb282e167ae9234755102258dd52ee8,delivered,2018-05-07 11:11:27,2018-05-07 18:25:44,2018-05-09 12:18:00,2018-05-10 18:02:42,2018-05-15,0000b849f77a49e4a4ce2b2a4ca5be3f,6053,osasco,SP,1.0,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,2018-05-11 17:56:33,18.90,8.29,56.0,635.0,1.0,375.0,26.0,11.0,18.0,health_beauty,2215.0,sao paulo,SP,27.19,credit_card,1.0,e383e10e36a765f04f752a37c1674e43,4.0,None,None,2018-05-11,2018-05-11 22:29:25,7.238056,1.0,1.0,7,2018,May,5,Monday,11,2,Good,5148.0,27.19,True,0.050400,True,0.072844,1,False,1,27.19,27.19,2018-05-07 11:11:27,2018-05-07 11:11:27,0,True,7.0,195.84,4.714286,19.042857,132.0,58.0,2804.17,3.982759,1066.0,-6.0,True,True,0.0,30.489150,10.61,False,False,Bronze,14895.0,1,27.19,4.034483,Average,Single Item,0.020150,False,False,False,Very Low,19,7,False,Autumn
2,b33ec3b699337181488304f362a6b734,9b3932a6253894a02c1df9d19004239f,delivered,2017-03-10 21:05:03,2017-03-10 21:05:03,2017-03-13 12:58:30,2017-04-05 14:38:47,2017-04-07,0000f46a3911fa3c0805444483337064,88115,sao jose,SC,1.0,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,2017-03-15 21:05:03,69.00,17.22,49.0,177.0,3.0,1500.0,25.0,50.0,35.0,stationery,13232.0,campo limpo paulista,SP,86.22,credit_card,8.0,d89cb4217c23008b141e66c3160de8a4,3.0,None,None,2017-04-06,2017-04-07 01:19:44,0.000000,2.0,23.0,27,2017,March,3,Friday,21,1,Average,43750.0,86.22,False,0.046000,True,0.034286,1,False,1,86.22,86.22,2017-03-10 21:05:03,2017-03-10 21:05:03,0,True,5.0,440.59,4.600000,73.000000,134.0,1147.0,131982.15,4.113656,20.0,-4.0,True,True,0.0,19.972164,51.78,False,False,Bronze,8553.0,1,86.22,9.628647,Good,Single Item,0.368390,False,False,False,Very Low,10,10,False,Autumn
3,41272756ecddd9a9ed0180413cc22fb6,914991f0c02ef0843c0e7010c819d642,delivered,2017-10-12 20:29:41,2017-10-12 20:49:17,2017-10-13 20:08:19,2017-11-01 21:23:05,2017-11-13,0000f6ccb0745a6a4b88665a16c9f078,66812,belem,PA,1.0,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,2017-10-18 21:49:17,25.99,17.63,43.0,1741.0,5.0,150.0,19.0,5.0,11.0,telephony,3569.0,sao paulo,SP,43.62,credit_card,4.0,6f22e4ad2cd9e0d40c5842e4787b4321,4.0,None,Bom vendedor,2017-11-02,2017-11-03 00:17:51,0.326667,0.0,19.0,31,2017,October,10,Thursday,20,4,Good,1045.0,43.62,False,0.173267,True,0.143541,1,False,1,43.62,43.62,2017-10-12 20:29:41,2017-10-12 20:29:41,0,True,3.0,123.49,4.666667,27.990000,136.0,340.0,16770.94,3.901786,257.0,-12.0,True,True,0.0,40.417240,8.36,False,False,Bronze,18403.0,1,43.62,9.361446,Average,Single Item,0.111764,False,False,False,Very Low,41,12,False,Spring
4,d957021f1127559cd947b62533f484f7,47227568b10f5f58a524a75507e6992c,delivered,2017-11-14 19:45:42,2017-11-14 20:06:52,2017-11-16 19:52:10,2017-11-27 23:08:56,2017-12-05,0004aac84e0df4da2b147fca70cf8255,18040,sorocaba,SP,1.0,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,2017-11-22 20:06:52,180.00,16.89,58.0,794.0,3.0,6050.0,16.0,3.0,11.0,telephony,12327.0,jacarei,SP,196.89,credit_card,6.0,880a77e7dd4e496969f138f974cc44a1,5.0,None,None,2017-11-28,2017-12-02 22:29:35,0.352778,1.0,11.0,20,2017,November,11,Tuesday,19,4,Excellent,528.0,196.89,True,0.029752,True,11.458333,1,False,1,196.89,196.89,2017-11-14 19:45:42,2017-11-14 19:45:42,0,True,1.0,196.89,5.000000,180.000000,138.0,328.0,40310.83,3.769939,94.0,-9.0,True,True,0.0,8.578394,163.11,True,False,Silver,14861.0,1,196.89,10.136223,Average,Single Item,0.753403,False,False,False,Low,46,14,False,Spring

,Column,Datatype,Missing,Unique
order_id,order_id,object,0,99441
customer_id,customer_id,object,0,99441
order_status,order_status,object,0,8
order_purchase_timestamp,order_purchase_timestamp,datetime64[ns],0,98875
order_approved_at,order_approved_at,datetime64[ns],161,90733
order_delivered_carrier_date,order_delivered_carrier_date,datetime64[ns],1968,81018
order_delivered_customer_date,order_delivered_customer_date,datetime64[ns],3229,95664
order_estimated_delivery_date,order_estimated_delivery_date,datetime64[ns],0,459
customer_unique_id,customer_unique_id,object,0,96096
customer_zip_code_prefix,customer_zip_code_prefix,int64,0,14994
customer_city,customer_city,object,0,4119
customer_state,customer_state,object,0,27
order_item_id,order_item_id,float64,775,21
product_id,product_id,object,775,32951
seller_id,seller_id,object,775,3095
shipping_limit_date,shipping_limit_date,datetime64[ns],775,93318
price,price,float64,775,5968
freight_value,freight_value,float64,775,6999
product_name_lenght,product_name_lenght,float64,2378,66
product_description_lenght,product_description_lenght,float64,2378,2960
product_photos_qty,product_photos_qty,float64,2378,19
product_weight_g,product_weight_g,float64,793,2204
product_length_cm,product_length_cm,float64,793,99
product_height_cm,product_height_cm,float64,793,102
product_width_cm,product_width_cm,float64,793,95
product_category,product_category,object,0,72
seller_zip_code_prefix,seller_zip_code_prefix,float64,775,2246
seller_city,seller_city,object,775,611
seller_state,seller_state,object,775,23
total_payment,total_payment,float64,3,27979
payment_type,payment_type,object,3,7
payment_installments,payment_installments,float64,3,24
review_id,review_id,object,961,98156
review_score,review_score,float64,961,11
review_comment_title,review_comment_title,object,99918,4525
review_comment_message,review_comment_message,object,65430,36106
review_creation_date,review_creation_date,datetime64[ns],961,636
review_answer_timestamp,review_answer_timestamp,datetime64[ns],961,97994
approval_hours,approval_hours,float64,161,33475
shipping_days,shipping_days,float64,3534,59
delivery_days,delivery_days,float64,3230,145
estimated_delivery_days,estimated_delivery_days,int64,0,104
purchase_year,purchase_year,int32,0,3
purchase_month,purchase_month,object,0,12
purchase_month_num,purchase_month_num,int32,0,12
purchase_day,purchase_day,object,0,7
purchase_hour,purchase_hour,int32,0,24
purchase_quarter,purchase_quarter,int32,0,4
review_category,review_category,category,0,5
product_volume_cm3,product_volume_cm3,float64,793,4525
total_product_cost,total_product_cost,float64,775,29149
local_order,local_order,bool,0,2
price_per_gram,price_per_gram,float64,801,24560
delivery_completed,delivery_completed,bool,0,2
product_density,product_density,float64,793,13659
customer_order_number,customer_order_number,int64,0,24
repeat_customer,repeat_customer,bool,0,2
customer_total_orders,customer_total_orders,int64,0,9
customer_lifetime_value,customer_lifetime_value,float64,0,31027
customer_avg_order_value,customer_avg_order_value,float64,3,29207
customer_first_purchase,customer_first_purchase,datetime64[ns],0,95837
customer_last_purchase,customer_last_purchase,datetime64[ns],0,95834
customer_tenure_days,customer_tenure_days,int64,0,422
new_customer,new_customer,bool,0,2
product_sales_count,product_sales_count,float64,775,138
product_total_revenue,product_total_revenue,float64,775,24294
product_avg_review,product_avg_review,float64,0,653
product_avg_price,product_avg_price,float64,775,8829
product_popularity_rank,product_popularity_rank,float64,775,138
seller_total_orders,seller_total_orders,float64,775,257
seller_revenue,seller_revenue,float64,775,3082
seller_avg_review,seller_avg_review,float64,780,832
seller_rank,seller_rank,float64,775,3082
delivery_delay_days,delivery_delay_days,float64,3230,201
early_delivery,early_delivery,bool,0,2
on_time_delivery,on_time_delivery,bool,0,2
late_delivery_days,late_delivery_days,float64,3230,111
freight_percentage,freight_percentage,float64,775,46684
profit_proxy,profit_proxy,float64,775,31125
high_margin,high_margin,bool,0,2
premium_order,premium_order,bool,0,2
customer_segment,customer_segment,category,0,4
product_revenue_rank,product_revenue_rank,float64,775,24294
basket_size,basket_size,int64,0,18
basket_value,basket_value,float64,3,27979
seller_avg_delivery_days,seller_avg_delivery_days,float64,981,1323
seller_performance,seller_performance,category,780,4
order_size,order_size,category,0,4
revenue_percentile,revenue_percentile,float64,3,27979
top_customer,top_customer,bool,0,2
top_seller,top_seller,bool,0,2
top_product,top_product,bool,0,2
revenue_class,revenue_class,category,3,5
purchase_week,purchase_week,UInt32,0,52
purchase_day_number,purchase_day_number,int32,0,31
purchase_weekend,purchase_weekend,bool,0,2
purchase_season,purchase_season,object,0,4

Schema Saved
Business Dictionary Template Created
Pipeline Metadata Saved
✓ build_dimension() defined successfully
======================================================================
DIM_CUSTOMERS
======================================================================
Rows : 99441
Columns : 12
Duplicate Customer IDs : 0

,customer_key,customer_id,customer_unique_id,customer_city,customer_state,customer_zip_code_prefix,customer_segment,customer_total_orders,customer_lifetime_value,customer_avg_order_value,customer_tenure_days,repeat_customer
0,1,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,osasco,SP,6273,Silver,1,114.74,114.74,0,False
1,2,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,itapecerica,MG,35550,Bronze,1,67.41,67.41,0,False
2,3,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,nova venecia,ES,29830,Silver,1,195.42,195.42,0,False
3,4,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,mendonca,MG,39664,Silver,1,179.35,179.35,0,False
4,5,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,sao paulo,SP,4841,Silver,1,107.01,107.01,0,False

,product_key,product_id,product_category,product_weight_g,product_length_cm,product_width_cm,product_height_cm,product_volume_cm3,product_sales_count,product_total_revenue,product_avg_review,product_avg_price,product_popularity_rank,product_revenue_rank
0,1,00066f42aeeb9f3007548bb9d3f33c38,perfumery,300.0,20.0,16.0,16.0,5120.0,1.0,120.24,5.0,101.65,138.0,18576.0
1,2,00088930e925c41fd95ebfe695fd2655,auto,1225.0,55.0,26.0,10.0,14300.0,1.0,143.83,4.0,129.90,138.0,17316.0
2,3,0009406fd7479715e4bef61dd91f2462,bed_bath_table,300.0,45.0,35.0,15.0,23625.0,1.0,242.10,1.0,229.00,138.0,13137.0
3,4,000b8f95fcb9e0096488278317764d19,housewares,550.0,19.0,12.0,24.0,5472.0,2.0,157.00,5.0,58.90,137.0,16658.0
4,5,000d9be29b5207b54e86aa1b1ac54872,watches_gifts,250.0,22.0,15.0,11.0,3630.0,1.0,218.27,5.0,199.00,138.0,13973.0

,seller_key,seller_id,seller_city,seller_state,seller_total_orders,seller_revenue,seller_avg_review,seller_avg_delivery_days,seller_rank,seller_performance
0,1,0015a82c2db000af6aaaf3ae2ecb0532,santo andre,SP,3.0,2748.06,3.666667,7.333333,1078.0,Average
1,2,001cca7ae9ae17fb1caed9dfb1094831,cariacica,ES,239.0,48349.22,3.902542,9.991453,78.0,Average
2,3,001e6ad469a905060d959994f1b41e4f,sao goncalo,RJ,1.0,267.94,1.000000,NaN,2396.0,Poor
3,4,002100f778ceb8431b7a1020ff7ab48f,franca,SP,55.0,2445.64,3.981818,11.092593,1149.0,Average
4,5,003554e2dce176b5555353e4f3555ac8,goiania,GO,1.0,139.38,5.000000,4.000000,2716.0,Excellent

======================================================================
DIM_PAYMENTS
======================================================================
Rows : 99441
Columns : 6

,payment_key,order_id,payment_methods,payment_installments,total_payment,payment_count
0,1,00010242fe8c5a6d1ba2dd792cb16214,credit_card,2.0,72.19,1
1,2,00018f77f2f0320c557190d7a144bdd3,credit_card,3.0,259.83,1
2,3,000229ec398224ef6ca0657da4fc703e,credit_card,5.0,216.87,1
3,4,00024acbcdf0a6daa1e931b038114c75,credit_card,2.0,25.78,1
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,credit_card,3.0,218.04,1

======================================================================
DIM_REVIEWS
======================================================================
Rows : 99441
Columns : 6
Duplicate Orders : 0

,review_key,order_id,review_score,review_category,review_available,review_label
0,1,e22acc9c116caa3f2b7121bbb380d08e,5.0,Excellent,True,Positive
1,2,3594e05a005ac4d06a72673270ef9ec9,4.0,Good,True,Positive
2,3,b33ec3b699337181488304f362a6b734,3.0,Average,True,Neutral
3,4,41272756ecddd9a9ed0180413cc22fb6,4.0,Good,True,Positive
4,5,d957021f1127559cd947b62533f484f7,5.0,Excellent,True,Positive

,location_key,customer_city,customer_state,seller_city,seller_state,local_order
0,1,brasileia,AC,ribeirao preto,SP,False
1,2,cruzeiro do sul,AC,mombuca,SP,False
2,3,cruzeiro do sul,AC,presidente prudente,SP,False
3,4,cruzeiro do sul,AC,sao paulo,SP,False
4,5,epitaciolandia,AC,sao paulo,SP,False

======================================================================
DIM_STATUS
======================================================================
Rows : 8
Unique Status : 8

   status_key order_status
0           1     approved
1           2     canceled
2           3      created
3           4    delivered
4           5     invoiced
5           6   processing
6           7      shipped
7           8  unavailable

============================================================
PRODUCT DIMENSION
============================================================
Rows : 32951
Duplicate Product IDs : 0
Missing Product IDs : 0
============================================================
SELLER DIMENSION
============================================================
Rows : 3095
Duplicate Seller IDs : 0
Missing Seller IDs : 0
======================================================================
DIM_DATE
======================================================================
Rows : 774
Columns : 10

,date_key,date,purchase_year,purchase_quarter,purchase_month,purchase_week,purchase_day,purchase_day_number,purchase_weekend,purchase_season
0,1,2016-09-04,2016,3,September,35,Sunday,4,True,Spring
1,2,2016-09-05,2016,3,September,36,Monday,5,False,Spring
2,3,2016-09-06,2016,3,September,36,Tuesday,6,False,Spring
3,4,2016-09-07,2016,3,September,36,Wednesday,7,False,Spring
4,5,2016-09-08,2016,3,September,36,Thursday,8,False,Spring

================================================================================
ALL DIMENSION TABLES CREATED
================================================================================
dim_customers        (99441, 12)
dim_products         (32951, 14)
dim_sellers          (3095, 10)
dim_payments         (99441, 6)
dim_reviews          (99441, 6)
dim_locations        (36771, 6)
dim_status           (8, 2)
dim_date             (774, 10)

In [ ]:
# ============================================================
# FACT SALES
# STEP 1
# ============================================================

fact_sales = warehouse.copy()

print("="*70)
print("FACT SALES INITIALIZED")
print("="*70)

print(fact_sales.shape)

# ============================================================
# DATE KEY
# ============================================================

fact_sales["purchase_date"] = (

    fact_sales["order_purchase_timestamp"]

    .dt.normalize()

)

# ============================================================
# CUSTOMER KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_customers[

        ["customer_key","customer_id"]

    ],

    on="customer_id",

    how="left"

)

# ============================================================
# PRODUCT KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_products[

        ["product_key","product_id"]

    ],

    on="product_id",

    how="left"

)

# ============================================================
# SELLER KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_sellers[

        ["seller_key","seller_id"]

    ],

    on="seller_id",

    how="left"

)

# ============================================================
# PAYMENT KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_payments[

        ["payment_key","order_id"]

    ],

    on="order_id",

    how="left"

)

# ============================================================
# REVIEW KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_reviews[

        ["review_key","order_id"]

    ],

    on="order_id",

    how="left"

)

# ============================================================
# STATUS KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_status,

    on="order_status",

    how="left"

)

# ============================================================
# DATE KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_date[

        ["date_key","date"]

    ],

    left_on="purchase_date",

    right_on="date",

    how="left"

)

fact_sales.drop(

    columns=["date"],

    inplace=True

)

# ============================================================
# LOCATION KEY
# ============================================================

fact_sales = fact_sales.merge(

    dim_locations,

    on=[

        "customer_city",

        "customer_state",

        "seller_city",

        "seller_state",

        "local_order"

    ],

    how="left"

)

# ============================================================
# FINAL FACT TABLE
# ============================================================

fact_sales = fact_sales[[

    "date_key",

    "customer_key",

    "product_key",

    "seller_key",

    "payment_key",

    "review_key",

    "location_key",

    "status_key",

    "order_id",

    "order_item_id",

    "price",

    "freight_value",

    "total_payment",

    "basket_size",

    "basket_value",

    "profit_proxy",

    "delivery_days",

    "shipping_days",

    "approval_hours",

    "delivery_delay_days",

    "review_score"

]].copy()

fact_sales.insert(

    0,

    "sales_key",

    range(

        1,

        len(fact_sales)+1

    )

)

print("="*80)
print("FACT SALES CREATED")
print("="*80)

print("Rows :",len(fact_sales))
print("Columns :",len(fact_sales.columns))

display(fact_sales.head())

unknown_product = pd.DataFrame({
    "product_key": [0],
    "product_id": ["UNKNOWN"],
    "product_category": ["Unknown"],
    "product_weight_g": [0],
    "product_length_cm": [0],
    "product_width_cm": [0],
    "product_height_cm": [0],
    "product_volume_cm3": [0],
    "product_sales_count": [0],
    "product_total_revenue": [0],
    "product_avg_review": [0],
    "product_avg_price": [0],
    "product_popularity_rank": [0],
    "product_revenue_rank": [0]
})

dim_products = pd.concat(
    [unknown_product, dim_products],
    ignore_index=True
)

unknown_seller = pd.DataFrame({
    "seller_key": [0],
    "seller_id": ["UNKNOWN"],
    "seller_city": ["Unknown"],
    "seller_state": ["Unknown"],
    "seller_total_orders": [0],
    "seller_revenue": [0],
    "seller_avg_review": [0],
    "seller_avg_delivery_days": [0],
    "seller_rank": [0],
    "seller_performance": ["Unknown"]
})

dim_sellers = pd.concat(
    [unknown_seller, dim_sellers],
    ignore_index=True
)

duplicate_lines = fact_sales.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

print("Duplicate Business Transactions:", duplicate_lines)




# ============================================================
# HANDLE UNKNOWN DIMENSION MEMBERS
# ============================================================

# Replace missing foreign keys with Unknown Key (0)

fact_sales["product_key"] = (
    fact_sales["product_key"]
    .fillna(0)
    .astype(int)
)

fact_sales["seller_key"] = (
    fact_sales["seller_key"]
    .fillna(0)
    .astype(int)
)

print("="*70)
print("UNKNOWN DIMENSION MEMBERS HANDLED")
print("="*70)

print("Missing Product Keys :", fact_sales["product_key"].isna().sum())
print("Missing Seller Keys  :", fact_sales["seller_key"].isna().sum())




# ============================================================
# VALIDATION
# ============================================================

print("="*80)
print("FACT TABLE VALIDATION")
print("="*80)

checks = {

    "Duplicate Sales Keys":
        fact_sales["sales_key"].duplicated().sum(),

    "Missing Customer Keys":
        fact_sales["customer_key"].isna().sum(),

    "Missing Product Keys":
        fact_sales["product_key"].isna().sum(),

    "Missing Seller Keys":
        fact_sales["seller_key"].isna().sum(),

    "Missing Payment Keys":
        fact_sales["payment_key"].isna().sum(),

    "Missing Review Keys":
        fact_sales["review_key"].isna().sum(),

    "Missing Date Keys":
        fact_sales["date_key"].isna().sum(),

    "Missing Status Keys":
        fact_sales["status_key"].isna().sum(),

    "Missing Location Keys":
        fact_sales["location_key"].isna().sum()

}

for check,value in checks.items():

    print(f"{check:<35}{value}")


    # ============================================================
# SAVE FACT TABLE
# ============================================================

fact_sales.to_parquet(

    os.path.join(

        FACTS,

        "fact_sales.parquet"

    ),

    index=False

)

fact_sales.to_csv(

    os.path.join(

        FACTS,

        "fact_sales.csv"

    ),

    index=False

)

print("="*80)
print("FACT TABLE SAVED SUCCESSFULLY")
print("="*80)

======================================================================
FACT SALES INITIALIZED
======================================================================
(113425, 97)
================================================================================
FACT SALES CREATED
================================================================================
Rows : 113425
Columns : 22

,sales_key,date_key,customer_key,product_key,seller_key,payment_key,review_key,location_key,status_key,order_id,order_item_id,price,freight_value,total_payment,basket_size,basket_value,profit_proxy,delivery_days,shipping_days,approval_hours,delivery_delay_days,review_score
0,1,614,97470,7159.0,2644.0,88030,1,27069,4,e22acc9c116caa3f2b7121bbb380d08e,1.0,129.90,12.00,141.90,1,141.90,117.90,4.0,1.0,0.247500,-6.0,5.0
1,2,611,29730,10467.0,228.0,20761,2,31806,4,3594e05a005ac4d06a72673270ef9ec9,1.0,18.90,8.29,27.19,1,27.19,10.61,1.0,1.0,7.238056,-6.0,4.0
2,3,188,60279,13004.0,732.0,69504,3,24920,4,b33ec3b699337181488304f362a6b734,1.0,69.00,17.22,86.22,1,86.22,51.78,23.0,2.0,0.000000,-4.0,3.0
3,4,404,56347,4674.0,2891.0,25241,4,12437,4,41272756ecddd9a9ed0180413cc22fb6,1.0,25.99,17.63,43.62,1,43.62,8.36,19.0,0.0,0.326667,-12.0,4.0
4,5,437,27597,25630.0,1375.0,84519,5,35521,4,d957021f1127559cd947b62533f484f7,1.0,180.00,16.89,196.89,1,196.89,163.11,11.0,1.0,0.352778,-9.0,5.0

Duplicate Business Transactions: 0
======================================================================
UNKNOWN DIMENSION MEMBERS HANDLED
======================================================================
Missing Product Keys : 0
Missing Seller Keys  : 0
================================================================================
FACT TABLE VALIDATION
================================================================================
Duplicate Sales Keys               0
Missing Customer Keys              0
Missing Product Keys               0
Missing Seller Keys                0
Missing Payment Keys               0
Missing Review Keys                0
Missing Date Keys                  0
Missing Status Keys                0
Missing Location Keys              0
================================================================================
FACT TABLE SAVED SUCCESSFULLY
================================================================================

In [ ]:
# ============================================================
# CREATE DELIVERY FLAGS
# ============================================================

warehouse["late_delivery"] = (
    warehouse["delivery_delay_days"].fillna(0) > 0
).astype(int)

warehouse["on_time_delivery"] = (
    warehouse["delivery_delay_days"].fillna(0) <= 0
).astype(int)

print("Delivery flags created successfully!")

print("Late Deliveries :", warehouse["late_delivery"].sum())
print("On Time Deliveries :", warehouse["on_time_delivery"].sum())


print("late_delivery" in warehouse.columns)
print("on_time_delivery" in warehouse.columns)

Delivery flags created successfully!
Late Deliveries : 4534
On Time Deliveries : 108891
True
True

Enterprises KPI & Semantic

In [ ]:
# ============================================================
# PHASE 6
# KPI LAYER
# ============================================================

KPI_PATH = os.path.join(BASE, "data", "kpi")

os.makedirs(KPI_PATH, exist_ok=True)

print("KPI Folder Ready")

# ============================================================
# EXECUTIVE METRICS
# ============================================================

executive_metrics = pd.DataFrame({

    "Metric":[

        "Total Revenue",

        "Total Orders",

        "Total Customers",

        "Total Products",

        "Total Sellers",

        "Average Order Value",

        "Average Basket Size",

        "Average Review Score",

        "Average Delivery Days"

    ],

    "Value":[

        fact_sales["total_payment"].sum(),

        fact_sales["order_id"].nunique(),

        fact_sales["customer_key"].nunique(),

        fact_sales["product_key"].nunique(),

        fact_sales["seller_key"].nunique(),

        fact_sales["total_payment"].mean(),

        fact_sales["basket_size"].mean(),

        fact_sales["review_score"].mean(),

        fact_sales["delivery_days"].mean()

    ]

})

display(executive_metrics)

# ============================================================
# CUSTOMER METRICS
# ============================================================

customer_metrics = (

    warehouse

    .groupby("customer_id")

    .agg(

        TotalOrders=("order_id","nunique"),

        LifetimeValue=("total_payment","sum"),

        AverageOrderValue=("total_payment","mean"),

        AverageReview=("review_score","mean"),

        AverageDelivery=("delivery_days","mean")

    )

    .reset_index()

)

display(customer_metrics.head())


# ============================================================
# SELLER METRICS
# ============================================================

seller_metrics = (

    warehouse

    .groupby("seller_id")

    .agg(

        Revenue=("total_payment","sum"),

        Orders=("order_id","count"),

        AverageReview=("review_score","mean"),

        AverageDelivery=("delivery_days","mean")

    )

    .reset_index()

)

display(seller_metrics.head())

# ============================================================
# PRODUCT METRICS
# ============================================================

product_metrics = (

    warehouse

    .groupby("product_id")

    .agg(

        Revenue=("total_payment","sum"),

        Quantity=("order_item_id","count"),

        AveragePrice=("price","mean"),

        AverageReview=("review_score","mean")

    )

    .reset_index()

)

display(product_metrics.head())

# ============================================================
# CREATE DELIVERY FLAGS
# ============================================================

warehouse["late_delivery"] = (
    warehouse["delivery_delay_days"].fillna(0) > 0
).astype(int)

warehouse["on_time_delivery"] = (
    warehouse["delivery_delay_days"].fillna(0) <= 0
).astype(int)

# ============================================================
# OPERATIONAL METRICS
# ============================================================

operational_metrics = pd.DataFrame({

    "Metric":[

        "Late Deliveries",

        "On Time Deliveries",

        "Average Shipping Days",

        "Average Approval Hours",

        "Average Freight"

    ],

    "Value":[

        warehouse["late_delivery"].sum(),

        warehouse["on_time_delivery"].sum(),

        warehouse["shipping_days"].mean(),

        warehouse["approval_hours"].mean(),

        warehouse["freight_value"].mean()

    ]

})

display(operational_metrics)


# ============================================================
# MONTHLY REVENUE
# ============================================================

monthly_revenue = (

    warehouse

    .groupby([

        "purchase_year",

        "purchase_month"

    ])

    .agg(

        Revenue=("total_payment","sum"),

        Orders=("order_id","nunique"),

        Customers=("customer_id","nunique")

    )

    .reset_index()

)

display(monthly_revenue)

# ============================================================
# CATEGORY PERFORMANCE
# ============================================================

category_metrics = (

    warehouse

    .groupby("product_category")

    .agg(

        Revenue=("total_payment","sum"),

        Orders=("order_id","count"),

        Review=("review_score","mean")

    )

    .sort_values(

        "Revenue",

        ascending=False

    )

    .reset_index()

)

display(category_metrics.head(20))

def calculate_aov(df):
    return df["total_payment"].sum() / df["order_id"].nunique()

def calculate_repeat_purchase_rate(df):
    ...

def calculate_clv(df):
    ...

# ============================================================
# SAVE KPI TABLES
# ============================================================

tables = {

    "executive_metrics":executive_metrics,

    "customer_metrics":customer_metrics,

    "seller_metrics":seller_metrics,

    "product_metrics":product_metrics,

    "operational_metrics":operational_metrics,

    "monthly_revenue":monthly_revenue,

    "category_metrics":category_metrics

}

for name,table in tables.items():

    table.to_parquet(

        os.path.join(

            KPI_PATH,

            f"{name}.parquet"

        ),

        index=False

    )

    table.to_csv(

        os.path.join(

            KPI_PATH,

            f"{name}.csv"

        ),

        index=False

    )

print("="*70)
print("KPI LAYER CREATED")
print("="*70)

print("Tables Generated")

for name in tables.keys():

    print(name)


    # ============================================================
# PHASE 5.5
# CREATE SQLITE DATABASE
# ============================================================

import sqlite3
import os
import pandas as pd

BASE = "/content/drive/MyDrive/InsightFlow_AI"

os.makedirs(BASE, exist_ok=True)

DB_PATH = os.path.join(BASE, "warehouse.db")

# ------------------------------------------------------------
# Delete old database if it exists
# ------------------------------------------------------------

if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

# ------------------------------------------------------------
# Create new SQLite database
# ------------------------------------------------------------

conn = sqlite3.connect(DB_PATH)

print("="*80)
print("CREATING SQLITE DATABASE")
print("="*80)

# ------------------------------------------------------------
# Store all warehouse tables
# ------------------------------------------------------------

warehouse_tables = {

    "fact_sales": fact_sales,

    "dim_customers": dim_customers,

    "dim_products": dim_products,

    "dim_sellers": dim_sellers,

    "dim_reviews": dim_reviews,

    "dim_payments": dim_payments,

    "dim_locations": dim_locations,

    "dim_status": dim_status,

    "dim_date": dim_date

}

# ------------------------------------------------------------
# Write tables
# ------------------------------------------------------------

for table_name, dataframe in warehouse_tables.items():

    dataframe.to_sql(

        table_name,

        conn,

        if_exists="replace",

        index=False

    )

    print(f"✓ {table_name:<20} {len(dataframe):>8,} rows")

# ------------------------------------------------------------
# Commit
# ------------------------------------------------------------

conn.commit()

# ------------------------------------------------------------
# Verify tables
# ------------------------------------------------------------

print("\n")

print("="*80)
print("VERIFYING DATABASE")
print("="*80)

tables = pd.read_sql("""

SELECT

name

FROM sqlite_master

WHERE type='table'

ORDER BY name;

""", conn)

display(tables)

print("\n")

summary = []

for table in tables["name"]:

    rows = pd.read_sql(

        f"SELECT COUNT(*) AS total FROM {table}",

        conn

    )["total"][0]

    summary.append([table, rows])

summary = pd.DataFrame(

    summary,

    columns=[

        "Table",

        "Rows"

    ]

)

display(summary)

conn.close()

print("\n")

print("="*80)
print("SQLITE DATABASE CREATED SUCCESSFULLY")
print("="*80)

print("Database Location:")

print(DB_PATH)

import sqlite3
import pandas as pd
import os

BASE = "/content/drive/MyDrive/InsightFlow_AI"

conn = sqlite3.connect(os.path.join(BASE,"warehouse.db"))

pd.read_sql("""

SELECT COUNT(*) AS Total_Orders

FROM fact_sales

""", conn)

KPI Folder Ready

                  Metric         Value
0          Total Revenue  2.047073e+07
1           Total Orders  9.944100e+04
2        Total Customers  9.944100e+04
3         Total Products  3.295200e+04
4          Total Sellers  3.096000e+03
5    Average Order Value  1.804829e+02
6    Average Basket Size  1.386132e+00
7   Average Review Score  4.017589e+00
8  Average Delivery Days  8.733890e+00

,customer_id,TotalOrders,LifetimeValue,AverageOrderValue,AverageReview,AverageDelivery
0,00012a2ce6f8dcda20d059ce98491703,1,114.74,114.74,1.0,11.0
1,000161a058600d5901f007fab4c27140,1,67.41,67.41,4.0,5.0
2,0001fd6190edaaf884bcaf3d49edf079,1,195.42,195.42,5.0,4.0
3,0002414f95344307404f0ace7a26f1d5,1,179.35,179.35,5.0,25.0
4,000379cdec625522490c315e70c7a9fb,1,107.01,107.01,4.0,9.0

,seller_id,Revenue,Orders,AverageReview,AverageDelivery
0,0015a82c2db000af6aaaf3ae2ecb0532,2748.06,3,3.666667,7.333333
1,001cca7ae9ae17fb1caed9dfb1094831,48349.22,239,3.902542,9.991453
2,001e6ad469a905060d959994f1b41e4f,267.94,1,1.000000,NaN
3,002100f778ceb8431b7a1020ff7ab48f,2445.64,55,3.981818,11.092593
4,003554e2dce176b5555353e4f3555ac8,139.38,1,5.000000,4.000000

,product_id,Revenue,Quantity,AveragePrice,AverageReview
0,00066f42aeeb9f3007548bb9d3f33c38,120.24,1,101.65,5.0
1,00088930e925c41fd95ebfe695fd2655,143.83,1,129.90,4.0
2,0009406fd7479715e4bef61dd91f2462,242.10,1,229.00,1.0
3,000b8f95fcb9e0096488278317764d19,157.00,2,58.90,5.0
4,000d9be29b5207b54e86aa1b1ac54872,218.27,1,199.00,5.0

                   Metric          Value
0         Late Deliveries    4534.000000
1      On Time Deliveries  108891.000000
2   Average Shipping Days       2.405966
3  Average Approval Hours      10.663526
4         Average Freight      19.990320

    purchase_year purchase_month     Revenue  Orders  Customers
0            2016       December       19.62       1          1
1            2016        October    76120.17     324        324
2            2016      September      388.47       4          4
3            2017          April   510891.55    2404       2404
4            2017         August   876129.37    4331       4331
5            2017       December  1057582.34    5673       5673
6            2017       February   349701.93    1780       1780
7            2017        January   189015.66     800        800
8            2017           July   744599.53    4026       4026
9            2017           June   608891.38    3245       3245
10           2017          March   544738.23    2682       2682
11           2017            May   731017.09    3700       3700
12           2017       November  1599444.18    7544       7544
13           2017        October  1031505.53    4631       4631
14           2017      September  1023095.49    4285       4285
15           2018          April  1497843.94    6939       6939
16           2018         August  1248837.93    6512       6512
17           2018       February  1311260.71    6728       6728
18           2018        January  1415348.54    7269       7269
19           2018           July  1359421.48    6292       6292
20           2018           June  1298685.81    6167       6167
21           2018          March  1480045.50    7211       7211
22           2018            May  1511113.00    6873       6873
23           2018        October      589.67       4          4
24           2018      September     4439.54      16         16

         product_category     Revenue  Orders    Review
0          bed_bath_table  1712553.67   11115  3.898334
1           health_beauty  1657373.12    9670  4.141827
2   computers_accessories  1585330.45    7827  3.932601
3         furniture_decor  1430176.39    8334  3.907333
4           watches_gifts  1429216.68    5991  4.018855
5          sports_leisure  1392127.56    8641  4.107039
6              housewares  1094758.13    6964  4.054785
7                    auto   852294.33    4235  4.064885
8            garden_tools   838280.75    4347  4.045539
9              cool_stuff   779698.00    3796  4.146598
10       office_furniture   646826.49    1691  3.488968
11                   toys   619037.69    4117  4.159564
12                   baby   539845.66    3065  4.010691
13              perfumery   506738.66    3419  4.166079
14              telephony   486882.05    4545  3.945922
15                Unknown   421903.74    2402  3.158295
16             stationery   317440.07    2517  4.195478
17               pet_shop   311268.97    1947  4.184306
18              computers   279121.55     203  4.175000
19            electronics   259857.10    2767  4.037118

======================================================================
KPI LAYER CREATED
======================================================================
Tables Generated
executive_metrics
customer_metrics
seller_metrics
product_metrics
operational_metrics
monthly_revenue
category_metrics
================================================================================
CREATING SQLITE DATABASE
================================================================================
✓ fact_sales            113,425 rows
✓ dim_customers          99,441 rows
✓ dim_products           32,952 rows
✓ dim_sellers             3,096 rows
✓ dim_reviews            99,441 rows
✓ dim_payments           99,441 rows
✓ dim_locations          36,771 rows
✓ dim_status                  8 rows
✓ dim_date                  774 rows


================================================================================
VERIFYING DATABASE
================================================================================

            name
0  dim_customers
1       dim_date
2  dim_locations
3   dim_payments
4   dim_products
5    dim_reviews
6    dim_sellers
7     dim_status
8     fact_sales

           Table    Rows
0  dim_customers   99441
1       dim_date     774
2  dim_locations   36771
3   dim_payments   99441
4   dim_products   32952
5    dim_reviews   99441
6    dim_sellers    3096
7     dim_status       8
8     fact_sales  113425

================================================================================
SQLITE DATABASE CREATED SUCCESSFULLY
================================================================================
Database Location:
/content/drive/MyDrive/InsightFlow_AI/warehouse.db

   Total_Orders
0        113425

In [ ]:
print("warehouse:", "warehouse" in globals())
print("fact_sales:", "fact_sales" in globals())
print("dim_customers:", "dim_customers" in globals())

warehouse: True
fact_sales: True
dim_customers: True

SQL Analytics

In [ ]:
# ============================================================
# PHASE 7
# ENTERPRISE SQL ANALYTICS
# FINAL FIXED VERSION
# ============================================================

import sqlite3
import pandas as pd
import os

# ============================================================
# CONFIGURATION
# ============================================================

BASE = "/content/drive/MyDrive/InsightFlow_AI"

SQL_PATH = os.path.join(
    BASE,
    "reports",
    "sql_results"
)

os.makedirs(
    SQL_PATH,
    exist_ok=True
)

DB_PATH = os.path.join(
    BASE,
    "warehouse.db"
)

print("=" * 80)
print("INSIGHTFLOW AI - PHASE 7 SQL ANALYTICS")
print("=" * 80)


# ============================================================
# CHECK REQUIRED DATAFRAMES
# ============================================================

required_objects = [
    "fact_sales",
    "dim_customers",
    "dim_products",
    "dim_sellers",
    "dim_reviews",
    "dim_payments",
    "dim_locations",
    "dim_status",
    "dim_date"
]

print("=" * 80)
print("CHECKING REQUIRED DATAFRAMES")
print("=" * 80)

missing = []

for obj in required_objects:

    exists = obj in globals()

    print(
        f"{obj:<25}{exists}"
    )

    if not exists:
        missing.append(obj)


if missing:

    raise NameError(
        "\nMissing DataFrames:\n"
        + "\n".join(
            f" - {x}"
            for x in missing
        )
        + "\n\nRun the Star Schema and Fact Sales phases first."
    )


# ============================================================
# CONNECT SQLITE
# ============================================================

print("=" * 80)
print("CONNECTING TO SQLITE")
print("=" * 80)

if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

conn = sqlite3.connect(DB_PATH)

print("SQLite Connected Successfully!")


# ============================================================
# LOAD STAR SCHEMA
# ============================================================

tables = {

    "fact_sales": fact_sales,

    "dim_customers": dim_customers,

    "dim_products": dim_products,

    "dim_sellers": dim_sellers,

    "dim_reviews": dim_reviews,

    "dim_payments": dim_payments,

    "dim_locations": dim_locations,

    "dim_status": dim_status,

    "dim_date": dim_date

}


print("=" * 80)
print("LOADING STAR SCHEMA INTO SQLITE")
print("=" * 80)


for name, df in tables.items():

    df.to_sql(

        name,

        conn,

        if_exists="replace",

        index=False

    )

    print(
        f"{name:<25}"
        f"{len(df):>12,} rows"
    )


conn.commit()


# ============================================================
# SHOW ACTUAL DATE SCHEMA
# ============================================================

print("=" * 80)
print("DIM_DATE COLUMNS")
print("=" * 80)

date_schema = pd.read_sql_query(
    "PRAGMA table_info(dim_date)",
    conn
)

display(
    date_schema[
        ["name", "type"]
    ]
)


# ============================================================
# QUERY ENGINE
# ============================================================

def run_query(
    title,
    query,
    save=True
):

    print("\n")
    print("=" * 90)
    print(title)
    print("=" * 90)

    result = pd.read_sql_query(
        query,
        conn
    )

    display(result)

    if save:

        filename = (

            title
            .lower()
            .replace(" ", "_")
            .replace("-", "_")
            .replace("/", "_")

        )

        output_path = os.path.join(
            SQL_PATH,
            filename + ".csv"
        )

        result.to_csv(
            output_path,
            index=False
        )

        print(
            "Saved:",
            output_path
        )

    return result


# ============================================================
# 1. EXECUTIVE KPI
# ============================================================

executive_kpi = run_query(

    "Executive KPI",

    """

    SELECT

        COUNT(DISTINCT order_id)
            AS TotalOrders,

        COUNT(DISTINCT customer_key)
            AS TotalCustomers,

        COUNT(DISTINCT product_key)
            AS TotalProducts,

        COUNT(DISTINCT seller_key)
            AS TotalSellers,

        ROUND(
            SUM(total_payment),
            2
        ) AS TotalRevenue,

        ROUND(
            SUM(total_payment)
            /
            NULLIF(
                COUNT(DISTINCT order_id),
                0
            ),
            2
        ) AS AverageOrderValue,

        ROUND(
            AVG(basket_size),
            2
        ) AS AverageBasketSize,

        ROUND(
            AVG(review_score),
            2
        ) AS AverageReviewScore,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays

    FROM fact_sales

    """

)


# ============================================================
# 2. MONTHLY REVENUE
# ============================================================
# IMPORTANT:
# We use dim_date.date instead of guessing month-name columns.
# ============================================================

monthly_revenue = run_query(

    "Monthly Revenue",

    """

    SELECT

        CAST(
            strftime(
                '%Y',
                d.date
            ) AS INTEGER
        ) AS Year,

        CAST(
            strftime(
                '%m',
                d.date
            ) AS INTEGER
        ) AS Month,

        CASE
            CAST(
                strftime(
                    '%m',
                    d.date
                ) AS INTEGER
            )

            WHEN 1 THEN 'January'
            WHEN 2 THEN 'February'
            WHEN 3 THEN 'March'
            WHEN 4 THEN 'April'
            WHEN 5 THEN 'May'
            WHEN 6 THEN 'June'
            WHEN 7 THEN 'July'
            WHEN 8 THEN 'August'
            WHEN 9 THEN 'September'
            WHEN 10 THEN 'October'
            WHEN 11 THEN 'November'
            WHEN 12 THEN 'December'

        END AS MonthName,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        COUNT(
            DISTINCT f.customer_key
        ) AS Customers,

        ROUND(

            SUM(f.total_payment)

            /

            NULLIF(
                COUNT(DISTINCT f.order_id),
                0
            ),

            2

        ) AS AverageOrderValue

    FROM fact_sales f

    INNER JOIN dim_date d

        ON f.date_key = d.date_key

    GROUP BY

        strftime('%Y', d.date),

        strftime('%m', d.date)

    ORDER BY

        Year,

        Month

    """

)


# ============================================================
# 3. TOP PRODUCT CATEGORIES
# ============================================================

top_products = run_query(

    "Top Product Categories",

    """

    SELECT

        p.product_category
            AS ProductCategory,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        COUNT(*)
            AS ItemsSold,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.price),
            2
        ) AS AveragePrice

    FROM fact_sales f

    INNER JOIN dim_products p

        ON f.product_key =
           p.product_key

    WHERE
        f.product_key <> 0

    GROUP BY

        p.product_category

    ORDER BY

        Revenue DESC

    LIMIT 20

    """

)


# ============================================================
# 4. TOP INDIVIDUAL PRODUCTS
# ============================================================

top_individual_products = run_query(

    "Top Individual Products",

    """

    SELECT

        p.product_id
            AS ProductID,

        p.product_category
            AS ProductCategory,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        COUNT(*)
            AS ItemsSold,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview

    FROM fact_sales f

    INNER JOIN dim_products p

        ON f.product_key =
           p.product_key

    WHERE
        f.product_key <> 0

    GROUP BY

        p.product_id,

        p.product_category

    ORDER BY

        Revenue DESC

    LIMIT 20

    """

)


# ============================================================
# 5. SELLER PERFORMANCE
# ============================================================

seller_performance = run_query(

    "Seller Performance",

    """

    SELECT

        s.seller_id
            AS SellerID,

        s.seller_city
            AS SellerCity,

        s.seller_state
            AS SellerState,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays

    FROM fact_sales f

    INNER JOIN dim_sellers s

        ON f.seller_key =
           s.seller_key

    WHERE
        f.seller_key <> 0

    GROUP BY

        s.seller_id,

        s.seller_city,

        s.seller_state

    ORDER BY

        Revenue DESC

    LIMIT 50

    """

)


# ============================================================
# 6. CUSTOMER LIFETIME VALUE
# ============================================================

customer_lifetime_value = run_query(

    "Customer Lifetime Value",

    """

    SELECT

        c.customer_id
            AS CustomerID,

        c.customer_city
            AS City,

        c.customer_state
            AS State,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS LifetimeValue,

        ROUND(

            SUM(f.total_payment)

            /

            NULLIF(
                COUNT(DISTINCT f.order_id),
                0
            ),

            2

        ) AS AverageOrderValue,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview

    FROM fact_sales f

    INNER JOIN dim_customers c

        ON f.customer_key =
           c.customer_key

    GROUP BY

        c.customer_id,

        c.customer_city,

        c.customer_state

    ORDER BY

        LifetimeValue DESC

    LIMIT 50

    """

)


# ============================================================
# 7. DELIVERY PERFORMANCE
# ============================================================

delivery_performance = run_query(

    "Delivery Performance",

    """

    SELECT

        COUNT(
            DISTINCT order_id
        ) AS Orders,

        COUNT(
            DISTINCT
            CASE
                WHEN delivery_delay_days > 0
                THEN order_id
            END
        ) AS LateOrders,

        COUNT(
            DISTINCT
            CASE
                WHEN delivery_delay_days <= 0
                THEN order_id
            END
        ) AS OnTimeOrEarlyOrders,

        ROUND(
            100.0 *

            COUNT(
                DISTINCT
                CASE
                    WHEN delivery_delay_days > 0
                    THEN order_id
                END
            )

            /

            NULLIF(
                COUNT(DISTINCT order_id),
                0
            ),

            2

        ) AS LateDeliveryPercent,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            AVG(shipping_days),
            2
        ) AS AverageShippingDays,

        ROUND(
            AVG(delivery_delay_days),
            2
        ) AS AverageDeliveryDelay

    FROM fact_sales

    """

)


# ============================================================
# 8. ORDER STATUS
# ============================================================

status_performance = run_query(

    "Order Status Performance",

    """

    SELECT

        s.order_status
            AS OrderStatus,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays

    FROM fact_sales f

    INNER JOIN dim_status s

        ON f.status_key =
           s.status_key

    GROUP BY

        s.order_status

    ORDER BY

        Orders DESC

    """

)


# ============================================================
# 9. REVIEW ANALYSIS
# ============================================================

review_analysis = run_query(

    "Review Analysis",

    """

    SELECT

        review_score
            AS ReviewScore,

        COUNT(
            DISTINCT order_id
        ) AS Orders,

        ROUND(
            AVG(total_payment),
            2
        ) AS AverageOrderValue,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays

    FROM fact_sales

    WHERE
        review_score IS NOT NULL

    GROUP BY

        review_score

    ORDER BY

        review_score DESC

    """

)


# ============================================================
# 10. REVIEW SENTIMENT
# ============================================================

# ============================================================
# 10. REVIEW SENTIMENT
# ============================================================

review_sentiment = run_query(

    "Review Sentiment",

    """

    SELECT

        CASE

            WHEN f.review_score >= 4
                THEN 'Positive'

            WHEN f.review_score = 3
                THEN 'Neutral'

            WHEN f.review_score <= 2
                THEN 'Negative'

            ELSE 'No Review'

        END AS ReviewSentiment,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReviewScore,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays

    FROM fact_sales f

    GROUP BY

        CASE

            WHEN f.review_score >= 4
                THEN 'Positive'

            WHEN f.review_score = 3
                THEN 'Neutral'

            WHEN f.review_score <= 2
                THEN 'Negative'

            ELSE 'No Review'

        END

    ORDER BY

        CASE

            WHEN ReviewSentiment = 'Positive'
                THEN 1

            WHEN ReviewSentiment = 'Neutral'
                THEN 2

            WHEN ReviewSentiment = 'Negative'
                THEN 3

            ELSE 4

        END

    """,

    save=True

)


# ============================================================
# 11. STATE PERFORMANCE
# ============================================================

state_performance = run_query(

    "State Performance",

    """

    SELECT

        l.customer_state
            AS CustomerState,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        COUNT(
            DISTINCT f.customer_key
        ) AS Customers,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays

    FROM fact_sales f

    INNER JOIN dim_locations l

        ON f.location_key =
           l.location_key

    GROUP BY

        l.customer_state

    ORDER BY

        Revenue DESC

    """

)


# ============================================================
# 12. LOCAL VS NON-LOCAL
# ============================================================

local_orders = run_query(

    "Local vs Non Local Orders",

    """

    SELECT

        CASE

            WHEN l.local_order = 1
                THEN 'Local'

            ELSE 'Non-Local'

        END AS OrderType,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            AVG(f.freight_value),
            2
        ) AS AverageFreight

    FROM fact_sales f

    INNER JOIN dim_locations l

        ON f.location_key =
           l.location_key

    GROUP BY

        l.local_order

    ORDER BY

        Revenue DESC

    """

)


# ============================================================
# 13. PROFITABILITY
# ============================================================

profitability = run_query(

    "Profitability Analysis",

    """

    SELECT

        ROUND(
            SUM(total_payment),
            2
        ) AS Revenue,

        ROUND(
            SUM(profit_proxy),
            2
        ) AS ProfitProxy,

        ROUND(
            AVG(profit_proxy),
            2
        ) AS AverageProfitProxy,

        ROUND(

            100.0 *
            SUM(profit_proxy)

            /

            NULLIF(
                SUM(total_payment),
                0
            ),

            2

        ) AS ProfitMarginPercent

    FROM fact_sales

    """

)


# ============================================================
# 14. PAYMENT ANALYSIS
# ============================================================

# ============================================================
# PAYMENT ANALYSIS
# ============================================================

payment_analysis = run_query(

    "Payment Analysis",

    """

    SELECT

        p.payment_methods AS PaymentMethod,

        COUNT(DISTINCT f.order_id) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(p.payment_installments),
            2
        ) AS AverageInstallments,

        ROUND(
            AVG(p.payment_count),
            2
        ) AS AveragePaymentCount

    FROM fact_sales f

    INNER JOIN dim_payments p

        ON f.payment_key = p.payment_key

    GROUP BY

        p.payment_methods

    ORDER BY

        Revenue DESC

    """,

    save=True

)


# ============================================================
# FINAL VALIDATION
# ============================================================

print("\n")
print("=" * 90)
print("PHASE 7 SQL ANALYTICS COMPLETED")
print("=" * 90)

print(
    "Database:",
    DB_PATH
)

print(
    "Reports:",
    SQL_PATH
)

print("\nCSV reports generated successfully.")


# ============================================================
# CLOSE DATABASE
# ============================================================

conn.commit()
conn.close()

print("SQLite connection closed.")
print("=" * 90)

================================================================================
INSIGHTFLOW AI - PHASE 7 SQL ANALYTICS
================================================================================
================================================================================
CHECKING REQUIRED DATAFRAMES
================================================================================
fact_sales               True
dim_customers            True
dim_products             True
dim_sellers              True
dim_reviews              True
dim_payments             True
dim_locations            True
dim_status               True
dim_date                 True
================================================================================
CONNECTING TO SQLITE
================================================================================
SQLite Connected Successfully!
================================================================================
LOADING STAR SCHEMA INTO SQLITE
================================================================================
fact_sales                    113,425 rows
dim_customers                  99,441 rows
dim_products                   32,952 rows
dim_sellers                     3,096 rows
dim_reviews                    99,441 rows
dim_payments                   99,441 rows
dim_locations                  36,771 rows
dim_status                          8 rows
dim_date                          774 rows
================================================================================
DIM_DATE COLUMNS
================================================================================

                  name       type
0             date_key    INTEGER
1                 date  TIMESTAMP
2        purchase_year    INTEGER
3     purchase_quarter    INTEGER
4       purchase_month       TEXT
5        purchase_week    INTEGER
6         purchase_day       TEXT
7  purchase_day_number    INTEGER
8     purchase_weekend    INTEGER
9      purchase_season       TEXT

==========================================================================================
Executive KPI
==========================================================================================

,TotalOrders,TotalCustomers,TotalProducts,TotalSellers,TotalRevenue,AverageOrderValue,AverageBasketSize,AverageReviewScore,AverageDeliveryDays
0,99441,99441,32952,3096,20470726.66,205.86,1.39,4.02,8.73

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/executive_kpi.csv


==========================================================================================
Monthly Revenue
==========================================================================================

    Year  Month  MonthName     Revenue  Orders  Customers  AverageOrderValue
0   2016      9  September      388.47       4          4              97.12
1   2016     10    October    76120.17     324        324             234.94
2   2016     12   December       19.62       1          1              19.62
3   2017      1    January   189015.66     800        800             236.27
4   2017      2   February   349701.93    1780       1780             196.46
5   2017      3      March   544738.23    2682       2682             203.11
6   2017      4      April   510891.55    2404       2404             212.52
7   2017      5        May   731017.09    3700       3700             197.57
8   2017      6       June   608891.38    3245       3245             187.64
9   2017      7       July   744599.53    4026       4026             184.95
10  2017      8     August   876129.37    4331       4331             202.29
11  2017      9  September  1023095.49    4285       4285             238.76
12  2017     10    October  1031505.53    4631       4631             222.74
13  2017     11   November  1599444.18    7544       7544             212.02
14  2017     12   December  1057582.34    5673       5673             186.42
15  2018      1    January  1415348.54    7269       7269             194.71
16  2018      2   February  1311260.71    6728       6728             194.90
17  2018      3      March  1480045.50    7211       7211             205.25
18  2018      4      April  1497843.94    6939       6939             215.86
19  2018      5        May  1511113.00    6873       6873             219.86
20  2018      6       June  1298685.81    6167       6167             210.59
21  2018      7       July  1359421.48    6292       6292             216.06
22  2018      8     August  1248837.93    6512       6512             191.77
23  2018      9  September     4439.54      16         16             277.47
24  2018     10    October      589.67       4          4             147.42

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/monthly_revenue.csv


==========================================================================================
Top Product Categories
==========================================================================================

,ProductCategory,Orders,ItemsSold,Revenue,AverageReview,AveragePrice
0,bed_bath_table,9417,11115,1712553.67,3.90,93.30
1,health_beauty,8836,9670,1657373.12,4.14,130.16
2,computers_accessories,6689,7827,1585330.45,3.93,116.51
3,furniture_decor,6449,8334,1430176.39,3.91,87.56
4,watches_gifts,5624,5991,1429216.68,4.02,201.14
5,sports_leisure,7720,8641,1392127.56,4.11,114.34
6,housewares,5884,6964,1094758.13,4.05,90.79
7,auto,3897,4235,852294.33,4.06,139.96
8,garden_tools,3518,4347,838280.75,4.05,111.63
9,cool_stuff,3632,3796,779698.00,4.15,167.36
10,office_furniture,1273,1691,646826.49,3.49,162.01
11,toys,3886,4117,619037.69,4.16,117.55
12,baby,2885,3065,539845.66,4.01,134.34
13,perfumery,3162,3419,506738.66,4.17,116.74
14,telephony,4199,4545,486882.05,3.95,71.21
15,stationery,2311,2517,317440.07,4.20,91.75
16,pet_shop,1710,1947,311268.97,4.18,110.07
17,computers,181,203,279121.55,4.18,1098.34
18,electronics,2550,2767,259857.10,4.04,57.91
19,Unknown,1473,1627,259311.79,3.83,113.74

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/top_product_categories.csv


==========================================================================================
Top Individual Products
==========================================================================================

,ProductID,ProductCategory,Orders,ItemsSold,Revenue,AverageReview
0,5769ef0a239114ac3a854af00df129e4,fixed_telephony,1,8,109312.64,1.00
1,bb50f2e236e5eea0100680137654686c,health_beauty,187,195,81887.42,4.22
2,422879e10f46682990de24d770e7f83d,garden_tools,352,484,79512.22,3.96
3,d1c427060a0f73f6b889a5c7c61f2ac4,computers_accessories,323,343,70557.90,4.19
4,6cdd53843498f92890544667809f1595,health_beauty,151,156,64825.67,4.32
5,d5991653e037ccb7af6ed7d94246b249,computers_accessories,57,103,64143.26,3.98
6,aca2eb7d00ea1a7b8ebd4e68314663af,furniture_decor,431,527,63788.12,4.02
7,a62e25e09e05e6faf31d90c6ec1aa3d1,watches_gifts,172,226,63167.37,3.86
8,99a4788cb24856965c36a24e339b6058,bed_bath_table,467,488,63161.40,3.90
9,3dd2a17168ec895c781a9191c1e95ad7,computers_accessories,255,274,58962.14,4.21
10,53759a2ecddad2bb87a079a1f1519f73,garden_tools,287,373,53445.35,3.86
11,368c6c730842d78016ad823897a372db,garden_tools,291,388,52508.63,3.92
12,d6160fb7873f184099d9bc95e30376af,computers,35,35,50326.18,4.57
13,53b36df67ebb7c41585e8d54d6772e08,watches_gifts,306,323,48994.30,4.19
14,389d119b48cf3043d311335e499d9c6b,garden_tools,311,392,48616.44,4.12
15,ee3d532c8a438679776d222e997606b3,computers_accessories,8,32,46582.97,1.88
16,e7cc48a9daff5436f63d3aad9426f28b,telephony,64,93,45469.84,3.53
17,9571759451b1d780ee7c15012ea109d4,auto,1,20,45256.00,NaN
18,5f504b3a1c75b73d6151be81eb05bdc9,cool_stuff,63,63,41885.77,4.56
19,25c38557cf793876c5abdd5931f922db,baby,38,38,40540.75,2.68

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/top_individual_products.csv


==========================================================================================
Seller Performance
==========================================================================================

,SellerID,SellerCity,SellerState,Orders,Revenue,AverageReview,AverageDeliveryDays
0,7c67e1448b00f6e969d365cea6b010ab,itaquaquecetuba,SP,982,507166.91,3.34,9.77
1,1025f0e2d44d7041d6cf58b6550e0bfa,sao paulo,SP,915,308222.04,3.85,7.35
2,4a3ca9315b744ce9f8e9374361493884,ibitinga,SP,1806,301245.27,3.80,11.16
3,1f50f920176fa81dab994f9023523100,sao jose do rio preto,SP,1404,290253.42,3.99,11.11
4,53243585a1d6dc2643021fd1853d8905,lauro de freitas,BA,358,284903.08,4.08,9.20
5,da8622b14eb17ae2831f4ac5b9dab84a,piracicaba,SP,1314,272219.32,4.06,7.92
6,4869f7a5dfa277a7dca6462dcf3b52b2,guariba,SP,1132,264166.12,4.12,11.90
7,955fee9216a65b617aa5c0531780ce60,sao paulo,SP,1287,236322.30,4.05,8.04
8,fa1c13f2614d7b5c4749cbc52fecda94,sumare,SP,585,206513.23,4.34,10.16
9,7e93a43ef30c4f03f38b393420bc753a,barueri,SP,336,185134.21,4.21,7.99
10,6560211a19b47992c3666cc44a7e94c0,sao paulo,SP,1854,179657.75,3.91,7.51
11,7a67c85e85bb2ce8582c35f2203ad736,sao paulo,SP,1160,169030.80,4.23,8.70
12,25c5c91f63607446a97b143d2d535d31,itauna,MG,158,160534.74,3.72,8.59
13,a1043bafd471dff536d0c462352beb48,ilicinea,MG,718,154356.91,4.19,11.22
14,46dc3b2cc0980fb8ec44634e21d2718e,rio de janeiro,RJ,521,148864.34,4.18,8.26
15,b37c4c02bda3161a7546a4e6d222d5b2,sao paulo,SP,4,145319.04,1.40,7.87
16,620c87c171fb2a6dd6e8bb4dec959fc6,petropolis,RJ,740,145267.95,4.21,9.73
17,cc419e0650a3c5ba77189a1882b7556a,santo andre,SP,1706,141309.58,4.07,8.21
18,5dceca129747e92ff8ef7a997dc4f8ca,santa barbara d´oeste,SP,325,132974.42,3.99,8.33
19,3d871de0142ce09b7081e2b9d1733cb1,campo limpo paulista,SP,1080,131982.15,4.11,9.63
20,7d13fca15225358621be4086e1eb0964,ribeirao preto,SP,565,129169.98,4.00,11.42
21,cca3071e3e9bb7d12640c9fbe2301306,ibitinga,SP,712,107125.39,3.85,9.90
22,8581055ce74af1daba164fdbd55a40de,guarulhos,SP,387,94322.49,4.23,9.38
23,f7ba60f8c3f99e7ee4042fdef03b70c4,sao bernardo do campo,SP,219,88248.63,4.20,10.05
24,edb1ef5e36e0c8cd84eb3c9b003e486d,teresopolis,RJ,166,86381.32,4.43,9.59
25,de722cd6dad950a92b7d4f82673f8833,recife,PE,339,85852.25,4.16,10.20
26,ccc4bbb5f32a6ab2b7066a4130f114e3,curitiba,PR,187,84993.28,4.28,11.99
27,634964b17796e64304cadf1ad3050fb7,rio de janeiro,RJ,268,83496.83,3.86,10.16
28,77530e9772f57a62c906e1c21538ab82,curitiba,PR,320,83399.39,4.05,12.16
29,fe2032dab1a61af8794248c8196565c9,campinas,SP,294,77462.18,4.38,8.19
30,f8db351d8c4c4c22c6835c19a46f01b0,salto,SP,667,76665.19,4.22,7.75
31,218d46b86c1881d022bce9c68a7d4b15,ribeirao preto,SP,388,76037.73,4.15,11.29
32,8e6d7754bc7e0f22c96d255ebda59eba,sao jose dos campos,SP,85,75934.98,2.97,7.80
33,1835b56ce799e6a4dc4eddc053f04066,ibitinga,SP,423,75255.73,3.59,10.34
34,8160255418d5aaa7dbdc9f4c64ebda44,ibitinga,SP,385,73389.49,3.83,12.08
35,17a053fcb14bd219540cbde0df490be0,mogi guacu,SP,125,70992.61,4.20,7.70
36,522620dcb18a6b31cd7bdf73665113a9,cascavel,PR,174,70945.29,3.90,12.12
37,391fc6631aebcf3004804e51b40bcf1e,ibitinga,SP,526,70856.05,3.96,10.34
38,7681ef142fd2c19048da7430856b5588,guarulhos,SP,59,68331.25,4.12,7.59
39,17f51e7198701186712e53a39c564617,sao paulo,SP,56,67584.27,4.34,10.02
40,e9bc59e7b60fc3063eb2290deda4cced,maringa,PR,216,67146.10,3.94,8.52
41,e9779976487b77c6d4ac45f75ec7afe9,praia grande,SP,657,66979.97,4.17,6.75
42,17e34d8224d27a541263c4c64b11a56b,riberao preto,SP,255,66198.05,4.14,10.49
43,7ddcbb64b5bc1ef36ca8c151f6ec77df,sao paulo,SP,334,65910.99,3.91,9.70
44,9c0e69c7bf2619675bbadf47b43f655a,sao jose dos campos,SP,157,65247.43,4.02,9.22
45,37be5a7c751166fbc5f8ccba4119e043,sao paulo,SP,272,65183.50,4.32,6.82
46,b2ba3715d723d245138f291a6fe42594,sao paulo,SP,337,64934.30,4.11,8.17
47,c70c1b0d8ca86052f45a432a38b73958,hortolandia,SP,261,64762.56,4.30,4.03
48,ceaec5548eefc6e23e6607c5435102e7,sao paulo,SP,203,64675.65,4.15,9.32
49,04308b1ee57b6625f47df1d56f00eedf,bombinhas,SC,94,63184.99,3.88,12.13

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/seller_performance.csv


==========================================================================================
Customer Lifetime Value
==========================================================================================

,CustomerID,City,State,Orders,LifetimeValue,AverageOrderValue,AverageReview
0,1617b1357756262bfa56ab541c47bc16,rio de janeiro,RJ,1,109312.64,109312.64,1.0
1,bd5d39761aa56689a265d95d8d32b8be,goiania,GO,1,45256.00,45256.00,NaN
2,be1b70680b9f9694d8c70f41fa3dc92b,sao paulo,SP,1,44048.00,44048.00,1.0
3,05455dfa7cd02f13d132aa7a6a9729c6,divinopolis,MG,1,36489.24,36489.24,1.0
4,1ff773612ab8934db89fd5afa8afe506,rio de janeiro,RJ,1,30186.00,30186.00,5.0
5,ec5b2ba62e574342386871631fafd3fc,vila velha,ES,1,29099.52,29099.52,1.0
6,e7d6802668de6e74d0d6c56565bf2a24,sao paulo,SP,1,22346.60,22346.60,1.0
7,8c20d9bfbc96c5d39025d77a3ba83d7f,cicero dantas,BA,1,21874.05,21874.05,3.0
8,f7622098214b4634b7fe7eee269b5426,campo novo do parecis,MT,1,19457.04,19457.04,3.0
9,71901689c5f3e5adc27b1dd16b33f0b8,sao luis,MA,1,19174.38,19174.38,1.0
10,cb87122c4871e202777cf243fbea2d12,guapore,RS,1,18667.00,18667.00,1.0
11,10de381f8a8d23fff822753305f71cae,uniao da vitoria,PR,1,18384.75,18384.75,5.0
12,91f92cfee46b79581b05aa974dd57ce5,curitiba,PR,1,17786.88,17786.88,1.0
13,4a60b2ce1ee8c7b828e4bbcca5b86b41,diadema,SP,1,17671.00,17671.00,1.0
14,ed583a2a1eaf0dedc33af816153e8b8c,campina grande,PB,1,17069.76,17069.76,5.0
15,0c792d32a3251b4f69dae8646dfbedbc,rio de janeiro,RJ,1,16313.60,16313.60,4.0
16,daf15f1b940cc6a72ba558f093dc00dd,celso ramos,SC,1,14963.64,14963.64,4.0
17,88324c93ce11436ae046563bf0da285c,rio verde,GO,1,14577.57,14577.57,1.0
18,78fc46047c4a639e81ff65f0396e02fe,jaguariuna,SP,1,14401.00,14401.00,1.0
19,d5f2b3f597c7ccafbb5cac0bcc3d6024,santos,SP,1,14196.28,14196.28,1.0
20,03a6f3a3935165f5d26f4797ba6039bb,sao paulo,SP,1,12834.50,12834.50,2.0
21,6152fbfc8a92ee25fd821740bd33b089,salvador,BA,1,12490.88,12490.88,5.0
22,e2f063c52fa92b54f186c62b90699c10,morro agudo,SP,1,12300.00,12300.00,1.0
23,5c51fe11e0c3a016201653955c6090ee,sao jose do rio preto,SP,1,11832.18,11832.18,2.0
24,adb32467ecc74b53576d9d13a5a55891,goiania,GO,1,11745.00,11745.00,5.0
25,e91409937a0fd26a57310548858d1762,porto alegre,RS,1,11697.12,11697.12,1.0
26,0d861a5e4dd6a9079d89e1330848f0ab,ipua,SP,1,11572.80,11572.80,3.0
27,f4c13379ddd0ed4f4fc1c0b49c2c5e51,alto paraiso de goias,GO,1,11531.41,11531.41,3.0
28,159132ab31eb3c8a1061ed18967f720b,valinhos,SP,1,11468.45,11468.45,1.0
29,a1a52dda6ac52aee936ad06712027b83,itapetininga,SP,1,11380.50,11380.50,1.0
30,7d03bf20fa96e80468bbf678eebbcb3f,gaspar,SC,1,10999.26,10999.26,5.0
31,068830daf2867cadbfc655e6a413388e,sao paulo,SP,1,9759.75,9759.75,5.0
32,727ab4449f530b9af13f40fa8e528bff,paranagua,PR,1,9751.00,9751.00,2.0
33,e0a2412720e9ea4f26c1ac985f6a7358,goiania,GO,1,9618.88,9618.88,1.0
34,2a1f6d64684615ad73ce7d05586115ed,sao paulo,SP,1,9618.48,9618.48,5.0
35,c455144b0c6e78f2574b7a92f22342cf,mogi das cruzes,SP,1,9443.35,9443.35,4.0
36,be1c4e52bb71e0c54b11a26b8e8d59f2,sao paulo,SP,1,9393.45,9393.45,1.0
37,368f207cdc8f5c93a2b2a5d4cce96ba8,japeri,RJ,1,9212.98,9212.98,2.0
38,cc803a2c412833101651d3f90ca7de24,niteroi,RJ,1,8891.00,8891.00,5.0
39,5c9d09439a7815d2c59d2242d90b296c,fortaleza,CE,1,8780.50,8780.50,4.0
40,30bb84b541c96af98ba7d90b9ebf35d0,montes claros,MG,1,8697.99,8697.99,5.0
41,5e312b0d9bf5c91599eb42120e633b19,castro,PR,1,8530.14,8530.14,1.0
42,b0f06b1979dedd3f28f8f0d5e4ad08fb,sao paulo,SP,1,8511.75,8511.75,5.0
43,222e4c4d91c814cafc5badfe6a02c574,colombo,PR,1,8425.44,8425.44,4.0
44,935b0e35c27eff20b89b6dfe7753d31f,itabira,MG,1,8299.20,8299.20,5.0
45,dd3f1762eb601f41c5e289fa08dbc6bf,rio de janeiro,RJ,1,8108.64,8108.64,4.0
46,023cf83ac35d703a6f3c1b31bcf844d5,irece,BA,1,8057.88,8057.88,1.0
47,1dbc055ccab23ed894267767e268e8a1,divinopolis,MG,1,7956.20,7956.20,1.0
48,d6646ea91d8cd9fc7e6882a7068779d4,sao paulo,SP,1,7852.40,7852.40,5.0
49,0179f2f4c32e0b0c2a4cb0d57e7d5a26,rio de janeiro,RJ,1,7849.08,7849.08,2.0

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/customer_lifetime_value.csv


==========================================================================================
Delivery Performance
==========================================================================================

,Orders,LateOrders,OnTimeOrEarlyOrders,LateDeliveryPercent,AverageDeliveryDays,AverageShippingDays,AverageDeliveryDelay
0,99441,4154,92321,4.18,8.73,2.41,-14.71

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/delivery_performance.csv


==========================================================================================
Order Status Performance
==========================================================================================

   OrderStatus  Orders      Revenue  AverageDeliveryDays
0    delivered   96478  19776160.44                 8.73
1      shipped    1107    197150.14                  NaN
2     canceled     625    186964.32                11.57
3  unavailable     609    126671.70                  NaN
4     invoiced     314     82410.89                  NaN
5   processing     301    100378.37                  NaN
6      created       5       688.10                  NaN
7     approved       2       302.70                  NaN

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/order_status_performance.csv


==========================================================================================
Review Analysis
==========================================================================================

    ReviewScore  Orders  AverageOrderValue  AverageDeliveryDays
0      5.000000   56955             167.84                 7.28
1      4.500000      54             187.53                 8.79
2      4.333333       1              42.77                 1.00
3      4.000000   19018             170.97                 8.49
4      3.500000      25             153.63                 8.10
5      3.333333       1              42.11                20.00
6      3.000000    8136             175.49                 9.94
7      2.500000      34             146.64                10.88
8      2.000000    3125             202.65                11.34
9      1.500000       8             271.49                12.06
10     1.000000   11316             242.03                14.50

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/review_analysis.csv


==========================================================================================
Review Sentiment
==========================================================================================

,ReviewSentiment,Orders,Revenue,AverageReviewScore,AverageDeliveryDays
0,Positive,76028,14236809.38,4.75,7.59
1,Neutral,8136,1656131.39,3.00,9.94
2,Negative,14449,4331273.44,1.21,13.78
3,No Review,828,246512.45,2.91,13.16

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/review_sentiment.csv


==========================================================================================
State Performance
==========================================================================================

,CustomerState,Orders,Customers,Revenue,AverageReview,AverageDeliveryDays
0,SP,41746,41746,7673188.55,4.11,5.06
1,RJ,12852,12852,2783724.26,3.80,11.32
2,MG,11635,11635,2341861.47,4.07,8.26
3,RS,5466,5466,1152019.17,4.04,11.44
4,PR,5045,5045,1074614.19,4.09,8.16
5,BA,3380,3380,802416.72,3.80,15.40
6,SC,3637,3637,799135.92,3.99,11.11
7,GO,2020,2020,516182.51,3.98,11.84
8,DF,2140,2140,434512.55,4.00,9.22
9,ES,2033,2033,406946.26,3.98,11.75
10,PE,1652,1652,378887.48,3.95,14.50
11,CE,1336,1336,347678.36,3.80,17.16
12,PA,975,975,262433.11,3.78,19.84
13,MT,907,907,257447.65,3.97,14.34
14,MA,747,747,199913.56,3.69,17.34
15,PB,536,536,181546.00,3.99,16.46
16,MS,715,715,165861.46,4.02,11.88
17,PI,495,495,137077.67,3.89,15.70
18,RN,485,485,117074.43,4.07,15.22
19,AL,413,413,111993.78,3.72,20.36
20,SE,350,350,90651.44,3.81,17.34
21,TO,280,280,72412.08,4.10,13.56
22,RO,253,253,69184.48,3.96,16.45
23,AM,148,148,34873.79,4.08,23.07
24,AC,81,81,24984.86,4.10,16.91
25,AP,68,68,21642.70,4.22,24.14
26,RR,46,46,12462.21,3.58,24.15

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/state_performance.csv


==========================================================================================
Local vs Non Local Orders
==========================================================================================

   OrderType  Orders      Revenue  AverageDeliveryDays  AverageFreight
0  Non-Local   64088  14264847.09                11.25           23.69
1      Local   35600   6205879.57                 4.29           13.46

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/local_vs_non_local_orders.csv


==========================================================================================
Profitability Analysis
==========================================================================================

       Revenue  ProfitProxy  AverageProfitProxy  ProfitMarginPercent
0  20470726.66  11339734.16              100.66                55.39

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/profitability_analysis.csv


==========================================================================================
Payment Analysis
==========================================================================================

,PaymentMethod,Orders,Revenue,AverageInstallments,AveragePaymentCount
0,credit_card,74259,15520455.62,3.67,1.37
1,boleto,19784,4086820.71,1.00,1.50
2,"credit_card,voucher",2245,400382.82,2.30,1.28
3,debit_card,1527,256367.92,1.00,1.31
4,voucher,1621,206546.77,1.00,1.16
5,"credit_card,debit_card",1,152.82,3.00,1.00
6,not_defined,3,0.00,1.00,1.00
7,None,1,NaN,NaN,3.00

Saved: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results/payment_analysis.csv


==========================================================================================
PHASE 7 SQL ANALYTICS COMPLETED
==========================================================================================
Database: /content/drive/MyDrive/InsightFlow_AI/warehouse.db
Reports: /content/drive/MyDrive/InsightFlow_AI/reports/sql_results

CSV reports generated successfully.
SQLite connection closed.
==========================================================================================

Business Intelligence

In [ ]:
# ============================================================
# PHASE 8
# BUSINESS INTELLIGENCE & AUTOMATED INSIGHT ENGINE
# ============================================================

import os
import sqlite3
import pandas as pd
import numpy as np

# ============================================================
# CONFIGURATION
# ============================================================

BASE = "/content/drive/MyDrive/InsightFlow_AI"

DB_PATH = os.path.join(
    BASE,
    "warehouse.db"
)

PHASE8_PATH = os.path.join(
    BASE,
    "reports",
    "phase8_business_intelligence"
)

os.makedirs(
    PHASE8_PATH,
    exist_ok=True
)

print("=" * 90)
print("INSIGHTFLOW AI")
print("PHASE 8 — BUSINESS INTELLIGENCE & INSIGHT ENGINE")
print("=" * 90)

# ============================================================
# CONNECT TO SQLITE
# ============================================================

conn = sqlite3.connect(DB_PATH)

print("\nSQLite Connected Successfully!")

# ============================================================
# VERIFY DATABASE
# ============================================================

required_tables = [
    "fact_sales",
    "dim_customers",
    "dim_products",
    "dim_sellers",
    "dim_reviews",
    "dim_payments",
    "dim_locations",
    "dim_status",
    "dim_date"
]

existing_tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    """,
    conn
)["name"].tolist()

missing_tables = [
    table
    for table in required_tables
    if table not in existing_tables
]

if missing_tables:

    conn.close()

    raise Exception(
        "Missing required tables: "
        + ", ".join(missing_tables)
    )

print("All required warehouse tables found.")

# ============================================================
# HELPER
# ============================================================

def save_output(df, filename):

    csv_path = os.path.join(
        PHASE8_PATH,
        filename + ".csv"
    )

    parquet_path = os.path.join(
        PHASE8_PATH,
        filename + ".parquet"
    )

    df.to_csv(
        csv_path,
        index=False
    )

    df.to_parquet(
        parquet_path,
        index=False
    )

    return csv_path


def run_phase8_query(
    title,
    query,
    filename
):

    print("\n")
    print("=" * 90)
    print(title)
    print("=" * 90)

    result = pd.read_sql_query(
        query,
        conn
    )

    display(result)

    save_output(
        result,
        filename
    )

    print(
        f"Saved → {filename}.csv"
    )

    return result


# ============================================================
# 8.1 EXECUTIVE KPI SCORECARD
# ============================================================

executive_kpis = run_phase8_query(

    "8.1 EXECUTIVE KPI SCORECARD",

    """

    SELECT

        COUNT(DISTINCT order_id)
            AS TotalOrders,

        COUNT(DISTINCT customer_key)
            AS TotalCustomers,

        COUNT(DISTINCT product_key)
            AS TotalProducts,

        COUNT(DISTINCT seller_key)
            AS TotalSellers,

        ROUND(
            SUM(total_payment),
            2
        ) AS TotalRevenue,

        ROUND(
            SUM(total_payment)
            /
            NULLIF(
                COUNT(DISTINCT order_id),
                0
            ),
            2
        ) AS AverageOrderValue,

        ROUND(
            AVG(basket_size),
            2
        ) AS AverageBasketSize,

        ROUND(
            AVG(review_score),
            2
        ) AS AverageReviewScore,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            AVG(shipping_days),
            2
        ) AS AverageShippingDays,

        ROUND(
            SUM(
                CASE
                    WHEN delivery_delay_days > 0
                    THEN 1
                    ELSE 0
                END
            ) * 100.0
            /
            NULLIF(COUNT(*),0),
            2
        ) AS LateDeliveryRate,

        ROUND(
            SUM(profit_proxy),
            2
        ) AS ProfitProxy,

        ROUND(
            SUM(profit_proxy) * 100.0
            /
            NULLIF(
                SUM(total_payment),
                0
            ),
            2
        ) AS ProfitMarginPercent

    FROM fact_sales

    """,

    "executive_kpis"

)


# ============================================================
# 8.2 MONTHLY BUSINESS PERFORMANCE
# ============================================================

monthly_business = run_phase8_query(

    "8.2 MONTHLY BUSINESS PERFORMANCE",

    """

    WITH monthly AS (

        SELECT

            d.purchase_year AS Year,

            d.purchase_month AS Month,

            SUM(f.total_payment)
                AS Revenue,

            COUNT(
                DISTINCT f.order_id
            ) AS Orders,

            COUNT(
                DISTINCT f.customer_key
            ) AS Customers,

            SUM(f.profit_proxy)
                AS ProfitProxy

        FROM fact_sales f

        INNER JOIN dim_date d

            ON f.date_key = d.date_key

        GROUP BY

            d.purchase_year,

            d.purchase_month

    )

    SELECT

        Year,

        Month,

        ROUND(
            Revenue,
            2
        ) AS Revenue,

        Orders,

        Customers,

        ROUND(
            Revenue
            /
            NULLIF(Orders,0),
            2
        ) AS AverageOrderValue,

        ROUND(
            ProfitProxy,
            2
        ) AS ProfitProxy,

        ROUND(
            ProfitProxy * 100.0
            /
            NULLIF(Revenue,0),
            2
        ) AS ProfitMarginPercent,

        ROUND(

            (
                Revenue
                -
                LAG(Revenue)
                OVER (
                    ORDER BY Year, Month
                )

            ) * 100.0

            /

            NULLIF(

                LAG(Revenue)
                OVER (
                    ORDER BY Year, Month
                ),

                0

            ),

            2

        ) AS RevenueGrowthPercent

    FROM monthly

    ORDER BY

        Year,

        Month

    """,

    "monthly_business_performance"

)


# ============================================================
# 8.3 PRODUCT INTELLIGENCE
# ============================================================

product_intelligence = run_phase8_query(

    "8.3 PRODUCT INTELLIGENCE",

    """

    SELECT

        p.product_id,

        p.product_category,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        SUM(
            f.order_item_id
        ) AS Quantity,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            SUM(f.profit_proxy),
            2
        ) AS ProfitProxy,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.price),
            2
        ) AS AveragePrice,

        ROUND(
            SUM(f.profit_proxy) * 100.0
            /
            NULLIF(
                SUM(f.total_payment),
                0
            ),
            2
        ) AS ProfitMarginPercent

    FROM fact_sales f

    INNER JOIN dim_products p

        ON f.product_key = p.product_key

    WHERE

        p.product_id != 'UNKNOWN'

    GROUP BY

        p.product_id,

        p.product_category

    ORDER BY

        Revenue DESC

    """,

    "product_intelligence"

)


# ============================================================
# 8.4 PRODUCT CATEGORY INTELLIGENCE
# ============================================================

category_intelligence = run_phase8_query(

    "8.4 PRODUCT CATEGORY INTELLIGENCE",

    """

    SELECT

        p.product_category,

        COUNT(
            DISTINCT p.product_id
        ) AS Products,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            SUM(f.profit_proxy),
            2
        ) AS ProfitProxy,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            SUM(f.profit_proxy) * 100.0
            /
            NULLIF(
                SUM(f.total_payment),
                0
            ),
            2
        ) AS ProfitMarginPercent

    FROM fact_sales f

    INNER JOIN dim_products p

        ON f.product_key = p.product_key

    WHERE

        p.product_category IS NOT NULL

        AND p.product_category != 'Unknown'

    GROUP BY

        p.product_category

    ORDER BY

        Revenue DESC

    """,

    "category_intelligence"

)


# ============================================================
# 8.5 CUSTOMER INTELLIGENCE
# ============================================================

customer_intelligence = run_phase8_query(

    "8.5 CUSTOMER INTELLIGENCE",

    """

    SELECT

        customer_key,

        COUNT(
            DISTINCT order_id
        ) AS Orders,

        ROUND(
            SUM(total_payment),
            2
        ) AS LifetimeValue,

        ROUND(
            SUM(total_payment)
            /
            NULLIF(
                COUNT(DISTINCT order_id),
                0
            ),
            2
        ) AS AverageOrderValue,

        ROUND(
            AVG(review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays,

        CASE

            WHEN COUNT(
                DISTINCT order_id
            ) >= 5

            AND SUM(total_payment) >= 1000

                THEN 'VIP'

            WHEN COUNT(
                DISTINCT order_id
            ) >= 3

                THEN 'High Value'

            WHEN COUNT(
                DISTINCT order_id
            ) = 2

                THEN 'Regular'

            ELSE 'One Time'

        END AS CustomerSegment

    FROM fact_sales

    WHERE

        customer_key != 0

    GROUP BY

        customer_key

    ORDER BY

        LifetimeValue DESC

    """,

    "customer_intelligence"

)


# ============================================================
# 8.6 CUSTOMER SEGMENT SUMMARY
# ============================================================

customer_segments = run_phase8_query(

    "8.6 CUSTOMER SEGMENT SUMMARY",

    """

    WITH customers AS (

        SELECT

            customer_key,

            COUNT(
                DISTINCT order_id
            ) AS Orders,

            SUM(total_payment)
                AS LifetimeValue

        FROM fact_sales

        WHERE customer_key != 0

        GROUP BY customer_key

    )

    SELECT

        CASE

            WHEN Orders >= 5
            AND LifetimeValue >= 1000
                THEN 'VIP'

            WHEN Orders >= 3
                THEN 'High Value'

            WHEN Orders = 2
                THEN 'Regular'

            ELSE 'One Time'

        END AS CustomerSegment,

        COUNT(*) AS Customers,

        ROUND(
            SUM(LifetimeValue),
            2
        ) AS Revenue,

        ROUND(
            AVG(LifetimeValue),
            2
        ) AS AverageCustomerValue

    FROM customers

    GROUP BY

        CASE

            WHEN Orders >= 5
            AND LifetimeValue >= 1000
                THEN 'VIP'

            WHEN Orders >= 3
                THEN 'High Value'

            WHEN Orders = 2
                THEN 'Regular'

            ELSE 'One Time'

        END

    ORDER BY

        Revenue DESC

    """,

    "customer_segment_summary"

)


# ============================================================
# 8.7 SELLER INTELLIGENCE
# ============================================================

seller_intelligence = run_phase8_query(

    "8.7 SELLER INTELLIGENCE",

    """

    SELECT

        s.seller_id,

        s.seller_state,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            SUM(f.profit_proxy),
            2
        ) AS ProfitProxy,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            SUM(f.profit_proxy) * 100.0
            /
            NULLIF(
                SUM(f.total_payment),
                0
            ),
            2
        ) AS ProfitMarginPercent

    FROM fact_sales f

    INNER JOIN dim_sellers s

        ON f.seller_key = s.seller_key

    WHERE

        s.seller_id != 'UNKNOWN'

    GROUP BY

        s.seller_id,

        s.seller_state

    ORDER BY

        Revenue DESC

    """,

    "seller_intelligence"

)


# ============================================================
# 8.8 SELLER PERFORMANCE MATRIX
# ============================================================

seller_performance = run_phase8_query(

    "8.8 SELLER PERFORMANCE MATRIX",

    """

    WITH seller_metrics AS (

        SELECT

            s.seller_id,

            COUNT(
                DISTINCT f.order_id
            ) AS Orders,

            SUM(
                f.total_payment
            ) AS Revenue,

            AVG(
                f.review_score
            ) AS ReviewScore,

            AVG(
                f.delivery_days
            ) AS DeliveryDays

        FROM fact_sales f

        INNER JOIN dim_sellers s

            ON f.seller_key =
               s.seller_key

        WHERE

            s.seller_id != 'UNKNOWN'

        GROUP BY

            s.seller_id

    ),

    thresholds AS (

        SELECT

            AVG(Revenue)
                AS AvgRevenue,

            AVG(ReviewScore)
                AS AvgReview

        FROM seller_metrics

    )

    SELECT

        s.seller_id,

        s.Orders,

        ROUND(
            s.Revenue,
            2
        ) AS Revenue,

        ROUND(
            s.ReviewScore,
            2
        ) AS ReviewScore,

        ROUND(
            s.DeliveryDays,
            2
        ) AS DeliveryDays,

        CASE

            WHEN s.Revenue >= t.AvgRevenue
            AND s.ReviewScore >= t.AvgReview

                THEN 'High Performer'

            WHEN s.Revenue >= t.AvgRevenue
            AND s.ReviewScore < t.AvgReview

                THEN 'Revenue Leader - Review Risk'

            WHEN s.Revenue < t.AvgRevenue
            AND s.ReviewScore >= t.AvgReview

                THEN 'Quality Opportunity'

            ELSE 'Needs Improvement'

        END AS SellerSegment

    FROM seller_metrics s

    CROSS JOIN thresholds t

    ORDER BY

        Revenue DESC

    """,

    "seller_performance_matrix"

)


# ============================================================
# 8.9 DELIVERY INTELLIGENCE
# ============================================================

delivery_intelligence = run_phase8_query(

    "8.9 DELIVERY INTELLIGENCE",

    """

    SELECT

        CASE

            WHEN delivery_delay_days > 0
                THEN 'Late'

            ELSE 'On Time'

        END AS DeliveryStatus,

        COUNT(*) AS Orders,

        ROUND(
            COUNT(*) * 100.0
            /
            NULLIF(
                (
                    SELECT COUNT(*)
                    FROM fact_sales
                ),
                0
            ),
            2
        ) AS OrderSharePercent,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            AVG(shipping_days),
            2
        ) AS AverageShippingDays,

        ROUND(
            AVG(delivery_delay_days),
            2
        ) AS AverageDelayDays,

        ROUND(
            AVG(review_score),
            2
        ) AS AverageReview

    FROM fact_sales

    GROUP BY

        CASE

            WHEN delivery_delay_days > 0
                THEN 'Late'

            ELSE 'On Time'

        END

    """,

    "delivery_intelligence"

)


# ============================================================
# 8.10 GEOGRAPHIC INTELLIGENCE
# ============================================================

geographic_intelligence = run_phase8_query(

    "8.10 GEOGRAPHIC INTELLIGENCE",

    """

    SELECT

        l.customer_state AS State,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        COUNT(
            DISTINCT f.customer_key
        ) AS Customers,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            SUM(f.profit_proxy),
            2
        ) AS ProfitProxy,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            SUM(
                CASE
                    WHEN f.delivery_delay_days > 0
                    THEN 1
                    ELSE 0
                END
            ) * 100.0
            /
            NULLIF(COUNT(*),0),
            2
        ) AS LateDeliveryRate

    FROM fact_sales f

    INNER JOIN dim_locations l

        ON f.location_key =
           l.location_key

    GROUP BY

        l.customer_state

    ORDER BY

        Revenue DESC

    """,

    "geographic_intelligence"

)


# ============================================================
# 8.11 LOCAL VS NON-LOCAL
# ============================================================

local_delivery_analysis = run_phase8_query(

    "8.11 LOCAL VS NON-LOCAL DELIVERY",

    """

    SELECT

        CASE

            WHEN l.local_order = 1
                THEN 'Local'

            ELSE 'Non-Local'

        END AS OrderType,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(f.delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            AVG(f.shipping_days),
            2
        ) AS AverageShippingDays,

        ROUND(
            AVG(f.review_score),
            2
        ) AS AverageReview,

        ROUND(
            SUM(
                CASE
                    WHEN f.delivery_delay_days > 0
                    THEN 1
                    ELSE 0
                END
            ) * 100.0
            /
            NULLIF(COUNT(*),0),
            2
        ) AS LateDeliveryRate

    FROM fact_sales f

    INNER JOIN dim_locations l

        ON f.location_key =
           l.location_key

    GROUP BY

        l.local_order

    ORDER BY

        AverageDeliveryDays

    """,

    "local_vs_nonlocal_delivery"

)


# ============================================================
# 8.12 PAYMENT INTELLIGENCE
# ============================================================

payment_intelligence = run_phase8_query(

    "8.12 PAYMENT INTELLIGENCE",

    """

    SELECT

        p.payment_methods AS PaymentMethod,

        COUNT(
            DISTINCT f.order_id
        ) AS Orders,

        ROUND(
            SUM(f.total_payment),
            2
        ) AS Revenue,

        ROUND(
            SUM(f.total_payment)
            /
            NULLIF(
                COUNT(DISTINCT f.order_id),
                0
            ),
            2
        ) AS AverageOrderValue,

        ROUND(
            AVG(
                p.payment_installments
            ),
            2
        ) AS AverageInstallments,

        ROUND(
            AVG(
                p.payment_count
            ),
            2
        ) AS AveragePaymentCount

    FROM fact_sales f

    INNER JOIN dim_payments p

        ON f.payment_key =
           p.payment_key

    GROUP BY

        p.payment_methods

    ORDER BY

        Revenue DESC

    """,

    "payment_intelligence"

)


# ============================================================
# 8.13 REVIEW / CUSTOMER EXPERIENCE
# ============================================================

review_intelligence = run_phase8_query(

    "8.13 REVIEW & CUSTOMER EXPERIENCE",

    """

    SELECT

        CASE

            WHEN review_score >= 4
                THEN 'Positive'

            WHEN review_score = 3
                THEN 'Neutral'

            WHEN review_score <= 2
                THEN 'Negative'

            ELSE 'No Review'

        END AS ReviewSentiment,

        COUNT(
            DISTINCT order_id
        ) AS Orders,

        ROUND(
            SUM(total_payment),
            2
        ) AS Revenue,

        ROUND(
            AVG(delivery_days),
            2
        ) AS AverageDeliveryDays,

        ROUND(
            AVG(delivery_delay_days),
            2
        ) AS AverageDelayDays

    FROM fact_sales

    GROUP BY

        CASE

            WHEN review_score >= 4
                THEN 'Positive'

            WHEN review_score = 3
                THEN 'Neutral'

            WHEN review_score <= 2
                THEN 'Negative'

            ELSE 'No Review'

        END

    ORDER BY

        Revenue DESC

    """,

    "review_customer_experience"

)


# ============================================================
# 8.14 AUTOMATED BUSINESS INSIGHTS
# ============================================================

print("\n")
print("=" * 90)
print("8.14 AUTOMATED BUSINESS INSIGHT GENERATION")
print("=" * 90)

insights = []


# ------------------------------------------------------------
# Executive KPI insights
# ------------------------------------------------------------

kpi = executive_kpis.iloc[0]

total_revenue = float(
    kpi["TotalRevenue"]
)

total_orders = int(
    kpi["TotalOrders"]
)

aov = float(
    kpi["AverageOrderValue"]
)

late_rate = float(
    kpi["LateDeliveryRate"]
)

profit_margin = float(
    kpi["ProfitMarginPercent"]
)

insights.append({

    "InsightType":
        "Executive",

    "Priority":
        "High",

    "Metric":
        "Revenue",

    "Insight":
        f"Total revenue is {total_revenue:,.2f} "
        f"across {total_orders:,} orders.",

    "Recommendation":
        "Use revenue and order trends as the primary "
        "executive performance indicators."

})


insights.append({

    "InsightType":
        "Executive",

    "Priority":
        "High",

    "Metric":
        "Average Order Value",

    "Insight":
        f"Average order value is {aov:,.2f}.",

    "Recommendation":
        "Increase basket size through cross-selling, "
        "bundling and personalized recommendations."

})


insights.append({

    "InsightType":
        "Operations",

    "Priority":
        "High" if late_rate >= 5 else "Medium",

    "Metric":
        "Late Delivery Rate",

    "Insight":
        f"Late delivery rate is {late_rate:.2f}%.",

    "Recommendation":
        "Investigate logistics, seller processing time "
        "and destination-level delivery bottlenecks."

})


insights.append({

    "InsightType":
        "Profitability",

    "Priority":
        "High",

    "Metric":
        "Profit Margin",

    "Insight":
        f"Current profit proxy margin is "
        f"{profit_margin:.2f}%.",

    "Recommendation":
        "Monitor pricing, freight cost and product mix "
        "to protect contribution margins."

})


# ------------------------------------------------------------
# Monthly trend insight
# ------------------------------------------------------------

if len(monthly_business) >= 2:

    latest = monthly_business.iloc[-1]

    previous = monthly_business.iloc[-2]

    growth = latest["RevenueGrowthPercent"]

    if pd.notna(growth):

        direction = (
            "increased"
            if growth >= 0
            else "decreased"
        )

        insights.append({

            "InsightType":
                "Revenue Trend",

            "Priority":
                "High",

            "Metric":
                "Monthly Revenue Growth",

            "Insight":
                f"Revenue {direction} by "
                f"{abs(growth):.2f}% "
                f"from the previous month.",

            "Recommendation":
                "Investigate the drivers of the latest "
                "monthly revenue movement."

        })


# ------------------------------------------------------------
# Product insight
# ------------------------------------------------------------

if len(category_intelligence) > 0:

    top_category = (
        category_intelligence
        .iloc[0]
    )

    insights.append({

        "InsightType":
            "Product",

        "Priority":
            "High",

        "Metric":
            "Top Category",

        "Insight":
            f"{top_category['product_category']} "
            f"is the highest-revenue product category "
            f"with revenue of "
            f"{top_category['Revenue']:,.2f}.",

        "Recommendation":
            "Protect inventory availability and analyze "
            "cross-selling opportunities around this category."

    })


# ------------------------------------------------------------
# Seller insight
# ------------------------------------------------------------

if len(seller_performance) > 0:

    high_performers = seller_performance[
        seller_performance["SellerSegment"]
        == "High Performer"
    ]

    insights.append({

        "InsightType":
            "Seller",

        "Priority":
            "Medium",

        "Metric":
            "High Performing Sellers",

        "Insight":
            f"{len(high_performers):,} sellers "
            f"are classified as High Performers.",

        "Recommendation":
            "Study high-performing seller practices "
            "and replicate them across weaker sellers."

    })


# ------------------------------------------------------------
# Customer insight
# ------------------------------------------------------------

if len(customer_segments) > 0:

    vip = customer_segments[
        customer_segments["CustomerSegment"]
        == "VIP"
    ]

    if len(vip) > 0:

        vip_customers = int(
            vip.iloc[0]["Customers"]
        )

        vip_revenue = float(
            vip.iloc[0]["Revenue"]
        )

        insights.append({

            "InsightType":
                "Customer",

            "Priority":
                "High",

            "Metric":
                "VIP Customers",

            "Insight":
                f"{vip_customers:,} customers "
                f"are classified as VIP and generate "
                f"{vip_revenue:,.2f} in revenue.",

            "Recommendation":
                "Use retention campaigns and personalized "
                "offers to protect high-value customers."

        })


# ------------------------------------------------------------
# Delivery insight
# ------------------------------------------------------------

if len(local_delivery_analysis) >= 2:

    local_row = local_delivery_analysis[
        local_delivery_analysis["OrderType"]
        == "Local"
    ]

    nonlocal_row = local_delivery_analysis[
        local_delivery_analysis["OrderType"]
        == "Non-Local"
    ]

    if (
        len(local_row) > 0
        and len(nonlocal_row) > 0
    ):

        local_days = float(
            local_row.iloc[0][
                "AverageDeliveryDays"
            ]
        )

        nonlocal_days = float(
            nonlocal_row.iloc[0][
                "AverageDeliveryDays"
            ]
        )

        if local_days > 0:

            ratio = (
                nonlocal_days
                /
                local_days
            )

            insights.append({

                "InsightType":
                    "Logistics",

                "Priority":
                    "High",

                "Metric":
                    "Local vs Non-Local",

                "Insight":
                    f"Non-local orders take approximately "
                    f"{ratio:.2f}× the delivery time of "
                    f"local orders.",

                "Recommendation":
                    "Optimize inter-state logistics, "
                    "carrier allocation and fulfillment routing."

            })


# ------------------------------------------------------------
# Payment insight
# ------------------------------------------------------------

if len(payment_intelligence) > 0:

    top_payment = (
        payment_intelligence
        .iloc[0]
    )

    insights.append({

        "InsightType":
            "Payments",

        "Priority":
            "Medium",

        "Metric":
            "Top Payment Method",

        "Insight":
            f"{top_payment['PaymentMethod']} "
            f"generates the highest revenue at "
            f"{top_payment['Revenue']:,.2f}.",

        "Recommendation":
            "Prioritize reliability and conversion "
            "optimization for the dominant payment method."

    })


# ============================================================
# SAVE BUSINESS INSIGHTS
# ============================================================

business_insights = pd.DataFrame(
    insights
)

display(
    business_insights
)

save_output(
    business_insights,
    "business_insights"
)


# ============================================================
# 8.15 CREATE PHASE 8 MASTER SUMMARY
# ============================================================

phase8_summary = pd.DataFrame({

    "Component": [

        "Executive KPI",

        "Monthly Business Performance",

        "Product Intelligence",

        "Category Intelligence",

        "Customer Intelligence",

        "Customer Segmentation",

        "Seller Intelligence",

        "Seller Performance Matrix",

        "Delivery Intelligence",

        "Geographic Intelligence",

        "Local vs Non-Local",

        "Payment Intelligence",

        "Review Intelligence",

        "Automated Business Insights"

    ],

    "Status": [

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed",

        "Completed"

    ]

})

display(
    phase8_summary
)

save_output(
    phase8_summary,
    "phase8_summary"
)


# ============================================================
# 8.16 FINAL OUTPUT
# ============================================================

print("\n")
print("=" * 90)
print("PHASE 8 COMPLETED SUCCESSFULLY")
print("=" * 90)

print("\nOutput Directory:")
print(PHASE8_PATH)

print("\nFiles Generated:")

for file in sorted(
    os.listdir(PHASE8_PATH)
):

    print("✓", file)

print("\n")
print("=" * 90)
print("BUSINESS INTELLIGENCE LAYER READY")
print("=" * 90)

# ============================================================
# CLOSE CONNECTION
# ============================================================

conn.close()

print("\nSQLite connection closed.")
print("InsightFlow AI Phase 8 is ready for Phase 9.")

==========================================================================================
INSIGHTFLOW AI
PHASE 8 — BUSINESS INTELLIGENCE & INSIGHT ENGINE
==========================================================================================

SQLite Connected Successfully!
All required warehouse tables found.


==========================================================================================
8.1 EXECUTIVE KPI SCORECARD
==========================================================================================

,TotalOrders,TotalCustomers,TotalProducts,TotalSellers,TotalRevenue,AverageOrderValue,AverageBasketSize,AverageReviewScore,AverageDeliveryDays,AverageShippingDays,LateDeliveryRate,ProfitProxy,ProfitMarginPercent
0,99441,99441,32952,3096,20470726.66,205.86,1.39,4.02,8.73,2.41,4.0,11339734.16,55.39

Saved → executive_kpis.csv


==========================================================================================
8.2 MONTHLY BUSINESS PERFORMANCE
==========================================================================================

,Year,Month,Revenue,Orders,Customers,AverageOrderValue,ProfitProxy,ProfitMarginPercent,RevenueGrowthPercent
0,2016,December,19.62,1,1,19.62,2.18,11.11,NaN
1,2016,October,76120.17,324,324,234.94,42206.48,55.45,387872.32
2,2016,September,388.47,4,4,97.12,179.97,46.33,-99.49
3,2017,April,510891.55,2404,2404,212.52,307432.22,60.18,131413.77
4,2017,August,876129.37,4331,4331,202.29,479738.76,54.76,71.49
5,2017,December,1057582.34,5673,5673,186.42,624281.11,59.03,20.71
6,2017,February,349701.93,1780,1780,196.46,208325.42,59.57,-66.93
7,2017,January,189015.66,800,800,236.27,103437.25,54.72,-45.95
8,2017,July,744599.53,4026,4026,184.95,411091.34,55.21,293.94
9,2017,June,608891.38,3245,3245,187.64,363114.16,59.64,-18.23
10,2017,March,544738.23,2682,2682,203.11,316640.01,58.13,-10.54
11,2017,May,731017.09,3700,3700,197.57,425951.33,58.27,34.20
12,2017,November,1599444.18,7544,7544,212.02,841398.97,52.61,118.80
13,2017,October,1031505.53,4631,4631,222.74,559126.49,54.20,-35.51
14,2017,September,1023095.49,4285,4285,238.76,528404.47,51.65,-0.82
15,2018,April,1497843.94,6939,6939,215.86,833597.46,55.65,46.40
16,2018,August,1248837.93,6512,6512,191.77,706064.19,56.54,-16.62
17,2018,February,1311260.71,6728,6728,194.90,701448.46,53.49,5.00
18,2018,January,1415348.54,7269,7269,194.71,792758.83,56.01,7.94
19,2018,July,1359421.48,6292,6292,216.06,732286.41,53.87,-3.95
20,2018,June,1298685.81,6167,6167,210.59,707571.51,54.48,-4.47
21,2018,March,1480045.50,7211,7211,205.25,811300.06,54.82,13.96
22,2018,May,1511113.00,6873,6873,219.86,843253.54,55.80,2.10
23,2018,October,589.67,4,4,147.42,NaN,NaN,-99.96
24,2018,September,4439.54,16,16,277.47,123.54,2.78,652.89

Saved → monthly_business_performance.csv


==========================================================================================
8.3 PRODUCT INTELLIGENCE
==========================================================================================

,product_id,product_category,Orders,Quantity,Revenue,ProfitProxy,AverageReview,AveragePrice,ProfitMarginPercent
0,5769ef0a239114ac3a854af00df129e4,fixed_telephony,1,36.0,109312.64,13215.92,1.00,1680.00,12.09
1,bb50f2e236e5eea0100680137654686c,health_beauty,187,215.0,81887.42,60163.90,4.22,327.62,73.47
2,422879e10f46682990de24d770e7f83d,garden_tools,352,793.0,79512.22,18953.18,3.96,54.91,23.84
3,d1c427060a0f73f6b889a5c7c61f2ac4,computers_accessories,323,369.0,70557.90,33452.99,4.19,137.65,47.41
4,6cdd53843498f92890544667809f1595,health_beauty,151,164.0,64825.67,50366.41,4.32,350.83,77.70
...,...,...,...,...,...,...,...,...,...
32946,5304ff3fa35856a156e1170a6022d34d,art,1,1.0,12.22,-5.22,5.00,3.50,-42.72
32947,680cc8535be7cc69544238c1d6a83fe8,pet_shop,1,1.0,11.62,-5.82,5.00,2.90,-50.09
32948,0eeeb45e2f5911fd44282e5bb0c624ff,music,1,1.0,11.56,-3.86,5.00,3.85,-33.39
32949,310dc32058903b6416c71faff132df9e,stationery,1,1.0,10.07,-5.49,5.00,2.29,-54.52
32950,46fce52cef5caa7cc225a5531c946c8b,health_beauty,1,1.0,9.59,-5.19,5.00,2.20,-54.12

Saved → product_intelligence.csv


==========================================================================================
8.4 PRODUCT CATEGORY INTELLIGENCE
==========================================================================================

,product_category,Products,Orders,Revenue,ProfitProxy,AverageReview,AverageDeliveryDays,ProfitMarginPercent
0,bed_bath_table,3029,9417,1712553.67,832295.64,3.90,9.20,48.60
1,health_beauty,2444,8836,1657373.12,1076114.61,4.14,8.44,64.93
2,computers_accessories,1639,6689,1585330.45,764636.24,3.93,9.08,48.23
3,furniture_decor,2657,6449,1430176.39,557013.19,3.91,8.65,38.95
4,watches_gifts,1329,5624,1429216.68,1104469.75,4.02,9.35,77.28
5,sports_leisure,2867,7720,1392127.56,819441.46,4.11,8.89,58.86
6,housewares,2335,5884,1094758.13,486099.55,4.05,7.39,44.40
7,auto,1900,3897,852294.33,500055.90,4.06,8.88,58.67
8,garden_tools,753,3518,838280.75,386293.71,4.05,10.02,46.08
9,cool_stuff,789,3632,779698.00,551251.75,4.15,9.00,70.70
10,office_furniture,309,1273,646826.49,205388.75,3.49,9.50,31.75
11,toys,1411,3886,619037.69,406520.65,4.16,8.45,65.67
12,baby,919,2885,539845.66,343411.78,4.01,8.75,63.61
13,perfumery,868,3162,506738.66,344911.03,4.17,8.37,68.06
14,telephony,1134,4199,486882.05,252451.74,3.95,8.85,51.85
15,stationery,849,2311,317440.07,184144.75,4.20,9.18,58.01
16,pet_shop,719,1710,311268.97,174754.17,4.18,7.57,56.14
17,computers,30,181,279121.55,213126.83,4.18,9.52,76.36
18,electronics,517,2550,259857.10,113668.42,4.04,9.68,43.74
19,construction_tools_construction,400,748,241475.63,124027.18,4.05,7.81,51.36
20,musical_instruments,289,628,233074.12,172860.39,4.15,9.12,74.17
21,small_appliances,231,630,225584.38,174628.33,4.15,7.68,77.41
22,fashion_bags_accessories,849,1864,218158.28,121373.54,4.15,8.04,55.64
23,fixed_telephony,116,217,207010.26,54945.19,3.68,8.32,26.54
24,consoles_games,317,1062,195480.38,137637.20,4.02,9.17,70.41
25,luggage_accessories,349,1034,187151.29,109984.75,4.32,8.20,58.77
26,home_construction,225,490,136645.29,69255.88,3.94,8.31,50.68
27,furniture_living_room,156,422,136138.77,50948.39,3.90,9.55,37.42
28,home_appliances_2,90,234,124563.46,102717.56,4.14,8.88,82.46
29,agro_industry_and_commerce,74,182,118730.61,66686.87,4.00,7.89,56.17
30,home_appliances,370,764,95532.27,65352.63,4.17,7.86,68.41
31,air_conditioning,124,253,91170.66,48275.73,3.97,7.61,52.95
32,home_confort,111,397,84329.06,50070.81,3.83,10.26,59.38
33,kitchen_dining_laundry_garden_furniture,94,248,74660.98,34328.94,3.97,7.63,45.98
34,construction_tools_lights,78,244,72712.48,33496.20,4.05,6.02,46.07
35,drinks,81,297,71429.65,16687.45,4.04,6.77,23.36
36,signaling_and_security,93,140,68488.05,15001.41,4.09,6.90,21.90
37,construction_tools_safety,91,167,65691.03,36625.42,3.84,7.93,55.75
38,books_general_interest,216,512,64694.76,37661.36,4.45,7.99,58.21
39,audio,58,350,60324.62,44978.06,3.83,9.91,74.56
40,industry_commerce_and_business,68,235,56745.76,31784.93,4.10,7.63,56.01
41,small_appliances_home_oven_and_coffee,31,75,51229.32,44697.85,4.30,6.78,87.25
42,food,82,450,46428.67,22122.38,4.22,7.23,47.65
43,market_place,104,280,45335.92,22922.41,4.02,7.75,50.56
44,costruction_tools_garden,88,194,42394.41,20404.49,4.05,8.25,48.13
45,fashion_shoes,173,240,32422.74,18643.90,4.24,9.33,57.50
46,furniture_bedroom,45,95,31598.94,15396.55,4.11,8.32,48.72
47,art,55,202,30992.93,20157.47,3.94,6.92,65.04
48,food_drink,104,227,27289.73,10671.49,4.31,7.60,39.10
49,books_technical,123,260,24915.44,14813.00,4.36,8.00,59.45
50,costruction_tools_tools,39,97,21069.07,13873.73,4.44,9.00,65.85
51,christmas_supplies,65,128,18994.77,5571.52,4.02,11.93,29.33
52,fashion_male_clothing,95,112,17290.98,8645.41,3.64,7.58,50.00
53,fashion_underwear_beach,53,121,12714.54,7625.36,3.98,8.98,59.97
54,tablets_printing_image,9,79,10042.93,6302.21,4.12,8.99,62.75
55,cine_photo,28,65,9530.32,5677.26,4.19,8.03,59.57
56,dvds_blu_ray,48,59,7935.28,4710.65,4.08,9.64,59.36
57,music,27,38,6901.43,5343.84,4.21,7.79,77.43
58,books_imported,31,53,6701.89,3870.00,4.40,4.88,57.74
59,furniture_mattress_and_upholstery,10,38,5998.54,2737.62,3.82,11.19,45.64
60,party_supplies,26,39,5966.31,3657.21,3.77,6.57,61.30
61,fashio_female_clothing,27,39,5109.62,2181.89,3.78,6.62,42.70
62,diapers_and_hygiene,12,27,4221.25,993.91,3.26,6.30,23.55
63,fashion_sport,19,27,3645.92,1541.38,4.23,8.97,42.28
64,la_cuisine,10,13,2913.53,1721.44,4.00,5.71,59.08
65,arts_and_craftmanship,19,23,2326.17,1443.88,4.13,3.13,62.07
66,flowers,14,29,2213.01,621.17,4.42,7.48,28.07
67,home_comfort_2,5,24,1710.54,349.96,3.63,11.70,20.46
68,cds_dvds_musicals,1,12,1199.43,505.01,4.64,7.57,42.10
69,fashion_childrens_clothes,5,8,785.67,474.34,4.50,6.43,60.37
70,security_and_services,2,2,324.51,242.07,2.50,13.00,74.60

Saved → category_intelligence.csv


==========================================================================================
8.5 CUSTOMER INTELLIGENCE
==========================================================================================

,customer_key,Orders,LifetimeValue,AverageOrderValue,AverageReview,AverageDeliveryDays,CustomerSegment
0,8547,1,109312.64,109312.64,1.0,7.0,One Time
1,73859,1,45256.00,45256.00,NaN,7.0,One Time
2,74119,1,44048.00,44048.00,1.0,3.0,One Time
3,2066,1,36489.24,36489.24,1.0,7.0,One Time
4,12399,1,30186.00,30186.00,5.0,9.0,One Time
...,...,...,...,...,...,...,...
99436,65096,1,9.59,9.59,5.0,1.0,One Time
99437,64968,1,0.00,0.00,3.0,NaN,One Time
99438,20654,1,0.00,0.00,1.0,NaN,One Time
99439,9909,1,0.00,0.00,1.0,NaN,One Time
99440,52278,1,NaN,NaN,1.0,1.0,One Time

Saved → customer_intelligence.csv


==========================================================================================
8.6 CUSTOMER SEGMENT SUMMARY
==========================================================================================

  CustomerSegment  Customers      Revenue  AverageCustomerValue
0        One Time      99441  20470726.66                205.86

Saved → customer_segment_summary.csv


==========================================================================================
8.7 SELLER INTELLIGENCE
==========================================================================================

,seller_id,seller_state,Orders,Revenue,ProfitProxy,AverageReview,AverageDeliveryDays,ProfitMarginPercent
0,7c67e1448b00f6e969d365cea6b010ab,SP,982,507166.91,136311.34,3.34,9.77,26.88
1,1025f0e2d44d7041d6cf58b6550e0bfa,SP,915,308222.04,105076.41,3.85,7.35,34.09
2,4a3ca9315b744ce9f8e9374361493884,SP,1806,301245.27,165405.88,3.80,11.16,54.91
3,1f50f920176fa81dab994f9023523100,SP,1404,290253.42,71773.44,3.99,11.11,24.73
4,53243585a1d6dc2643021fd1853d8905,BA,358,284903.08,209695.42,4.08,9.20,73.60
...,...,...,...,...,...,...,...,...
3090,ad14615bdd492b01b0d97922e87cb87f,SC,1,19.21,-2.71,5.00,12.00,-14.11
3091,702835e4b785b67a084280efca355756,MG,1,18.56,-3.36,5.00,1.00,-18.10
3092,4965a7002cca77301c82d3f91b82e1a9,SP,1,16.36,0.62,5.00,1.00,3.79
3093,77128dec4bec4878c37ab7d6169d6f26,SP,1,15.22,-2.22,5.00,6.00,-14.59
3094,cf6f6bc4df3999b9c6440f124fb2f687,SP,1,12.22,-5.22,5.00,NaN,-42.72

Saved → seller_intelligence.csv


==========================================================================================
8.8 SELLER PERFORMANCE MATRIX
==========================================================================================

,seller_id,Orders,Revenue,ReviewScore,DeliveryDays,SellerSegment
0,7c67e1448b00f6e969d365cea6b010ab,982,507166.91,3.34,9.77,Revenue Leader - Review Risk
1,1025f0e2d44d7041d6cf58b6550e0bfa,915,308222.04,3.85,7.35,Revenue Leader - Review Risk
2,4a3ca9315b744ce9f8e9374361493884,1806,301245.27,3.80,11.16,Revenue Leader - Review Risk
3,1f50f920176fa81dab994f9023523100,1404,290253.42,3.99,11.11,High Performer
4,53243585a1d6dc2643021fd1853d8905,358,284903.08,4.08,9.20,High Performer
...,...,...,...,...,...,...
3090,ad14615bdd492b01b0d97922e87cb87f,1,19.21,5.00,12.00,Quality Opportunity
3091,702835e4b785b67a084280efca355756,1,18.56,5.00,1.00,Quality Opportunity
3092,4965a7002cca77301c82d3f91b82e1a9,1,16.36,5.00,1.00,Quality Opportunity
3093,77128dec4bec4878c37ab7d6169d6f26,1,15.22,5.00,6.00,Quality Opportunity
3094,cf6f6bc4df3999b9c6440f124fb2f687,1,12.22,5.00,NaN,Quality Opportunity

Saved → seller_performance_matrix.csv


==========================================================================================
8.9 DELIVERY INTELLIGENCE
==========================================================================================

,DeliveryStatus,Orders,OrderSharePercent,AverageDeliveryDays,AverageShippingDays,AverageDelayDays,AverageReview
0,Late,4534,4.0,34.12,2.40,11.28,1.97
1,On Time,108891,96.0,7.64,2.41,-15.82,4.10

Saved → delivery_intelligence.csv


==========================================================================================
8.10 GEOGRAPHIC INTELLIGENCE
==========================================================================================

,State,Orders,Customers,Revenue,ProfitProxy,AverageReview,AverageDeliveryDays,LateDeliveryRate
0,SP,41746,41746,7673188.55,4484231.98,4.11,5.06,1.97
1,RJ,12852,12852,2783724.26,1518503.36,3.80,11.32,8.45
2,MG,11635,11635,2341861.47,1314454.57,4.07,8.26,2.36
3,RS,5466,5466,1152019.17,614781.28,4.04,11.44,3.86
4,PR,5045,5045,1074614.19,565232.08,4.09,8.16,1.92
5,BA,3380,3380,802416.72,411193.31,3.80,15.40,8.98
6,SC,3637,3637,799135.92,430893.08,3.99,11.11,4.57
7,GO,2020,2020,516182.51,241476.97,3.98,11.84,3.88
8,DF,2140,2140,434512.55,251978.44,4.00,9.22,2.89
9,ES,2033,2033,406946.26,225272.71,3.98,11.75,7.20
10,PE,1652,1652,378887.48,203338.37,3.95,14.50,6.74
11,CE,1336,1336,347678.36,178903.12,3.80,17.16,10.02
12,PA,975,975,262433.11,140248.51,3.78,19.84,9.22
13,MT,907,907,257447.65,126738.10,3.97,14.34,4.44
14,MA,747,747,199913.56,88124.45,3.69,17.34,10.59
15,PB,536,536,181546.00,89548.35,3.99,16.46,6.93
16,MS,715,715,165861.46,97668.61,4.02,11.88,5.45
17,PI,495,495,137077.67,65695.88,3.89,15.70,9.19
18,RN,485,485,117074.43,64174.88,4.07,15.22,6.20
19,AL,413,413,111993.78,64400.22,3.72,20.36,16.37
20,SE,350,350,90651.44,44809.38,3.81,17.34,10.77
21,TO,280,280,72412.08,37889.06,4.10,13.56,6.01
22,RO,253,253,69184.48,34723.26,3.96,16.45,3.17
23,AM,148,148,34873.79,16877.95,4.08,23.07,1.20
24,AC,81,81,24984.86,12296.20,4.10,16.91,2.17
25,AP,68,68,21642.70,10685.80,4.22,24.14,2.44
26,RR,46,46,12462.21,5594.24,3.58,24.15,7.69

Saved → geographic_intelligence.csv


==========================================================================================
8.11 LOCAL VS NON-LOCAL DELIVERY
==========================================================================================

,OrderType,Orders,Revenue,AverageDeliveryDays,AverageShippingDays,AverageReview,LateDeliveryRate
0,Local,35600,6205879.57,4.29,2.33,4.15,1.94
1,Non-Local,64088,14264847.09,11.25,2.45,3.95,5.15

Saved → local_vs_nonlocal_delivery.csv


==========================================================================================
8.12 PAYMENT INTELLIGENCE
==========================================================================================

,PaymentMethod,Orders,Revenue,AverageOrderValue,AverageInstallments,AveragePaymentCount
0,credit_card,74259,15520455.62,209.00,3.67,1.37
1,boleto,19784,4086820.71,206.57,1.00,1.50
2,"credit_card,voucher",2245,400382.82,178.34,2.30,1.28
3,debit_card,1527,256367.92,167.89,1.00,1.31
4,voucher,1621,206546.77,127.42,1.00,1.16
5,"credit_card,debit_card",1,152.82,152.82,3.00,1.00
6,not_defined,3,0.00,0.00,1.00,1.00
7,None,1,NaN,NaN,NaN,3.00

Saved → payment_intelligence.csv


==========================================================================================
8.13 REVIEW & CUSTOMER EXPERIENCE
==========================================================================================

  ReviewSentiment  Orders      Revenue  AverageDeliveryDays  AverageDelayDays
0        Positive   76028  14236809.38                 7.59            -15.58
1        Negative   14449   4331273.44                13.78            -10.70
2         Neutral    8136   1656131.39                 9.94            -14.12
3       No Review     828    246512.45                13.16            -11.37

Saved → review_customer_experience.csv


==========================================================================================
8.14 AUTOMATED BUSINESS INSIGHT GENERATION
==========================================================================================

,InsightType,Priority,Metric,Insight,Recommendation
0,Executive,High,Revenue,"Total revenue is 20,470,726.66 across 99,441 o...",Use revenue and order trends as the primary ex...
1,Executive,High,Average Order Value,Average order value is 205.86.,"Increase basket size through cross-selling, bu..."
2,Operations,Medium,Late Delivery Rate,Late delivery rate is 4.00%.,"Investigate logistics, seller processing time ..."
3,Profitability,High,Profit Margin,Current profit proxy margin is 55.39%.,"Monitor pricing, freight cost and product mix ..."
4,Revenue Trend,High,Monthly Revenue Growth,Revenue increased by 652.89% from the previous...,Investigate the drivers of the latest monthly ...
5,Product,High,Top Category,bed_bath_table is the highest-revenue product ...,Protect inventory availability and analyze cro...
6,Seller,Medium,High Performing Sellers,402 sellers are classified as High Performers.,Study high-performing seller practices and rep...
7,Logistics,High,Local vs Non-Local,Non-local orders take approximately 2.62× the ...,"Optimize inter-state logistics, carrier alloca..."
8,Payments,Medium,Top Payment Method,credit_card generates the highest revenue at 1...,Prioritize reliability and conversion optimiza...

                       Component     Status
0                  Executive KPI  Completed
1   Monthly Business Performance  Completed
2           Product Intelligence  Completed
3          Category Intelligence  Completed
4          Customer Intelligence  Completed
5          Customer Segmentation  Completed
6            Seller Intelligence  Completed
7      Seller Performance Matrix  Completed
8          Delivery Intelligence  Completed
9        Geographic Intelligence  Completed
10            Local vs Non-Local  Completed
11          Payment Intelligence  Completed
12           Review Intelligence  Completed
13   Automated Business Insights  Completed

==========================================================================================
PHASE 8 COMPLETED SUCCESSFULLY
==========================================================================================

Output Directory:
/content/drive/MyDrive/InsightFlow_AI/reports/phase8_business_intelligence

Files Generated:
✓ business_insights.csv
✓ business_insights.parquet
✓ category_intelligence.csv
✓ category_intelligence.parquet
✓ customer_intelligence.csv
✓ customer_intelligence.parquet
✓ customer_segment_summary.csv
✓ customer_segment_summary.parquet
✓ delivery_intelligence.csv
✓ delivery_intelligence.parquet
✓ executive_kpis.csv
✓ executive_kpis.parquet
✓ geographic_intelligence.csv
✓ geographic_intelligence.parquet
✓ local_vs_nonlocal_delivery.csv
✓ local_vs_nonlocal_delivery.parquet
✓ monthly_business_performance.csv
✓ monthly_business_performance.parquet
✓ payment_intelligence.csv
✓ payment_intelligence.parquet
✓ phase8_summary.csv
✓ phase8_summary.parquet
✓ product_intelligence.csv
✓ product_intelligence.parquet
✓ review_customer_experience.csv
✓ review_customer_experience.parquet
✓ seller_intelligence.csv
✓ seller_intelligence.parquet
✓ seller_performance_matrix.csv
✓ seller_performance_matrix.parquet


==========================================================================================
BUSINESS INTELLIGENCE LAYER READY
==========================================================================================

SQLite connection closed.
InsightFlow AI Phase 8 is ready for Phase 9.

CUSTOMER, PRODUCT & SELLER INTELLIGENCE

In [ ]:
# ============================================================
# INSIGHTFLOW AI
# PHASE 9.2
# DELIVERY METRIC REFINEMENT
# ============================================================

print("="*90)
print("INSIGHTFLOW AI — PHASE 9.2")
print("DELIVERY METRIC REFINEMENT")
print("="*90)


PHASE92_PATH = os.path.join(
    BASE,
    "reports",
    "phase9_2_delivery"
)

os.makedirs(PHASE92_PATH, exist_ok=True)


delivery = warehouse.copy()


# ============================================================
# DELIVERY COMPLETION
# ============================================================

delivery["delivery_completed"] = (
    delivery["order_delivered_customer_date"]
    .notna()
)


# ============================================================
# DELIVERY VARIANCE
#
# Negative = delivered early
# Positive = delivered late
# ============================================================

delivery["delivery_variance_days"] = np.where(

    delivery["delivery_completed"],

    (
        delivery["order_delivered_customer_date"]
        -
        delivery["order_estimated_delivery_date"]
    ).dt.total_seconds() / 86400,

    np.nan
)


print("\n" + "-"*60)
print("DELIVERY VARIANCE")
print("-"*60)

display(
    delivery[
        ["delivery_variance_days"]
    ]
    .describe()
)


# ============================================================
# CORRECTED DELIVERY DELAY
# ============================================================

delivery["delivery_delay_days_corrected"] = np.where(

    delivery["delivery_completed"],

    np.maximum(
        delivery["delivery_variance_days"],
        0
    ),

    np.nan
)


# ============================================================
# EARLY DELIVERY
# ============================================================

delivery["early_delivery_days"] = np.where(

    delivery["delivery_completed"],

    np.maximum(
        -delivery["delivery_variance_days"],
        0
    ),

    np.nan
)


# ============================================================
# DELIVERY CLASSIFICATION
# ============================================================

delivery["late_delivery_corrected"] = np.where(

    delivery["delivery_completed"],

    (
        delivery["delivery_variance_days"] > 0
    ).astype(int),

    np.nan
)


delivery["on_time_delivery_corrected"] = np.where(

    delivery["delivery_completed"],

    (
        delivery["delivery_variance_days"] <= 0
    ).astype(int),

    np.nan
)


# ============================================================
# NEW — EXPLICIT UNDELIVERED FLAG
# ============================================================

delivery["undelivered"] = (

    ~delivery["delivery_completed"]

).astype(int)


# ============================================================
# DELIVERY STATUS
# ============================================================

delivery["delivery_status_corrected"] = np.select(

    [

        delivery["undelivered"] == 1,

        delivery["late_delivery_corrected"] == 1,

        delivery["on_time_delivery_corrected"] == 1

    ],

    [

        "Undelivered",

        "Late",

        "On-Time / Early"

    ],

    default="Unknown"

)


# ============================================================
# RECONCILIATION
# ============================================================

total_rows = len(delivery)

late_count = (

    delivery["late_delivery_corrected"]
    .fillna(0)
    .sum()
)

on_time_count = (

    delivery["on_time_delivery_corrected"]
    .fillna(0)
    .sum()
)

undelivered_count = (

    delivery["undelivered"]
    .sum()
)


classified_total = (

    late_count
    +
    on_time_count
    +
    undelivered_count

)


print("\n" + "="*90)
print("DELIVERY RECONCILIATION")
print("="*90)

print(
    "Total rows:",
    total_rows
)

print(
    "Late deliveries:",
    int(late_count)
)

print(
    "On-time / early deliveries:",
    int(on_time_count)
)

print(
    "Undelivered:",
    int(undelivered_count)
)

print(
    "Total classified:",
    int(classified_total)
)

print(
    "Reconciliation difference:",
    int(total_rows - classified_total)
)


# ============================================================
# VALIDATION
# ============================================================

negative_corrected_delays = (

    delivery["delivery_delay_days_corrected"]
    .dropna()
    .lt(0)
    .sum()

)


negative_early_days = (

    delivery["early_delivery_days"]
    .dropna()
    .lt(0)
    .sum()

)


print(
    "Negative corrected delays:",
    negative_corrected_delays
)

print(
    "Negative early-delivery days:",
    negative_early_days
)


# ============================================================
# ASSERTIONS
# ============================================================

assert negative_corrected_delays == 0

assert negative_early_days == 0

assert total_rows == classified_total

print("\n✓ Delivery reconciliation passed")


# ============================================================
# DELIVERY STATISTICS
# ============================================================

print("\n" + "-"*60)
print("CORRECTED DELIVERY DELAY")
print("-"*60)

display(
    delivery[
        ["delivery_delay_days_corrected"]
    ]
    .describe()
)


print("\n" + "-"*60)
print("EARLY DELIVERY")
print("-"*60)

display(
    delivery[
        ["early_delivery_days"]
    ]
    .describe()
)


# ============================================================
# DELIVERY STATUS SUMMARY
# ============================================================

delivery_summary = (

    delivery

    .groupby("delivery_status_corrected")

    .agg(

        Orders=(
            "order_id",
            "nunique"
        ),

        Rows=(
            "order_id",
            "count"
        ),

        AverageDeliveryDays=(
            "delivery_days",
            "mean"
        ),

        AverageDelayDays=(
            "delivery_delay_days_corrected",
            "mean"
        ),

        AverageEarlyDays=(
            "early_delivery_days",
            "mean"
        )

    )

    .reset_index()

)


delivery_summary["Percentage"] = (

    delivery_summary["Rows"]
    /
    total_rows
    *
    100

)


display(delivery_summary)


# ============================================================
# SAMPLE DELIVERY RECORDS
# ============================================================

print("\n" + "="*90)
print("SAMPLE DELIVERY RECORDS")
print("="*90)

display(

    delivery[

        [

            "order_delivered_customer_date",

            "order_estimated_delivery_date",

            "delivery_variance_days",

            "delivery_delay_days_corrected",

            "early_delivery_days",

            "late_delivery_corrected",

            "on_time_delivery_corrected",

            "undelivered",

            "delivery_status_corrected"

        ]

    ]

    .head(20)

)


# ============================================================
# SELLER DELIVERY METRICS
# ============================================================

seller_delivery = (

    delivery

    .groupby("seller_id")

    .agg(

        Orders=(
            "order_id",
            "nunique"
        ),

        Revenue=(
            "total_payment",
            "sum"
        ),

        ProfitProxy=(
            "profit_proxy",
            "sum"
        ),

        AverageReview=(
            "review_score",
            "mean"
        ),

        AverageDeliveryDays=(
            "delivery_days",
            "mean"
        ),

        AverageDeliveryDelay=(
            "delivery_delay_days_corrected",
            "mean"
        ),

        AverageEarlyDelivery=(
            "early_delivery_days",
            "mean"
        ),

        LateDeliveries=(
            "late_delivery_corrected",
            "sum"
        ),

        OnTimeDeliveries=(
            "on_time_delivery_corrected",
            "sum"
        ),

        UndeliveredOrders=(
            "undelivered",
            "sum"
        )

    )

    .reset_index()

)


seller_delivery["LateDeliveryRate"] = np.where(

    (
        seller_delivery["LateDeliveries"]
        +
        seller_delivery["OnTimeDeliveries"]
    ) > 0,

    seller_delivery["LateDeliveries"]
    /
    (
        seller_delivery["LateDeliveries"]
        +
        seller_delivery["OnTimeDeliveries"]
    )
    * 100,

    np.nan

)


display(
    seller_delivery.head(20)
)


# ============================================================
# SAVE PHASE 9.2
# ============================================================

print("\n" + "="*90)
print("SAVING PHASE 9.2")
print("="*90)


delivery.to_parquet(

    os.path.join(
        PHASE92_PATH,
        "delivery_metrics_corrected.parquet"
    ),

    index=False

)


delivery.to_csv(

    os.path.join(
        PHASE92_PATH,
        "delivery_metrics_corrected.csv"
    ),

    index=False

)


delivery_summary.to_parquet(

    os.path.join(
        PHASE92_PATH,
        "delivery_summary_corrected.parquet"
    ),

    index=False

)


delivery_summary.to_csv(

    os.path.join(
        PHASE92_PATH,
        "delivery_summary_corrected.csv"
    ),

    index=False

)


seller_delivery.to_parquet(

    os.path.join(
        PHASE92_PATH,
        "seller_delivery_corrected.parquet"
    ),

    index=False

)


seller_delivery.to_csv(

    os.path.join(
        PHASE92_PATH,
        "seller_delivery_corrected.csv"
    ),

    index=False

)


print("✓ delivery_metrics_corrected")
print("✓ delivery_summary_corrected")
print("✓ seller_delivery_corrected")


# ============================================================
# FINAL PHASE 9.2 SCORECARD
# ============================================================

print("\n" + "="*90)
print("PHASE 9.2 VALIDATION SCORECARD")
print("="*90)

print(
    f"{'Warehouse Rows':<35}{total_rows:,}"
)

print(
    f"{'Late Deliveries':<35}{int(late_count):,}"
)

print(
    f"{'On-Time / Early':<35}{int(on_time_count):,}"
)

print(
    f"{'Undelivered':<35}{int(undelivered_count):,}"
)

print(
    f"{'Total Classified':<35}{int(classified_total):,}"
)

print(
    f"{'Reconciliation Difference':<35}{int(total_rows-classified_total):,}"
)

print(
    f"{'Negative Corrected Delays':<35}{negative_corrected_delays}"
)

print(
    f"{'Negative Early Days':<35}{negative_early_days}"
)


print("\n" + "="*90)
print("PHASE 9.2 COMPLETED SUCCESSFULLY")
print("="*90)

print("Output Directory:")
print(PHASE92_PATH)

==========================================================================================
INSIGHTFLOW AI — PHASE 9.2
DELIVERY METRIC REFINEMENT
==========================================================================================

------------------------------------------------------------
DELIVERY VARIANCE
------------------------------------------------------------

       delivery_variance_days
count           110196.000000
mean               -11.333149
std                 10.162342
min               -146.016123
25%                -16.321042
50%                -12.046788
75%                 -6.476803
max                188.975081

==========================================================================================
DELIVERY RECONCILIATION
==========================================================================================
Total rows: 113425
Late deliveries: 8715
On-time / early deliveries: 101481
Undelivered: 3229
Total classified: 113425
Reconciliation difference: 0
Negative corrected delays: 0
Negative early-delivery days: 0

✓ Delivery reconciliation passed

------------------------------------------------------------
CORRECTED DELIVERY DELAY
------------------------------------------------------------

       delivery_delay_days_corrected
count                  110196.000000
mean                        0.745647
std                         4.641307
min                         0.000000
25%                         0.000000
50%                         0.000000
75%                         0.000000
max                       188.975081

------------------------------------------------------------
EARLY DELIVERY
------------------------------------------------------------

       early_delivery_days
count        110196.000000
mean             12.078797
std               7.982372
min               0.000000
25%               6.476803
50%              12.046788
75%              16.321042
max             146.016123

,delivery_status_corrected,Orders,Rows,AverageDeliveryDays,AverageDelayDays,AverageEarlyDays,Percentage
0,Late,7827,8715,24.835782,9.428269,0.000000,7.683491
1,On-Time / Early,88649,101481,7.351248,0.000000,13.116102,89.469694
2,Undelivered,2965,3229,NaN,NaN,NaN,2.846815

==========================================================================================
SAMPLE DELIVERY RECORDS
==========================================================================================

,order_delivered_customer_date,order_estimated_delivery_date,delivery_variance_days,delivery_delay_days_corrected,early_delivery_days,late_delivery_corrected,on_time_delivery_corrected,undelivered,delivery_status_corrected
0,2018-05-16 20:48:37,2018-05-21,-4.132905,0.000000,4.132905,0.0,1.0,0,On-Time / Early
1,2018-05-10 18:02:42,2018-05-15,-4.248125,0.000000,4.248125,0.0,1.0,0,On-Time / Early
2,2017-04-05 14:38:47,2017-04-07,-1.389734,0.000000,1.389734,0.0,1.0,0,On-Time / Early
3,2017-11-01 21:23:05,2017-11-13,-11.108970,0.000000,11.108970,0.0,1.0,0,On-Time / Early
4,2017-11-27 23:08:56,2017-12-05,-7.035463,0.000000,7.035463,0.0,1.0,0,On-Time / Early
5,2018-04-07 16:12:43,2018-04-19,-11.324502,0.000000,11.324502,0.0,1.0,0,On-Time / Early
6,2018-04-27 12:08:59,2018-05-09,-11.493762,0.000000,11.493762,0.0,1.0,0,On-Time / Early
7,2018-03-16 19:02:51,2018-03-26,-9.206354,0.000000,9.206354,0.0,1.0,0,On-Time / Early
8,2018-03-16 19:02:51,2018-03-26,-9.206354,0.000000,9.206354,0.0,1.0,0,On-Time / Early
9,2017-03-09 08:33:08,2017-04-06,-27.643657,0.000000,27.643657,0.0,1.0,0,On-Time / Early
10,2018-05-05 12:38:38,2018-04-04,31.526829,31.526829,0.000000,1.0,0.0,0,Late
11,2017-08-03 18:42:49,2017-08-15,-11.220266,0.000000,11.220266,0.0,1.0,0,On-Time / Early
12,2017-11-29 21:55:29,2017-12-07,-7.086470,0.000000,7.086470,0.0,1.0,0,On-Time / Early
13,2018-04-09 13:35:42,2018-04-17,-7.433542,0.000000,7.433542,0.0,1.0,0,On-Time / Early
14,2018-04-30 15:35:03,2018-05-15,-14.350660,0.000000,14.350660,0.0,1.0,0,On-Time / Early
15,2017-08-22 20:57:57,2017-09-06,-14.126424,0.000000,14.126424,0.0,1.0,0,On-Time / Early
16,2017-10-13 13:50:07,2017-10-26,-12.423530,0.000000,12.423530,0.0,1.0,0,On-Time / Early
17,2017-12-27 01:37:12,2018-01-05,-8.932500,0.000000,8.932500,0.0,1.0,0,On-Time / Early
18,2018-01-11 22:20:23,2018-01-24,-12.069178,0.000000,12.069178,0.0,1.0,0,On-Time / Early
19,2017-08-21 19:18:42,2017-09-06,-15.195347,0.000000,15.195347,0.0,1.0,0,On-Time / Early

,seller_id,Orders,Revenue,ProfitProxy,AverageReview,AverageDeliveryDays,AverageDeliveryDelay,AverageEarlyDelivery,LateDeliveries,OnTimeDeliveries,UndeliveredOrders,LateDeliveryRate
0,0015a82c2db000af6aaaf3ae2ecb0532,3,2748.06,2621.94,3.666667,7.333333,0.000000,15.593380,0.0,3.0,0,0.000000
1,001cca7ae9ae17fb1caed9dfb1094831,200,48349.22,16225.89,3.902542,9.991453,0.659533,13.228899,13.0,221.0,5,5.555556
2,001e6ad469a905060d959994f1b41e4f,1,267.94,232.06,1.000000,NaN,NaN,NaN,0.0,0.0,1,NaN
3,002100f778ceb8431b7a1020ff7ab48f,51,2445.64,440.84,3.981818,11.092593,1.375567,8.770686,9.0,45.0,1,16.666667
4,003554e2dce176b5555353e4f3555ac8,1,139.38,100.62,5.000000,4.000000,0.000000,26.066794,0.0,1.0,0,0.000000
5,004c9cd9d87a3c30c522c48c4fc07416,158,27810.35,16161.48,4.143713,12.190476,0.689731,12.021428,13.0,155.0,2,7.738095
6,00720abe85ba0859807595bbf045a33b,13,3118.40,691.52,3.653846,5.307692,0.787945,12.803091,2.0,24.0,0,7.692308
7,00ab3eff1b5192e5f1a63bcecfee11c8,1,110.08,85.92,5.000000,5.000000,0.000000,9.461100,0.0,1.0,0,0.000000
8,00d8b143d12632bad99c0ad66ad52825,1,137.10,34.90,5.000000,5.000000,0.000000,21.296088,0.0,1.0,0,0.000000
9,00ee68308b45bc5e2660cd833c3f81cc,135,37126.37,17079.34,4.327485,6.703488,0.770266,10.925166,14.0,158.0,0,8.139535
10,00fc707aaaad2d31347cf883cd2dfe10,103,25822.96,10399.81,3.791045,12.333333,0.284455,15.116808,6.0,129.0,0,4.444444
11,010543a62bd80aa422851e79a3bc7540,2,1447.95,1384.05,4.500000,5.500000,0.000000,7.753889,0.0,2.0,0,0.000000
12,010da0602d7774602cd1b3f5fb7b709e,1,5398.75,619.25,1.000000,4.000000,0.000000,9.109456,0.0,5.0,0,0.000000
13,011b0eaba87386a2ae96a7d32bb531d1,1,258.32,70.80,4.000000,9.000000,0.000000,29.522292,0.0,2.0,0,0.000000
14,01266d4c46afa519678d16a8b683d325,3,137.48,43.02,5.000000,4.333333,0.000000,8.601331,0.0,3.0,0,0.000000
15,013900e863eace745d3ec7614cab5b1a,23,2659.19,1150.03,4.730769,7.846154,0.000000,15.359030,0.0,26.0,0,0.000000
16,014c0679dd340a0e338872e7ec85666a,14,8423.67,6429.69,3.666667,12.866667,0.927373,11.979412,2.0,13.0,0,13.333333
17,014d9a685fd57276679edd00e07089e5,11,1317.47,582.95,3.833333,6.083333,0.000000,11.917173,0.0,12.0,0,0.000000
18,0176f73cc1195f367f7b32db1e5b3aa8,38,6521.06,3446.09,4.025641,10.868421,1.746583,9.827720,4.0,34.0,1,10.526316
19,01bcc9d254a0143f0ce9791b960b2a47,11,1798.87,1243.55,4.400000,10.600000,0.000000,17.622725,0.0,10.0,1,0.000000

==========================================================================================
SAVING PHASE 9.2
==========================================================================================
✓ delivery_metrics_corrected
✓ delivery_summary_corrected
✓ seller_delivery_corrected

==========================================================================================
PHASE 9.2 VALIDATION SCORECARD
==========================================================================================
Warehouse Rows                     113,425
Late Deliveries                    8,715
On-Time / Early                    101,481
Undelivered                        3,229
Total Classified                   113,425
Reconciliation Difference          0
Negative Corrected Delays          0
Negative Early Days                0

==========================================================================================
PHASE 9.2 COMPLETED SUCCESSFULLY
==========================================================================================
Output Directory:
/content/drive/MyDrive/InsightFlow_AI/reports/phase9_2_delivery

In [ ]:
# ============================================================
# INSIGHTFLOW AI
# PHASE 10B
# PRODUCTION-GRADE CUSTOMER RETENTION ENGINE
# ============================================================

import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings("ignore")

print("="*90)
print("INSIGHTFLOW AI — PHASE 10B")
print("ROLLING CUSTOMER RETENTION PREDICTION")
print("="*90)

# ============================================================
# PATHS
# ============================================================

BASE = "/content/drive/MyDrive/InsightFlow_AI"

PHASE10B_PATH = os.path.join(
    BASE,
    "reports",
    "phase10b_retention"
)

os.makedirs(PHASE10B_PATH, exist_ok=True)

# ============================================================
# PREPARE ORDER-LEVEL DATA
# ============================================================

orders_ml = warehouse.copy()

orders_ml["order_purchase_timestamp"] = pd.to_datetime(
    orders_ml["order_purchase_timestamp"],
    errors="coerce"
)

orders_ml = orders_ml[
    orders_ml["order_purchase_timestamp"].notna()
].copy()

# ============================================================
# IMPORTANT:
# CUSTOMER IDENTITY = customer_unique_id
# This represents the actual customer across orders.
# ============================================================

orders_ml = orders_ml[
    orders_ml["customer_unique_id"].notna()
].copy()

orders_ml = orders_ml.sort_values(
    "order_purchase_timestamp"
).reset_index(drop=True)

print("="*90)
print("ORDER DATA READY")
print("="*90)

print("Rows              :", len(orders_ml))
print(
    "Unique Orders     :",
    orders_ml["order_id"].nunique()
)
print(
    "Unique Customers  :",
    orders_ml["customer_unique_id"].nunique()
)

# ============================================================
# TEMPORAL RANGE
# ============================================================

min_date = orders_ml["order_purchase_timestamp"].min()
max_date = orders_ml["order_purchase_timestamp"].max()

print()
print("Earliest transaction :", min_date)
print("Latest transaction   :", max_date)

# ============================================================
# PARAMETERS
# ============================================================

OBSERVATION_DAYS = 180
PREDICTION_DAYS = 90
STEP_DAYS = 30

print()
print("Observation Window :", OBSERVATION_DAYS, "days")
print("Prediction Window   :", PREDICTION_DAYS, "days")
print("Snapshot Frequency  :", STEP_DAYS, "days")


# ============================================================
# 10B.2
# ROLLING CUSTOMER SNAPSHOTS
# ============================================================

snapshot_start = (
    min_date
    + pd.Timedelta(days=OBSERVATION_DAYS)
)

snapshot_end = (
    max_date
    - pd.Timedelta(days=PREDICTION_DAYS)
)

snapshot_dates = pd.date_range(
    start=snapshot_start.normalize(),
    end=snapshot_end.normalize(),
    freq=f"{STEP_DAYS}D"
)

print("="*90)
print("CREATING ROLLING SNAPSHOTS")
print("="*90)

print("Number of snapshots:", len(snapshot_dates))
print("First snapshot      :", snapshot_dates.min())
print("Last snapshot       :", snapshot_dates.max())

# ============================================================
# FEATURE COLUMNS
# ============================================================

feature_columns = [
    "TotalOrders",
    "TotalRevenue",
    "AverageOrderValue",
    "MaximumOrderValue",
    "AverageBasketSize",
    "AverageBasketValue",
    "TotalItems",
    "AverageFreight",
    "AverageDeliveryDays",
    "AverageReview",
    "TotalProfitProxy",
    "RecencyDays",
    "CustomerLifetimeDays",
    "PurchaseFrequency",
    "OrderVelocity",
    "FreightRatio",
    "CategoryDiversity",
    "SellerDiversity",
    "WeekendPurchaseRatio"
]

snapshot_records = []

# ============================================================
# CREATE SNAPSHOTS
# ============================================================

for i, snapshot_date in enumerate(snapshot_dates):

    observation_start = (
        snapshot_date
        - pd.Timedelta(days=OBSERVATION_DAYS)
    )

    prediction_end = (
        snapshot_date
        + pd.Timedelta(days=PREDICTION_DAYS)
    )

    # --------------------------------------------------------
    # Historical data only
    # --------------------------------------------------------

    historical = orders_ml[
        (orders_ml["order_purchase_timestamp"] >= observation_start)
        &
        (orders_ml["order_purchase_timestamp"] < snapshot_date)
    ].copy()

    # --------------------------------------------------------
    # Future data ONLY for target
    # --------------------------------------------------------

    future = orders_ml[
        (orders_ml["order_purchase_timestamp"] >= snapshot_date)
        &
        (orders_ml["order_purchase_timestamp"] < prediction_end)
    ].copy()

    if historical.empty:
        continue

    # --------------------------------------------------------
    # Historical customer aggregation
    # --------------------------------------------------------

    customer_features = (

        historical

        .groupby("customer_unique_id")

        .agg(

            TotalOrders=("order_id", "nunique"),

            TotalRevenue=("total_payment", "sum"),

            AverageOrderValue=("total_payment", "mean"),

            MaximumOrderValue=("total_payment", "max"),

            AverageBasketSize=("basket_size", "mean"),

            AverageBasketValue=("basket_value", "mean"),

            TotalItems=("order_item_id", "count"),

            AverageFreight=("freight_value", "mean"),

            AverageDeliveryDays=("delivery_days", "mean"),

            AverageReview=("review_score", "mean"),

            TotalProfitProxy=("profit_proxy", "sum"),

            FirstPurchase=(
                "order_purchase_timestamp",
                "min"
            ),

            LastPurchase=(
                "order_purchase_timestamp",
                "max"
            )

        )

        .reset_index()

    )

    # --------------------------------------------------------
    # Recency
    # --------------------------------------------------------

    customer_features["RecencyDays"] = (

        snapshot_date
        - customer_features["LastPurchase"]

    ).dt.total_seconds() / 86400

    # --------------------------------------------------------
    # Customer lifetime
    # --------------------------------------------------------

    customer_features["CustomerLifetimeDays"] = (

        customer_features["LastPurchase"]
        - customer_features["FirstPurchase"]

    ).dt.total_seconds() / 86400

    customer_features["CustomerLifetimeDays"] = (
        customer_features["CustomerLifetimeDays"]
        .clip(lower=0)
    )

    # --------------------------------------------------------
    # Purchase frequency
    # --------------------------------------------------------

    customer_features["PurchaseFrequency"] = (

        customer_features["TotalOrders"]
        /
        (
            customer_features["CustomerLifetimeDays"]
            + 1
        )

    )

    # --------------------------------------------------------
    # Order velocity
    # --------------------------------------------------------

    customer_features["OrderVelocity"] = (

        customer_features["TotalOrders"]
        /
        OBSERVATION_DAYS

    )

    # --------------------------------------------------------
    # Freight ratio
    # --------------------------------------------------------

    customer_features["FreightRatio"] = (

        customer_features["AverageFreight"]
        /
        customer_features["AverageOrderValue"].replace(
            0,
            np.nan
        )

    ).fillna(0)

    # --------------------------------------------------------
    # Category diversity
    # --------------------------------------------------------

    category_diversity = (

        historical

        .groupby("customer_unique_id")[
            "product_category"
        ]

        .nunique()

    )

    customer_features["CategoryDiversity"] = (

        customer_features["customer_unique_id"]
        .map(category_diversity)
        .fillna(0)

    )

    # --------------------------------------------------------
    # Seller diversity
    # --------------------------------------------------------

    seller_diversity = (

        historical

        .groupby("customer_unique_id")[
            "seller_id"
        ]

        .nunique()

    )

    customer_features["SellerDiversity"] = (

        customer_features["customer_unique_id"]
        .map(seller_diversity)
        .fillna(0)

    )

    # --------------------------------------------------------
    # Weekend purchase ratio
    # --------------------------------------------------------

    historical["purchase_day"] = (
        historical["order_purchase_timestamp"]
        .dt.dayofweek
    )

    weekend_ratio = (

        historical.assign(
            weekend=
            historical["purchase_day"].isin([5, 6])
        )

        .groupby("customer_unique_id")["weekend"]

        .mean()

    )

    customer_features["WeekendPurchaseRatio"] = (

        customer_features["customer_unique_id"]
        .map(weekend_ratio)
        .fillna(0)

    )

    # --------------------------------------------------------
    # TARGET
    #
    # Did customer purchase during next 90 days?
    # --------------------------------------------------------

    future_customers = set(
        future["customer_unique_id"].unique()
    )

    customer_features["RepeatPurchase90D"] = (

        customer_features["customer_unique_id"]
        .isin(future_customers)
        .astype(int)

    )

    # --------------------------------------------------------
    # Snapshot identifier
    # --------------------------------------------------------

    customer_features["SnapshotDate"] = snapshot_date

    snapshot_records.append(
        customer_features
    )

    if (i + 1) % 5 == 0:

        print(
            f"Processed snapshot "
            f"{i+1}/{len(snapshot_dates)}"
        )

# ============================================================
# COMBINE
# ============================================================

retention_dataset = pd.concat(
    snapshot_records,
    ignore_index=True
)

print()
print("="*90)
print("ROLLING RETENTION DATASET CREATED")
print("="*90)

print(
    "Rows              :",
    len(retention_dataset)
)

print(
    "Customers         :",
    retention_dataset["customer_unique_id"].nunique()
)

print(
    "Snapshots         :",
    retention_dataset["SnapshotDate"].nunique()
)

print(
    "Positive targets  :",
    retention_dataset["RepeatPurchase90D"].sum()
)

print(
    "Positive rate     :",
    round(
        retention_dataset["RepeatPurchase90D"].mean(),
        4
    )
)

display(
    retention_dataset.head()
)

# ============================================================
# 10B.3
# DATASET VALIDATION
# ============================================================

print("="*90)
print("RETENTION DATASET VALIDATION")
print("="*90)

print(
    "Total rows:",
    len(retention_dataset)
)

print(
    "Duplicate customer-snapshot pairs:",
    retention_dataset.duplicated(
        subset=[
            "customer_unique_id",
            "SnapshotDate"
        ]
    ).sum()
)

print(
    "Missing target:",
    retention_dataset[
        "RepeatPurchase90D"
    ].isna().sum()
)

print()
print("TARGET DISTRIBUTION")

display(
    retention_dataset[
        "RepeatPurchase90D"
    ].value_counts()
    .rename_axis("RepeatPurchase90D")
    .reset_index(name="Customers")
)

print()
print("TARGET RATE BY SNAPSHOT")

snapshot_target = (

    retention_dataset

    .groupby("SnapshotDate")

    ["RepeatPurchase90D"]

    .agg(
        Customers="count",
        Repeaters="sum",
        RepeatRate="mean"
    )

    .reset_index()

)

display(snapshot_target)

# ============================================================
# 10B.4
# SAVE ROLLING DATASET
# ============================================================

retention_dataset.to_parquet(
    os.path.join(
        PHASE10B_PATH,
        "rolling_retention_dataset.parquet"
    ),
    index=False
)

retention_dataset.to_csv(
    os.path.join(
        PHASE10B_PATH,
        "rolling_retention_dataset.csv"
    ),
    index=False
)

print("="*90)
print("ROLLING RETENTION DATASET SAVED")
print("="*90)

print(
    os.path.join(
        PHASE10B_PATH,
        "rolling_retention_dataset.parquet"
    )
)

# ============================================================
# PHASE 10B.5
# TEMPORAL TRAIN / VALIDATION / TEST SPLIT
# ============================================================

import pandas as pd
import numpy as np

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("="*90)
print("INSIGHTFLOW AI — PHASE 10B.5")
print("TEMPORAL MODEL SPLIT")
print("="*90)

# ============================================================
# SORT BY SNAPSHOT DATE
# ============================================================

model_data = retention_dataset.copy()

model_data["SnapshotDate"] = pd.to_datetime(
    model_data["SnapshotDate"]
)

model_data = model_data.sort_values(
    "SnapshotDate"
).reset_index(drop=True)

# ============================================================
# GET SNAPSHOT DATES
# ============================================================

dates = sorted(
    model_data["SnapshotDate"].unique()
)

n_dates = len(dates)

train_end_index = int(n_dates * 0.60)
validation_end_index = int(n_dates * 0.80)

train_dates = dates[:train_end_index]

validation_dates = dates[
    train_end_index:validation_end_index
]

test_dates = dates[
    validation_end_index:
]

# ============================================================
# SPLIT
# ============================================================

train = model_data[
    model_data["SnapshotDate"].isin(train_dates)
].copy()

validation = model_data[
    model_data["SnapshotDate"].isin(validation_dates)
].copy()

test = model_data[
    model_data["SnapshotDate"].isin(test_dates)
].copy()

print()
print("="*90)
print("TEMPORAL SPLIT")
print("="*90)

print(
    "Training snapshots   :",
    len(train_dates)
)

print(
    "Validation snapshots :",
    len(validation_dates)
)

print(
    "Test snapshots       :",
    len(test_dates)
)

print()
print(
    "Training period   :",
    train["SnapshotDate"].min(),
    "→",
    train["SnapshotDate"].max()
)

print(
    "Validation period :",
    validation["SnapshotDate"].min(),
    "→",
    validation["SnapshotDate"].max()
)

print(
    "Test period       :",
    test["SnapshotDate"].min(),
    "→",
    test["SnapshotDate"].max()
)

print()
print("Rows")
print("Training   :", len(train))
print("Validation :", len(validation))
print("Test       :", len(test))

print()
print("Positive examples")

print(
    "Training   :",
    train["RepeatPurchase90D"].sum()
)

print(
    "Validation :",
    validation["RepeatPurchase90D"].sum()
)

print(
    "Test       :",
    test["RepeatPurchase90D"].sum()
)

# ============================================================
# PHASE 10B.6
# FEATURE PREPARATION
# ============================================================

TARGET = "RepeatPurchase90D"

ID_COLUMNS = [
    "customer_unique_id",
    "SnapshotDate",
    "FirstPurchase",
    "LastPurchase"
]

FEATURES = [
    "TotalOrders",
    "TotalRevenue",
    "AverageOrderValue",
    "MaximumOrderValue",
    "AverageBasketSize",
    "AverageBasketValue",
    "TotalItems",
    "AverageFreight",
    "AverageDeliveryDays",
    "AverageReview",
    "TotalProfitProxy",
    "RecencyDays",
    "CustomerLifetimeDays",
    "PurchaseFrequency",
    "OrderVelocity",
    "FreightRatio",
    "CategoryDiversity",
    "SellerDiversity",
    "WeekendPurchaseRatio"
]

# ============================================================
# CREATE X / Y
# ============================================================

X_train = train[FEATURES].copy()
y_train = train[TARGET].copy()

X_validation = validation[FEATURES].copy()
y_validation = validation[TARGET].copy()

X_test = test[FEATURES].copy()
y_test = test[TARGET].copy()

# ============================================================
# HANDLE INFINITE VALUES
# ============================================================

for df in [
    X_train,
    X_validation,
    X_test
]:

    df.replace(
        [np.inf, -np.inf],
        np.nan,
        inplace=True
    )

# ============================================================
# MEDIAN IMPUTATION
# ============================================================

train_medians = X_train.median()

X_train = X_train.fillna(train_medians)

X_validation = X_validation.fillna(train_medians)

X_test = X_test.fillna(train_medians)

print("="*90)
print("FEATURE DATA READY")
print("="*90)

print("Number of features:", len(FEATURES))

print()
print("Training shape   :", X_train.shape)
print("Validation shape :", X_validation.shape)
print("Test shape       :", X_test.shape)

print()
print("Features:")

for feature in FEATURES:
    print("✓", feature)

    # ============================================================
# PHASE 10B.7
# OPTUNA-TUNED RANDOM FOREST
# ============================================================

!pip install -q optuna

import optuna
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score
)

print("="*90)
print("INSIGHTFLOW AI — PHASE 10B.7")
print("OPTUNA-TUNED RANDOM FOREST")
print("="*90)

# ============================================================
# OBJECTIVE FUNCTION
# ============================================================

def objective(trial):

    params = {

        "n_estimators": trial.suggest_int(
            "n_estimators",
            200,
            700,
            step=100
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            4,
            18
        ),

        "min_samples_split": trial.suggest_int(
            "min_samples_split",
            2,
            30
        ),

        "min_samples_leaf": trial.suggest_int(
            "min_samples_leaf",
            1,
            20
        ),

        "max_features": trial.suggest_categorical(
            "max_features",
            ["sqrt", "log2", 0.5, 0.8]
        ),

        "max_samples": trial.suggest_float(
            "max_samples",
            0.5,
            1.0
        ),

        "class_weight": trial.suggest_categorical(
            "class_weight",
            ["balanced", "balanced_subsample"]
        ),

        "random_state": 42,

        "n_jobs": -1
    }

    model = RandomForestClassifier(
        **params
    )

    model.fit(
        X_train,
        y_train
    )

    validation_probability = model.predict_proba(
        X_validation
    )[:, 1]

    # --------------------------------------------------------
    # PRIMARY OPTIMIZATION METRIC
    # --------------------------------------------------------

    pr_auc = average_precision_score(
        y_validation,
        validation_probability
    )

    return pr_auc


# ============================================================
# CREATE OPTUNA STUDY
# ============================================================

study = optuna.create_study(
    direction="maximize",
    study_name="InsightFlow_Retention_RF"
)

study.optimize(
    objective,
    n_trials=30,
    show_progress_bar=True
)

# ============================================================
# BEST PARAMETERS
# ============================================================

print()
print("="*90)
print("OPTUNA RESULTS")
print("="*90)

print(
    "Best Validation PR-AUC:",
    round(study.best_value, 6)
)

print()
print("Best Parameters:")

for key, value in study.best_params.items():

    print(
        f"{key:<25}: {value}"
    )

    # ============================================================
# 10B.7.1
# TRAIN BEST RANDOM FOREST
# ============================================================

best_rf = RandomForestClassifier(

    **study.best_params,

    random_state=42,

    n_jobs=-1
)

best_rf.fit(
    X_train,
    y_train
)

# ============================================================
# VALIDATION PREDICTIONS
# ============================================================

validation_probability = best_rf.predict_proba(
    X_validation
)[:, 1]

validation_prediction = (
    validation_probability >= 0.5
).astype(int)

validation_roc = roc_auc_score(
    y_validation,
    validation_probability
)

validation_pr = average_precision_score(
    y_validation,
    validation_probability
)

validation_precision = precision_score(
    y_validation,
    validation_prediction,
    zero_division=0
)

validation_recall = recall_score(
    y_validation,
    validation_prediction,
    zero_division=0
)

validation_f1 = f1_score(
    y_validation,
    validation_prediction,
    zero_division=0
)

print("="*90)
print("BEST RANDOM FOREST — VALIDATION RESULTS")
print("="*90)

print(
    "ROC-AUC   :",
    round(validation_roc, 6)
)

print(
    "PR-AUC    :",
    round(validation_pr, 6)
)

print(
    "Precision :",
    round(validation_precision, 6)
)

print(
    "Recall    :",
    round(validation_recall, 6)
)

print(
    "F1 Score  :",
    round(validation_f1, 6)
)

==========================================================================================
INSIGHTFLOW AI — PHASE 10B
ROLLING CUSTOMER RETENTION PREDICTION
==========================================================================================
==========================================================================================
ORDER DATA READY
==========================================================================================
Rows              : 113425
Unique Orders     : 99441
Unique Customers  : 96096

Earliest transaction : 2016-09-04 21:15:19
Latest transaction   : 2018-10-17 17:30:18

Observation Window : 180 days
Prediction Window   : 90 days
Snapshot Frequency  : 30 days
==========================================================================================
CREATING ROLLING SNAPSHOTS
==========================================================================================
Number of snapshots: 17
First snapshot      : 2017-03-03 00:00:00
Last snapshot       : 2018-06-26 00:00:00
Processed snapshot 5/17
Processed snapshot 10/17
Processed snapshot 15/17

==========================================================================================
ROLLING RETENTION DATASET CREATED
==========================================================================================
Rows              : 402002
Customers         : 82780
Snapshots         : 17
Positive targets  : 3198
Positive rate     : 0.008

,customer_unique_id,TotalOrders,TotalRevenue,AverageOrderValue,MaximumOrderValue,AverageBasketSize,AverageBasketValue,TotalItems,AverageFreight,AverageDeliveryDays,AverageReview,TotalProfitProxy,FirstPurchase,LastPurchase,RecencyDays,CustomerLifetimeDays,PurchaseFrequency,OrderVelocity,FreightRatio,CategoryDiversity,SellerDiversity,WeekendPurchaseRatio,RepeatPurchase90D,SnapshotDate
0,00115fc7123b5310cf6d3a3aa932699e,1,76.11,76.11,76.11,1.0,76.11,1,16.12,9.0,4.0,43.87,2017-01-21 21:58:35,2017-01-21 21:58:35,40.084317,0.0,1.0,0.005556,0.211799,1,1,1.0,0,2017-03-03
1,002b4cd83fabaffaa475f78ea5ef3e08,1,64.42,64.42,64.42,1.0,64.42,1,14.52,7.0,2.0,35.38,2017-02-01 13:53:16,2017-02-01 13:53:16,29.421343,0.0,1.0,0.005556,0.225396,1,1,0.0,0,2017-03-03
2,0032c76b20340da25249092a268ce66c,1,144.94,144.94,144.94,1.0,144.94,1,16.04,2.0,4.0,112.86,2016-10-06 11:32:00,2016-10-06 11:32:00,147.519444,0.0,1.0,0.005556,0.110666,1,1,0.0,0,2017-03-03
3,0071f46a072a9ae25bbe4438b15efe9c,1,174.54,174.54,174.54,0.0,174.54,0,NaN,NaN,3.0,0.00,2017-02-01 00:04:17,2017-02-01 00:04:17,29.997025,0.0,1.0,0.005556,0.000000,1,0,0.0,0,2017-03-03
4,0087eede471173af78d789df249c3a45,1,151.11,151.11,151.11,1.0,151.11,1,24.12,10.0,5.0,102.87,2017-02-16 20:12:03,2017-02-16 20:12:03,14.158299,0.0,1.0,0.005556,0.159619,1,1,0.0,0,2017-03-03

==========================================================================================
RETENTION DATASET VALIDATION
==========================================================================================
Total rows: 402002
Duplicate customer-snapshot pairs: 0
Missing target: 0

TARGET DISTRIBUTION

   RepeatPurchase90D  Customers
0                  0     398804
1                  1       3198

TARGET RATE BY SNAPSHOT

   SnapshotDate  Customers  Repeaters  RepeatRate
0    2017-03-03       3009         20    0.006647
1    2017-04-02       5530         52    0.009403
2    2017-05-02       7618         70    0.009189
3    2017-06-01      11102        100    0.009007
4    2017-07-01      14241        123    0.008637
5    2017-07-31      17244        147    0.008525
6    2017-08-30      19356        186    0.009609
7    2017-09-29      21090        214    0.010147
8    2017-10-29      22993        234    0.010177
9    2017-11-28      26365        240    0.009103
10   2017-12-28      29261        230    0.007860
11   2018-01-27      32003        241    0.007531
12   2018-02-26      34686        294    0.008476
13   2018-03-28      37629        291    0.007733
14   2018-04-27      40039        291    0.007268
15   2018-05-27      40091        283    0.007059
16   2018-06-26      39745        182    0.004579

==========================================================================================
ROLLING RETENTION DATASET SAVED
==========================================================================================
/content/drive/MyDrive/InsightFlow_AI/reports/phase10b_retention/rolling_retention_dataset.parquet
==========================================================================================
INSIGHTFLOW AI — PHASE 10B.5
TEMPORAL MODEL SPLIT
==========================================================================================

==========================================================================================
TEMPORAL SPLIT
==========================================================================================
Training snapshots   : 10
Validation snapshots : 3
Test snapshots       : 4

Training period   : 2017-03-03 00:00:00 → 2017-11-28 00:00:00
Validation period : 2017-12-28 00:00:00 → 2018-02-26 00:00:00
Test period       : 2018-03-28 00:00:00 → 2018-06-26 00:00:00

Rows
Training   : 148548
Validation : 95950
Test       : 157504

Positive examples
Training   : 1386
Validation : 765
Test       : 1047
==========================================================================================
FEATURE DATA READY
==========================================================================================
Number of features: 19

Training shape   : (148548, 19)
Validation shape : (95950, 19)
Test shape       : (157504, 19)

Features:
✓ TotalOrders
✓ TotalRevenue
✓ AverageOrderValue
✓ MaximumOrderValue
✓ AverageBasketSize
✓ AverageBasketValue
✓ TotalItems
✓ AverageFreight
✓ AverageDeliveryDays
✓ AverageReview
✓ TotalProfitProxy
✓ RecencyDays
✓ CustomerLifetimeDays
✓ PurchaseFrequency
✓ OrderVelocity
✓ FreightRatio
✓ CategoryDiversity
✓ SellerDiversity
✓ WeekendPurchaseRatio
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 26.4 MB/s eta 0:00:00

[I 2026-08-19 04:14:17,293] A new study created in memory with name: InsightFlow_Retention_RF

==========================================================================================
INSIGHTFLOW AI — PHASE 10B.7
OPTUNA-TUNED RANDOM FOREST
==========================================================================================

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-08-19 04:15:09,397] Trial 0 finished with value: 0.012522466088967846 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'log2', 'max_samples': 0.7290859222838295, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.012522466088967846.
[I 2026-08-19 04:16:05,770] Trial 1 finished with value: 0.014492764355730561 and parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 0.8, 'max_samples': 0.8872591772618428, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.014492764355730561.
[I 2026-08-19 04:18:19,863] Trial 2 finished with value: 0.011717497445278969 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 22, 'min_samples_leaf': 11, 'max_features': 0.8, 'max_samples': 0.7853814655004763, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: 0.014492764355730561.
[I 2026-08-19 04:24:04,408] Trial 3 finished with value: 0.01481298470065454 and parameters: {'n_estimators': 600, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.5, 'max_samples': 0.9772390509563214, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 0.01481298470065454.
[I 2026-08-19 04:24:54,258] Trial 4 finished with value: 0.014754007452190106 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 16, 'max_features': 'log2', 'max_samples': 0.7915861381597333, 'class_weight': 'balanced'}. Best is trial 3 with value: 0.01481298470065454.
[I 2026-08-19 04:27:38,146] Trial 5 finished with value: 0.01207964133401236 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 17, 'max_features': 0.8, 'max_samples': 0.6379554971589835, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 0.01481298470065454.
[I 2026-08-19 04:30:04,026] Trial 6 finished with value: 0.01567014514283711 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 18, 'max_features': 0.5, 'max_samples': 0.7086511424531257, 'class_weight': 'balanced_subsample'}. Best is trial 6 with value: 0.01567014514283711.
[I 2026-08-19 04:32:35,565] Trial 7 finished with value: 0.013917362391281557 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 20, 'max_features': 0.8, 'max_samples': 0.819224201628842, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.01567014514283711.
[I 2026-08-19 04:33:56,170] Trial 8 finished with value: 0.014173020934178493 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'max_samples': 0.7650161902134268, 'class_weight': 'balanced_subsample'}. Best is trial 6 with value: 0.01567014514283711.
[I 2026-08-19 04:34:52,476] Trial 9 finished with value: 0.017697768577418838 and parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'log2', 'max_samples': 0.6511431934747851, 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.017697768577418838.
[I 2026-08-19 04:37:27,529] Trial 10 finished with value: 0.019064544857752767 and parameters: {'n_estimators': 700, 'max_depth': 18, 'min_samples_split': 27, 'min_samples_leaf': 13, 'max_features': 'log2', 'max_samples': 0.5029414313128573, 'class_weight': 'balanced_subsample'}. Best is trial 10 with value: 0.019064544857752767.
[I 2026-08-19 04:40:07,313] Trial 11 finished with value: 0.019241934623043626 and parameters: {'n_estimators': 700, 'max_depth': 18, 'min_samples_split': 30, 'min_samples_leaf': 12, 'max_features': 'log2', 'max_samples': 0.5060755289441499, 'class_weight': 'balanced_subsample'}. Best is trial 11 with value: 0.019241934623043626.
[I 2026-08-19 04:42:51,642] Trial 12 finished with value: 0.018874317935378887 and parameters: {'n_estimators': 700, 'max_depth': 18, 'min_samples_split': 30, 'min_samples_leaf': 13, 'max_features': 'log2', 'max_samples': 0.5174382453755456, 'class_weight': 'balanced_subsample'}. Best is trial 11 with value: 0.019241934623043626.
[I 2026-08-19 04:45:29,131] Trial 13 finished with value: 0.017473757455865213 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 30, 'min_samples_leaf': 14, 'max_features': 'log2', 'max_samples': 0.5064703894772624, 'class_weight': 'balanced_subsample'}. Best is trial 11 with value: 0.019241934623043626.
[I 2026-08-19 04:47:50,001] Trial 14 finished with value: 0.017078939675454263 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 25, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'max_samples': 0.5745486953876555, 'class_weight': 'balanced_subsample'}. Best is trial 11 with value: 0.019241934623043626.
[I 2026-08-19 04:50:13,945] Trial 15 finished with value: 0.01979008139641122 and parameters: {'n_estimators': 600, 'max_depth': 18, 'min_samples_split': 25, 'min_samples_leaf': 13, 'max_features': 'log2', 'max_samples': 0.5800077143318544, 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.01979008139641122.
[I 2026-08-19 04:52:08,447] Trial 16 finished with value: 0.0175064000551539 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 21, 'min_samples_leaf': 15, 'max_features': 'log2', 'max_samples': 0.5955927038590341, 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.01979008139641122.
[I 2026-08-19 04:54:32,376] Trial 17 finished with value: 0.02006677107560051 and parameters: {'n_estimators': 600, 'max_depth': 18, 'min_samples_split': 21, 'min_samples_leaf': 12, 'max_features': 'log2', 'max_samples': 0.5771464513921649, 'class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.02006677107560051.
[I 2026-08-19 04:56:19,105] Trial 18 finished with value: 0.016075780628747025 and parameters: {'n_estimators': 500, 'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'max_samples': 0.5846964069647484, 'class_weight': 'balanced'}. Best is trial 17 with value: 0.02006677107560051.
[I 2026-08-19 05:00:52,665] Trial 19 finished with value: 0.013611067222003934 and parameters: {'n_estimators': 600, 'max_depth': 15, 'min_samples_split': 25, 'min_samples_leaf': 5, 'max_features': 0.5, 'max_samples': 0.6466479927618278, 'class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.02006677107560051.
[I 2026-08-19 05:03:09,318] Trial 20 finished with value: 0.02139203386629087 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 19, 'max_features': 'log2', 'max_samples': 0.6982454818786721, 'class_weight': 'balanced_subsample'}. Best is trial 20 with value: 0.02139203386629087.
[I 2026-08-19 05:05:35,221] Trial 21 finished with value: 0.02192874876637702 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 20, 'max_features': 'log2', 'max_samples': 0.6917586301091331, 'class_weight': 'balanced_subsample'}. Best is trial 21 with value: 0.02192874876637702.
[I 2026-08-19 05:07:51,955] Trial 22 finished with value: 0.020281069836429202 and parameters: {'n_estimators': 500, 'max_depth': 16, 'min_samples_split': 16, 'min_samples_leaf': 20, 'max_features': 'log2', 'max_samples': 0.6897535319861662, 'class_weight': 'balanced_subsample'}. Best is trial 21 with value: 0.02192874876637702.
[I 2026-08-19 05:10:06,710] Trial 23 finished with value: 0.01946092006557914 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 20, 'max_features': 'log2', 'max_samples': 0.6951168403533559, 'class_weight': 'balanced_subsample'}. Best is trial 21 with value: 0.02192874876637702.
[I 2026-08-19 05:12:01,998] Trial 24 finished with value: 0.01952440329951201 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 18, 'max_features': 'log2', 'max_samples': 0.8509283038746212, 'class_weight': 'balanced_subsample'}. Best is trial 21 with value: 0.02192874876637702.
[I 2026-08-19 05:13:45,254] Trial 25 finished with value: 0.020386514000160567 and parameters: {'n_estimators': 400, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 19, 'max_features': 'log2', 'max_samples': 0.6783392779784297, 'class_weight': 'balanced_subsample'}. Best is trial 21 with value: 0.02192874876637702.
[I 2026-08-19 05:15:29,540] Trial 26 finished with value: 0.022071863475830004 and parameters: {'n_estimators': 400, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 18, 'max_features': 'log2', 'max_samples': 0.7414875148324664, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.022071863475830004.
[I 2026-08-19 05:18:55,161] Trial 27 finished with value: 0.019642245101985707 and parameters: {'n_estimators': 400, 'max_depth': 17, 'min_samples_split': 13, 'min_samples_leaf': 16, 'max_features': 0.5, 'max_samples': 0.7565996415115345, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.022071863475830004.
[I 2026-08-19 05:21:12,942] Trial 28 finished with value: 0.022976504193409283 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 19, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'max_samples': 0.8627378768830147, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.022976504193409283.
[I 2026-08-19 05:22:58,353] Trial 29 finished with value: 0.019686795543614695 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 23, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'max_samples': 0.925671793669074, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.022976504193409283.

==========================================================================================
OPTUNA RESULTS
==========================================================================================
Best Validation PR-AUC: 0.022977

Best Parameters:
n_estimators             : 500
max_depth                : 17
min_samples_split        : 19
min_samples_leaf         : 18
max_features             : sqrt
max_samples              : 0.8627378768830147
class_weight             : balanced
==========================================================================================
BEST RANDOM FOREST — VALIDATION RESULTS
==========================================================================================
ROC-AUC   : 0.617239
PR-AUC    : 0.022977
Precision : 0.052726
Recall    : 0.077124
F1 Score  : 0.062633

In [ ]:
# ============================================================
# PHASE 10B.8
# OPTUNA-TUNED XGBOOST
# ============================================================

!pip install -q xgboost

import xgboost as xgb
import optuna

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score
)

print("="*90)
print("INSIGHTFLOW AI — PHASE 10B.8")
print("OPTUNA-TUNED XGBOOST")
print("="*90)

# ============================================================
# CALCULATE CLASS IMBALANCE
# ============================================================

negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()

scale_pos_weight = (
    negative_count / positive_count
)

print()
print("Negative samples :", negative_count)
print("Positive samples :", positive_count)

print(
    "Scale Pos Weight :",
    round(scale_pos_weight, 2)
)

# ============================================================
# OPTUNA OBJECTIVE
# ============================================================

def xgb_objective(trial):

    params = {

        "n_estimators": trial.suggest_int(
            "n_estimators",
            200,
            800,
            step=100
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            2,
            8
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.15,
            log=True
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            20
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            0,
            5
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            0.1,
            10,
            log=True
        ),

        "scale_pos_weight": scale_pos_weight,

        "objective": "binary:logistic",

        "eval_metric": "aucpr",

        "tree_method": "hist",

        "random_state": 42,

        "n_jobs": -1
    }

    model = xgb.XGBClassifier(
        **params
    )

    model.fit(
        X_train,
        y_train,

        eval_set=[
            (X_validation, y_validation)
        ],

        verbose=False
    )

    probability = model.predict_proba(
        X_validation
    )[:, 1]

    pr_auc = average_precision_score(
        y_validation,
        probability
    )

    return pr_auc


# ============================================================
# CREATE STUDY
# ============================================================

xgb_study = optuna.create_study(
    direction="maximize",
    study_name="InsightFlow_Retention_XGB"
)

xgb_study.optimize(
    xgb_objective,
    n_trials=30,
    show_progress_bar=True
)

# ============================================================
# RESULTS
# ============================================================

print()
print("="*90)
print("XGBOOST OPTUNA RESULTS")
print("="*90)

print(
    "Best Validation PR-AUC:",
    round(
        xgb_study.best_value,
        6
    )
)

print()
print("Best Parameters:")

for key, value in xgb_study.best_params.items():

    print(
        f"{key:<25}: {value}"
    )

    # ============================================================
# 10B.8.1
# BEST XGBOOST VALIDATION MODEL
# ============================================================

best_xgb = xgb.XGBClassifier(

    **xgb_study.best_params,

    scale_pos_weight=scale_pos_weight,

    objective="binary:logistic",

    eval_metric="aucpr",

    tree_method="hist",

    random_state=42,

    n_jobs=-1
)

best_xgb.fit(
    X_train,
    y_train,

    eval_set=[
        (X_validation, y_validation)
    ],

    verbose=False
)

# ============================================================
# VALIDATION PREDICTIONS
# ============================================================

xgb_validation_probability = (
    best_xgb
    .predict_proba(X_validation)[:, 1]
)

xgb_validation_prediction = (
    xgb_validation_probability >= 0.5
).astype(int)

xgb_roc = roc_auc_score(
    y_validation,
    xgb_validation_probability
)

xgb_pr = average_precision_score(
    y_validation,
    xgb_validation_probability
)

xgb_precision = precision_score(
    y_validation,
    xgb_validation_prediction,
    zero_division=0
)

xgb_recall = recall_score(
    y_validation,
    xgb_validation_prediction,
    zero_division=0
)

xgb_f1 = f1_score(
    y_validation,
    xgb_validation_prediction,
    zero_division=0
)

print("="*90)
print("BEST XGBOOST — VALIDATION RESULTS")
print("="*90)

print("ROC-AUC   :", round(xgb_roc, 6))
print("PR-AUC    :", round(xgb_pr, 6))
print("Precision :", round(xgb_precision, 6))
print("Recall    :", round(xgb_recall, 6))
print("F1 Score  :", round(xgb_f1, 6))

# ============================================================
# 10B.8.2
# MODEL COMPARISON
# ============================================================

comparison = pd.DataFrame({

    "Model": [
        "Random Forest",
        "XGBoost"
    ],

    "ROC_AUC": [
        validation_roc,
        xgb_roc
    ],

    "PR_AUC": [
        validation_pr,
        xgb_pr
    ],

    "Precision": [
        validation_precision,
        xgb_precision
    ],

    "Recall": [
        validation_recall,
        xgb_recall
    ],

    "F1": [
        validation_f1,
        xgb_f1
    ]

})

comparison = comparison.sort_values(
    "PR_AUC",
    ascending=False
).reset_index(drop=True)

print("="*90)
print("MODEL COMPARISON")
print("="*90)

display(
    comparison.round(6)
)

# ============================================================
# SELECT WINNER
# ============================================================

winner = comparison.iloc[0]["Model"]

print()
print("="*90)
print("MODEL SELECTED")
print("="*90)

print(
    "Winner based on validation PR-AUC:",
    winner
)

[I 2026-08-19 05:59:27,761] A new study created in memory with name: InsightFlow_Retention_XGB

==========================================================================================
INSIGHTFLOW AI — PHASE 10B.8
OPTUNA-TUNED XGBOOST
==========================================================================================

Negative samples : 147162
Positive samples : 1386
Scale Pos Weight : 106.18

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-08-19 05:59:39,262] Trial 0 finished with value: 0.018061292214357674 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.010513807440255903, 'min_child_weight': 11, 'subsample': 0.8091038624392023, 'colsample_bytree': 0.99572103493498, 'gamma': 1.750146783329916, 'reg_alpha': 2.9306212171900885, 'reg_lambda': 1.5217178188752174}. Best is trial 0 with value: 0.018061292214357674.
[I 2026-08-19 05:59:47,700] Trial 1 finished with value: 0.014314183949330933 and parameters: {'n_estimators': 200, 'max_depth': 8, 'learning_rate': 0.016620243177884835, 'min_child_weight': 13, 'subsample': 0.615194636470877, 'colsample_bytree': 0.8857778694646363, 'gamma': 0.04800600174937664, 'reg_alpha': 1.7954520615066953, 'reg_lambda': 4.103032707139571}. Best is trial 0 with value: 0.018061292214357674.
[I 2026-08-19 06:00:13,182] Trial 2 finished with value: 0.019463247432257406 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.03930697450529493, 'min_child_weight': 9, 'subsample': 0.8301552003131003, 'colsample_bytree': 0.9429627235897224, 'gamma': 2.8305371296843567, 'reg_alpha': 2.5744240681646806, 'reg_lambda': 0.729060689741299}. Best is trial 2 with value: 0.019463247432257406.
[I 2026-08-19 06:00:33,093] Trial 3 finished with value: 0.018069904166780414 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.01104721946781338, 'min_child_weight': 9, 'subsample': 0.7897685234539219, 'colsample_bytree': 0.7635188541016884, 'gamma': 0.06968939208272906, 'reg_alpha': 0.6112468239262941, 'reg_lambda': 0.23230587204154765}. Best is trial 2 with value: 0.019463247432257406.
[I 2026-08-19 06:00:45,915] Trial 4 finished with value: 0.022204338916496598 and parameters: {'n_estimators': 400, 'max_depth': 2, 'learning_rate': 0.012282727017513054, 'min_child_weight': 3, 'subsample': 0.7303898038390508, 'colsample_bytree': 0.628393398192224, 'gamma': 0.8892418463218527, 'reg_alpha': 1.9144224980319269, 'reg_lambda': 0.23547860964306597}. Best is trial 4 with value: 0.022204338916496598.
[I 2026-08-19 06:01:02,126] Trial 5 finished with value: 0.01667294512045182 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.018229311241164104, 'min_child_weight': 11, 'subsample': 0.6305997185253756, 'colsample_bytree': 0.860283569774342, 'gamma': 0.16115076889932356, 'reg_alpha': 3.1944734179614933, 'reg_lambda': 0.19988421069186102}. Best is trial 4 with value: 0.022204338916496598.
[I 2026-08-19 06:01:23,021] Trial 6 finished with value: 0.020449313521726402 and parameters: {'n_estimators': 600, 'max_depth': 2, 'learning_rate': 0.022489260840210003, 'min_child_weight': 14, 'subsample': 0.6055722023327654, 'colsample_bytree': 0.6893251908361678, 'gamma': 0.7660027894396465, 'reg_alpha': 2.893048440561376, 'reg_lambda': 8.726487930971064}. Best is trial 4 with value: 0.022204338916496598.
[I 2026-08-19 06:01:42,196] Trial 7 finished with value: 0.02045811914907652 and parameters: {'n_estimators': 600, 'max_depth': 3, 'learning_rate': 0.011439940014875648, 'min_child_weight': 3, 'subsample': 0.8373199495276036, 'colsample_bytree': 0.9499646944082019, 'gamma': 0.039669166251606325, 'reg_alpha': 3.2204135518036154, 'reg_lambda': 0.15054245588356985}. Best is trial 4 with value: 0.022204338916496598.
[I 2026-08-19 06:01:50,771] Trial 8 finished with value: 0.020151672373167364 and parameters: {'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.029211049045570255, 'min_child_weight': 20, 'subsample': 0.7598976043904896, 'colsample_bytree': 0.7919086060149713, 'gamma': 4.938007107710518, 'reg_alpha': 0.37230723058384596, 'reg_lambda': 0.6581744133055824}. Best is trial 4 with value: 0.022204338916496598.
[I 2026-08-19 06:02:23,309] Trial 9 finished with value: 0.02638373929765824 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.13928663051530507, 'min_child_weight': 14, 'subsample': 0.6094604567100735, 'colsample_bytree': 0.8029180990408332, 'gamma': 1.8300359829078365, 'reg_alpha': 1.6382779089745543, 'reg_lambda': 0.34310769922234435}. Best is trial 9 with value: 0.02638373929765824.
[I 2026-08-19 06:02:53,446] Trial 10 finished with value: 0.033719751111407265 and parameters: {'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.14638616870815369, 'min_child_weight': 20, 'subsample': 0.9694777031704178, 'colsample_bytree': 0.7498873741156359, 'gamma': 3.8373372347679946, 'reg_alpha': 4.790930963470773, 'reg_lambda': 2.222133188488224}. Best is trial 10 with value: 0.033719751111407265.
[I 2026-08-19 06:03:20,391] Trial 11 finished with value: 0.022381455634157138 and parameters: {'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.13194809990079465, 'min_child_weight': 19, 'subsample': 0.997873436221494, 'colsample_bytree': 0.762016765036723, 'gamma': 3.6576702548147515, 'reg_alpha': 4.350583962690633, 'reg_lambda': 2.4267788015092826}. Best is trial 10 with value: 0.033719751111407265.
[I 2026-08-19 06:03:49,066] Trial 12 finished with value: 0.037559643787942604 and parameters: {'n_estimators': 800, 'max_depth': 7, 'learning_rate': 0.1488858708403417, 'min_child_weight': 17, 'subsample': 0.9754743544069796, 'colsample_bytree': 0.8226964870116769, 'gamma': 2.8100470066381042, 'reg_alpha': 4.561057067213456, 'reg_lambda': 0.7390484651826196}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:04:18,358] Trial 13 finished with value: 0.02950343727445886 and parameters: {'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.08024070527365196, 'min_child_weight': 18, 'subsample': 0.9926515117271804, 'colsample_bytree': 0.7034485752733572, 'gamma': 3.715659909707621, 'reg_alpha': 4.924234790478036, 'reg_lambda': 1.2603700996780243}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:04:51,840] Trial 14 finished with value: 0.03271349668933893 and parameters: {'n_estimators': 800, 'max_depth': 8, 'learning_rate': 0.07549016642086787, 'min_child_weight': 17, 'subsample': 0.919196577646733, 'colsample_bytree': 0.852036232622448, 'gamma': 3.582316202784146, 'reg_alpha': 4.031191323701858, 'reg_lambda': 5.039118309239651}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:05:20,063] Trial 15 finished with value: 0.02862653365070843 and parameters: {'n_estimators': 700, 'max_depth': 6, 'learning_rate': 0.09459480901894488, 'min_child_weight': 16, 'subsample': 0.9155947545387757, 'colsample_bytree': 0.7039425029330325, 'gamma': 4.757059495386827, 'reg_alpha': 4.9824880372693965, 'reg_lambda': 0.5308655474781805}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:05:43,558] Trial 16 finished with value: 0.028003972053074803 and parameters: {'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.0568863651753338, 'min_child_weight': 20, 'subsample': 0.9282690804511581, 'colsample_bytree': 0.600767859308176, 'gamma': 2.811206763704253, 'reg_alpha': 3.9929636292227775, 'reg_lambda': 1.4732729359394976}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:06:15,117] Trial 17 finished with value: 0.02712380776739413 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.11152982935622088, 'min_child_weight': 16, 'subsample': 0.9511783713614841, 'colsample_bytree': 0.8216806370420566, 'gamma': 4.262320698282896, 'reg_alpha': 4.393223794129464, 'reg_lambda': 2.773180864025266}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:06:41,886] Trial 18 finished with value: 0.01934812117042392 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.056396130959326864, 'min_child_weight': 17, 'subsample': 0.8772855133343709, 'colsample_bytree': 0.7355891966570876, 'gamma': 2.797285483023443, 'reg_alpha': 3.722493923969523, 'reg_lambda': 0.862228406459574}. Best is trial 12 with value: 0.037559643787942604.
[I 2026-08-19 06:07:01,228] Trial 19 finished with value: 0.04053205018363268 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.14872442170630554, 'min_child_weight': 1, 'subsample': 0.961458436651822, 'colsample_bytree': 0.6600971682954958, 'gamma': 1.9439415541817497, 'reg_alpha': 4.468091051293833, 'reg_lambda': 0.10321457155211901}. Best is trial 19 with value: 0.04053205018363268.
[I 2026-08-19 06:07:24,661] Trial 20 finished with value: 0.0417515806468967 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.10276158595301926, 'min_child_weight': 6, 'subsample': 0.8990718024010728, 'colsample_bytree': 0.6520068963598644, 'gamma': 2.067341491504658, 'reg_alpha': 3.6335933768928177, 'reg_lambda': 0.10182302142698876}. Best is trial 20 with value: 0.0417515806468967.
[I 2026-08-19 06:07:48,532] Trial 21 finished with value: 0.04112454008602196 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.0981736354419778, 'min_child_weight': 1, 'subsample': 0.8806206318182447, 'colsample_bytree': 0.6618367463424317, 'gamma': 2.1108567894581816, 'reg_alpha': 3.6142826421724714, 'reg_lambda': 0.11255469003830966}. Best is trial 20 with value: 0.0417515806468967.
[I 2026-08-19 06:08:12,664] Trial 22 finished with value: 0.043912857645533564 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.10187055073643628, 'min_child_weight': 1, 'subsample': 0.8817373528722718, 'colsample_bytree': 0.6548759116617787, 'gamma': 2.0205035292589937, 'reg_alpha': 3.5426016677895076, 'reg_lambda': 0.10144695423169516}. Best is trial 22 with value: 0.043912857645533564.
[I 2026-08-19 06:08:36,350] Trial 23 finished with value: 0.03654296448414979 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.06357808053988569, 'min_child_weight': 5, 'subsample': 0.881070323375617, 'colsample_bytree': 0.6529965348904562, 'gamma': 2.310055338035189, 'reg_alpha': 3.5721763171409036, 'reg_lambda': 0.10813193974947395}. Best is trial 22 with value: 0.043912857645533564.
[I 2026-08-19 06:08:58,281] Trial 24 finished with value: 0.044424258601312376 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.10156605210467738, 'min_child_weight': 6, 'subsample': 0.8735869642370792, 'colsample_bytree': 0.6001659619068311, 'gamma': 1.2885667189260923, 'reg_alpha': 2.2377775279399037, 'reg_lambda': 0.14961266976948392}. Best is trial 24 with value: 0.044424258601312376.
[I 2026-08-19 06:09:20,655] Trial 25 finished with value: 0.028777255915941678 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.04317882269759382, 'min_child_weight': 6, 'subsample': 0.8735735438159828, 'colsample_bytree': 0.6133547087016321, 'gamma': 1.362125945218235, 'reg_alpha': 2.2760237591171815, 'reg_lambda': 0.3303713667037546}. Best is trial 24 with value: 0.044424258601312376.
[I 2026-08-19 06:09:34,863] Trial 26 finished with value: 0.03488935844092825 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.10929629998129473, 'min_child_weight': 6, 'subsample': 0.8508969777919757, 'colsample_bytree': 0.6357940707580075, 'gamma': 1.3107637867530049, 'reg_alpha': 1.0539301982305918, 'reg_lambda': 0.1627729780183675}. Best is trial 24 with value: 0.044424258601312376.
[I 2026-08-19 06:09:53,357] Trial 27 finished with value: 0.02191680578579014 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.07938664945967001, 'min_child_weight': 8, 'subsample': 0.7037823766621577, 'colsample_bytree': 0.6858600015508745, 'gamma': 1.324154426722209, 'reg_alpha': 2.356890040858602, 'reg_lambda': 0.3575992593716497}. Best is trial 24 with value: 0.044424258601312376.
[I 2026-08-19 06:10:20,239] Trial 28 finished with value: 0.045390943572428115 and parameters: {'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.06543417863161909, 'min_child_weight': 5, 'subsample': 0.9030460395771575, 'colsample_bytree': 0.600688192062359, 'gamma': 2.4406822908447077, 'reg_alpha': 1.3002659488246766, 'reg_lambda': 0.14989517550032094}. Best is trial 28 with value: 0.045390943572428115.
[I 2026-08-19 06:10:48,853] Trial 29 finished with value: 0.033445162561388235 and parameters: {'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.04760615910582292, 'min_child_weight': 3, 'subsample': 0.7975522547937073, 'colsample_bytree': 0.6056716112907502, 'gamma': 2.436077432326708, 'reg_alpha': 1.3957994423691973, 'reg_lambda': 0.14877175130249687}. Best is trial 28 with value: 0.045390943572428115.

==========================================================================================
XGBOOST OPTUNA RESULTS
==========================================================================================
Best Validation PR-AUC: 0.045391

Best Parameters:
n_estimators             : 600
max_depth                : 8
learning_rate            : 0.06543417863161909
min_child_weight         : 5
subsample                : 0.9030460395771575
colsample_bytree         : 0.600688192062359
gamma                    : 2.4406822908447077
reg_alpha                : 1.3002659488246766
reg_lambda               : 0.14989517550032094
==========================================================================================
BEST XGBOOST — VALIDATION RESULTS
==========================================================================================
ROC-AUC   : 0.616028
PR-AUC    : 0.045391
Precision : 0.094293
Recall    : 0.14902
F1 Score  : 0.115502
==========================================================================================
MODEL COMPARISON
==========================================================================================

           Model   ROC_AUC    PR_AUC  Precision    Recall        F1
0        XGBoost  0.616028  0.045391   0.094293  0.149020  0.115502
1  Random Forest  0.617239  0.022977   0.052726  0.077124  0.062633

==========================================================================================
MODEL SELECTED
==========================================================================================
Winner based on validation PR-AUC: XGBoost